### ISSUE TITLE
Midi Sequencer

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#10]
In http://csound.github.io/docs/manual/UsingRealTime.html i read about Linux Midi:
"MIDI Input
Csound does not automatically create its own ALSA sequencer port. It creates an ALSA raw midi port each time it runs"

I am using a Linux system with Jack and have set the Midi Driver option of Alsa to Midi Sequencer - instead of Midi Raw Mode. So this works. But i would like to know more about the differences between them and when to choose one.
At least the option of Midi Sequencer could be mentioned - personally i don't know much about the Midi Sequencer itself, apart from being newer. I'd like more info.

**Comment by vlazzarini** [comment]
Tito added the sequencer code at some point, but it was never announced nor documented. I only found out when I saw it in the rtalsa source. I am not quite sure how it is supposed to work, as I don't often use midi in linux. I agree we need to change this and document it properly

**Comment by tjingboem** [comment]
i could contact and ask David Philips about Raw Midi versus Midi Sequencer. as I believe he can be a bridge between Csound and Alsa Midi. 
Just letting the manual user know that Csound has this choice between the 2 midi drivers since a few years and telling the advantages of the newer Midi Sequencer driver over the old Midi Raw would be enough, i think.

**Comment by vlazzarini** [comment]
I think it's a good idea to consult him.

**Comment by tjingboem** [comment]
I was not able to get in contact with Dave.
I asked around for a good&simple site about Midi Sequencer and the differences with Raw Midi.

This is the text that i can come up with, a text that could be inserted in the Linux Midi section:
"Since version 5.15, the Csound midi system is expanded with a second Alsa Midi driver, the Midi Sequencer. This driver is preferred above the use of the Midi Raw driver.  
There are several advantages using the Midi Sequencer:
- Multiple concurrent access 
- Scheduled by priority queues 
- Real-time event dispatching 
i.e., the role of the Midi Sequencer is to deliver events at the right time (sequence) to the right destination (device)."

There is also a nice picture of the ALSA structure:
![archtect](https://cloud.githubusercontent.com/assets/6670911/6738299/6c092e36-ce71-11e4-93f2-973e27919640.gif)

All this i found on: http://www.alsa-project.org/~tiwai/lk2k/lk2k.html

**Comment by tjingboem** [comment]
added Alsa Sequencer info to documentation
