### ISSUE TITLE
scans

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#102]
scans in the manual:
iorder (optional, default=0) -- order of interpolation used internally. It can take any value in the range 1 to 4, and defaults to 4, which is quartic interpolation. The setting of 2 is quadratic and 1 is linear.

-must not default=0 be default=4?
-The setting of 2 is quadratic and 1 is linear. What are 4 and 4?

**Comment by jpffitch** [comment]
Default is 0 which is mapped internally to 4. I think 3 is cubic but away from the code

**Comment by jpffitch** [comment]
Manual changed
==John ffitch
