### ISSUE TITLE
PDFs cannot be created with recent versions of FOP

### ISSUE THREAD

**Issue by nwhetsell** [csound/manual#105]
As @fggp wrote at https://listserv.heanet.ie/cgi-bin/wa?A2=CSOUND-DEV;27fa5c45.1701, PDFs of the manual are created using FOP 0.20.5, which [was released on July 18, 2003 and is no longer maintained](https://xmlgraphics.apache.org/fop/status.html). The current version of FOP is 2.1, released January 15, 2016.

Multiple users have reported issues building the manual using recent versions of FOP, including @DaveSeidel [with FOP 1.1](https://listserv.heanet.ie/cgi-bin/wa?A2=ind1701&L=CSOUND-DEV&P=6990) and yours truly [with FOP 2.0](https://github.com/csound/manual/pull/40).

Please consider either

1. using a more recent (preferably the latest) version of FOP to create PDFs of the manual, or
2. describing in the [README.md](https://github.com/csound/manual/blob/master/README.md) exactly how one can obtain FOP 0.20.5 so that one can create PDFs of the manual.

Either way, it would also seem to be a good idea to perform some continuous integration ([Travis CI](https://travis-ci.org), [Circle CI](https://circleci.com), [AppVeyor](https://www.appveyor.com)) to show not only that PDFs can indeed be built using the prerequisites mentioned at https://github.com/csound/manual#building-the-manual, but also to make sure that future commits don’t break the manual (like https://listserv.heanet.ie/cgi-bin/wa?A2=ind1609&L=CSOUND-DEV&P=57847).

**Comment by fggp** [comment]
Some fop extensions (fox:outline, fox:label) are replaced with bookmark
feature in XSL 1.1. XSL 1.0 generates these extensions, which need
fop-0.20.5. I changed README.md accordingly.

François

2017-01-04 9:42 GMT+01:00 Nate Whetsell <notifications@github.com>:

**Comment by nwhetsell** [comment]
Is FOP 0.20.5 still a requirement after commit 6f4934b36881396a269670be5be5ebcf3a6578a9 from @kunstmusik? Or is it now FOP 1.0 or 1.1?

Why not use the latest FOP?

**Comment by fggp** [comment]
That did the trick. I can build the pdf file now with fop1.1 (ubuntu
14.04). I think that it should work with latest fop as well.

François

2017-01-04 17:13 GMT+01:00 Nate Whetsell <notifications@github.com>:

**Comment by nwhetsell** [comment]
> I think that it should work with latest fop as well.

Well, the way to be sure would be to test it. Travis CI with an appropriate [build matrix](https://docs.travis-ci.com/user/customizing-the-build#Build-Matrix) could test building the manual with multiple versions of FOP.

**Comment by nwhetsell** [comment]
Commit 39fda116132f57e7c8bc44047fb53e79532a46a7 builds the manual on [Travis CI](https://travis-ci.org/csound/manual), so I’m closing this.
