### ISSUE TITLE
How are the files in this repository licensed?

### ISSUE THREAD

**Issue by nwhetsell** [csound/manual#107]
I was about to open a pull request to use the [Pygments](http://pygments.org) lexer for syntax highlighting instead of [csd2docbook.py](https://github.com/csound/manual/blob/master/csd2docbook.py)/[csd2docbook2.py](https://github.com/csound/manual/blob/master/csd2docbook2.py), when I realized that I’m not sure how this repository is licensed.

* [copying.txt](https://github.com/csound/manual/blob/master/copying.txt) makes me think the manual itself is under [GFDLv1.2](https://www.gnu.org/licenses/fdl-1.2.en.html).

* csd2docbook.py uses [LGPLv2.1](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.en.html).

* [makeframes.py](https://github.com/csound/manual/blob/master/makeframes.py), [opcodeparser.py](https://github.com/csound/manual/blob/master/opcodeparser.py), and [quickref.py](https://github.com/csound/manual/blob/master/quickref.py) use [GPLv3](https://www.gnu.org/licenses/gpl-3.0.en.html).

* [csound.css](https://github.com/csound/manual/blob/master/csound.css) says it uses a GNU Free Documentation License (no version is specified), even though it’s arguably not documentation.

(This situation is not helped by the massive amount of duplication between this repository and [csound/manual-fr](https://github.com/csound/manual-fr).)

So, what’s the actual license? Is there more than one? Does the presence of GPL-licensed code change anything?

I was intending to add some CSS generated by Pygments, which uses a [2-clause BSD license](https://bitbucket.org/birkenfeld/pygments-main/src/default/LICENSE), to csound.css, but now I’m wondering if that’s possible.

**Comment by gogins** [comment]
All licenses should be compatible with LGPL v2. All "open source" as
opposed to "free software" licenses are. If one of OUR licenses is not, it
should simply be changed to LGPL v2. In other cases, if the free software
is not built into our software,  e.g. if it is only a tool we make to use
our software, that is fine. If free software is built into Csound, it must
be replaced or removed.

Background: first Csound was proprietary, then under pressure from us it
was made GPL, then at my urging it was made LGPL to permit the widest
possible variety of uses. I'm not sure everyone followed or understood
this.

Regards,
Mike

**Comment by nwhetsell** [comment]
Well, [IANAL](https://en.wikipedia.org/wiki/IANAL), as they say, but I didn’t have to go far to find [some criticism of the GFDL](https://en.wikipedia.org/wiki/GNU_Free_Documentation_License#Criticism). I’m really not sure whether it’s compatible with [LGPLv2.0](https://www.gnu.org/licenses/old-licenses/lgpl-2.0.html) or [LGPLv2.1](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.html).

What I’m thinking of doing is not touching [csound.css](https://github.com/csound/manual/blob/master/csound.css) and adding the new styles in their own file. This slightly complicates building the HTML files, but I don’t see another way unless [csound.css](https://github.com/csound/manual/blob/master/csound.css) is relicensed (François Pinot and Andrés Cabrera are listed as the authors).

> If one of OUR licenses is not, it should simply be changed to LGPL v2.

Does this mean [makeframes.py](https://github.com/csound/manual/blob/master/makeframes.py), [opcodeparser.py](https://github.com/csound/manual/blob/master/opcodeparser.py), and [quickref.py](https://github.com/csound/manual/blob/master/quickref.py) should be relicensed? (I think these are also by Andrés Cabrera and François Pinot.)

To avoid license issues, it might make sense to extract the scripts and such for building this manual (and the French translation) into a new, LGPL-licensed csound/manual-distribution repository, so that either manual could be built using, for example,

```sh
cd csound/manual-distribution
git clone https://github.com/csound/manual.git
make pdf
```

or

```sh
cd csound/manual-distribution
git clone https://github.com/csound/manual-fr.git manual
make pdf
```

**Comment by vlazzarini** [comment]
For sake of simplicity, I would prefer everything to be on one license; since most of the things are LGPL, it would be good to keep it that way. There are some legacy issues with the scanning opcodes, to which it would be good to avoiding adding further issues. My 0.1 eur.

**Comment by kunstmusik** [comment]
I read through some of my mail archives and it looks like the choice of GFDL was a decision by MIT for the documentation and LGPL for Csound's source code. 

We could probably replace/relicense the build scripts as it is not part of the documentation source, but rather the build tools to build the documentation.  csound.css might be relicensed/replaced too, as far as I understand.  Relicensing the documentation source (i.e., the docbook xml files) though would be onerous.  

@fsateler , @mantaraya36 : thoughts on all of this?

**Comment by gogins** [comment]
Please keep it simple. The python scripts are tools, GPL is OK for that.
Let's ask the authors to change the license but it doesn't really matter.

Also ask them to change the .css license but if that doesn't happen,  let's
just write a new one under LGPL.

Regards,
Mike

**Comment by nwhetsell** [comment]
To my mind, the simplest thing would be to:

1. Move everything that’s not really XML of either the English or French manual — the build scripts, really — to its own repository, and add a LICENSE.txt or LICENSE.md file containing some version of the LGPL (or other permissive license) to this repository. From that point on, anything written to build the manual is LGPL-licensed. This might entail rewriting [makeframes.py](https://github.com/csound/manual/blob/master/makeframes.py), [opcodeparser.py](https://github.com/csound/manual/blob/master/opcodeparser.py), and [quickref.py](https://github.com/csound/manual/blob/master/quickref.py). We could probably use [docbook5/makeframes.xsl](https://github.com/csound/manual/blob/docbook5/makeframes.xsl) and [docbook5/quickref.py](https://github.com/csound/manual/blob/docbook5/quickref.py) as a starting point; I wrote both and left the license information intact, but they’re completely different implementations.

2. Leave the actual XML of the English and French versions of the manual in their respective repositories, and add a LICENSE.txt or LICENSE.md file containing the [GFDLv1.2](https://www.gnu.org/licenses/fdl-1.2.en.html) to these repositories.

This way, the license should appear at the top of each repository page (as it does at [csound/csound](https://github.com/csound/csound)), and there will be no ambiguity.

**Comment by fsateler** [comment]
The GFDL without invariant sections (which I think applies to the manual) is free and compatible with GPL and LGPL. 

My own TLDR conclusion from the time I investigated this (but of course IANAL either) is that the manual is GFDL-1.2+. Some build tools are GPL or LGPL, but since they are not shipped as part of the manual and only used during build they do not affect the licensing of the manual.
