### ISSUE TITLE
ableton link man pages break a html filename pattern

### ISSUE THREAD

**Issue by hlolli** [csound/manual#113]
The opcode prefix on all the new ableton link opcode https://csound.github.io/docs/manual/opcodeslinktemposet.html would better be
https://csound.github.io/docs/manual/link_tempo_set.html etc.

In my usecase, I search for the html page when looking for docs in my emacs. I can change it and make a PR if it's ok to change it?

**Comment by vlazzarini** [comment]
go ahead with a PR please.
