### ISSUE TITLE
opcode (udo) entry

### ISSUE THREAD

**Issue by Oeyvind** [csound/manual#115]
The entry for opcode (http://www.csounds.com/manual/html/opcode.html) states that strings are allowed as input to opcode, and only at i-rate.
It seems to me that string types does indeed work both as input and output, and that k-rate strings also work.  The manual text should be updated to accordingly.

Here's an example:

<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>

opcode Kstring, S, Sk
  Stest, kx xin 
  Stest1 sprintfk "%s %i", Stest, kx
  xout Stest1
endop

instr 1
Sin = "test"
k1 init 0
k1 += 1
Sout Kstring Sin, k1
puts Sout, k1+1
endin
        
</CsInstruments>
<CsScore>
i1 0 .01 
e
</CsScore>
</CsoundSynthesizer>

**Comment by jpffitch** [comment]
Sorry but I failed to find that in the source of opcode.xml.  Could you check to see if it is still wrong in the words and quote them to me here, or confirm it is OK now

**Comment by tgrey1** [comment]
Digging up a fossil here...

On opcode.xml/opcode.html the table showing input types and rates says:
`S | string variable | i-rate string | i-time`

And the output table doesn't mention strings at all.

I suggest both tables say:
`S | string variable | k- and i-rate string | i-time and k-rate`

**Comment by tgrey1** [comment]
I think this can be closed now, but would love confirmation from someone that knows better than I... Tests seem to indicate UDOs currently work these ways with strings.
