### ISSUE TITLE
examples/mtof-ftom.csd contains a syntax error

### ISSUE THREAD

**Issue by nwhetsell** [csound/manual#117]
Attempting to run [mtof-ftom.csd](https://github.com/csound/manual/blob/master/examples/mtof-ftom.csd) results in

```
error: syntax error, unexpected NEWLINE, expecting '='  (token "
") from file mtof-ftom.csd (1)
 line 10:
>>>A4 <<<
Parsing failed due to invalid input!
Stopping on parser failure
cannot compile orchestra
```

**Comment by joachimheintz** [comment]
obviously it should read
A4 = 440

i have pushed this fix.  if this is sufficient (not sure if anything in 
the xml has to be changed, too), this issue can be closed.
