### ISSUE TITLE
update to OPCODE6DIR64

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#12]
On the page http://csound.github.io/docs/manual/Configuring.html there is still talk about OPCODEDIR64 etc., but Csound6 needs OPCODE6DIR64

Personally i think the "old" OPCODEDIR64 etc. can stay, but it must be clear that with Csound6 there is another situation

**Comment by vlazzarini** [comment]
yes, we need to change this

**Comment by jpffitch** [comment]
hanged in source of manual
