### ISSUE TITLE
Update readme to include docbook-xsl brew package for MacOSX

### ISSUE THREAD

**Issue by benmca** [csound/manual#129]
xsl stylesheets are in a separate brew package: docbook-xsl. To run 'make' on my macbook running 10.12.6, it was necessary to do

`brew install dockbook-xsl`

then export XSL_BASE_PATH as indicated in the docs:

`export XSL_BASE_PATH='/usr/local/Cellar/docbook-xsl/1.79.1/docbook-xsl/'`

**Comment by kunstmusik** [comment]
Fixed by PR #130
