### ISSUE TITLE
fout iformat=2 creates 8bit not 16 bit file

### ISSUE THREAD

**Issue by joachimheintz** [csound/manual#135]
as the title suggests, i think there is a typo (since ever?) in the manual page for fout. iformat = 2 is described as: 
2 - 16-bit integers with a header. The header type depends on the render (-o) format. For example, if the user chooses the AIFF format (using the -A flag), the header format will be AIFF type.

i have just rendered files with iformat = 12 (wav plus iformat=2), and i got 8 bit files.

if someone reading the sources confirms, i can correct this in the manual.

**Comment by jpffitch** [comment]
Not sure what the manual says but 
0.  Raw float
1.  Raw 16 bit
2.  16 bit pcm
3.  Ulaw
4.  16bit
5.  32 bit
6.  Float
7.  Unsigned 8
8.  24 bit
9.  Double fpt
10. Wav
11. 8bit signed wav
12. Alaw wav
13. Ulaw wav
14. 16bit wav
Etc to 50

2 and 4 are the same which seems wrong.  I think 2 should be an eight bit format


⁣Sent from TypeApp ​

**Comment by joachimheintz** [comment]
thanks.  i have come closer to my problem.  i thought i can use 10 (for 
wav) plus 2 (for 16 bit), but i overlooked the tricky second half of 
this sentence:

"In addition, Csound versions 5.0 and later allow for explicitly 
selecting a particular header type by specifying the format as 10 * 
fileType + sampleFormat, where fileType may be 1 for WAV, 2 for AIFF, 3 
for raw (headerless) files, and 4 for IRCAM; sampleFormat is one of the 
above values in the range 0 to 9, except sample format 0 is taken from 
the command line (-o), format 1 is 8-bit signed integers, and format 2 
is a-law."

this means:
iformat = 2 is 16 bit, but
iformat = 12 is 8 bit, whereas
iformat = 14 is really 16 bit.

not quite intuitive, but no error in the manual.  i will close this issue.
