### ISSUE TITLE
Multithreadig and opcode monitor

### ISSUE THREAD

**Issue by fggp** [csound/manual#140]
When running the example of the monitor opcode in the manual with the command "csound -j1 monitor.csd", everything is OK. When running "csound -jn monitor.csd" with n >= 2 the fout_all.wav file generated through the monitor opcode contains distorded signal.

**Comment by jpffitch** [comment]
Looks like monitor does not have the necessary semantic information to ensure it is run after the other Opcodes.  Not sure at present what it should say.  
Actually not sure what monitor does and it is too early in the day to have a computer on.
⁣Sent from TypeApp ​

**Comment by jpffitch** [comment]
Please test; this is not really a manual issue though -- coding issue

**Comment by fggp** [comment]
I filed the issue in the wrong place, sorry.
It's working now. Thanks John.
