### ISSUE TITLE
Manual build error

### ISSUE THREAD

**Issue by hlolli** [csound/manual#151]
I'll try to debug this but this is the error I'm getting

```
Traceback (most recent call last):
  File "csd2docbook.py", line 373, in <module>
    CsoundScoreLexer.tokens['root'][3] = (stateTuple[0], Token.Name.Builtin, stateTuple[2])
IndexError: tuple index out of range
make[1]: *** [Makefile:700: examples-xml/stamp] Error 1
```

Using python 2.7.15 and pygments 2.3.1 on NixOs

**Comment by fggp** [comment]
Here it works fine: latest pull of the manual from github, Python 2.7.15,
Pygments 2.3.1, Ubuntu 18.04.2

François

**Comment by hlolli** [comment]
This only happens on the tag 6.12.0 but not on the master branch. Something was fixed there in between. Maybe time to make a release, for package managers?
