### ISSUE TITLE
remark in fluidControl page not correct

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#157]
the manual page of fluidControl states: 
"In this implementation, SoundFont effects such as chorus or reverb are used if and only if they are defaults for the preset.There is no means of turning such effects on or off, or of changing their parameters, from Csound."

i do not think that the last remark is correct:
- Chorus and Reverb _can_ be switched ON or OFF using fluidEngine:
ienginenum fluidEngine [iReverbEnabled] [, iChorusEnabled] [,iNumChannels] [, iPolyphony] 

- values for depth of reverb and chorus can be set with fluidCCi or fluidCCk:
fluidCCk giengine, 1, 91, kvalue ;CC 91 = reverb depth
fluidCCk giengine, 1, 93, kvalue ;CC 93 = chorus depth

i was not able to find out how to set reverb or chorus to different hall types or other chorus parameters such as number of delays in chorus etc.

So: reverb and chorus can be set to ON or OFF by Csound, and only depth of reverb and chorus can be changed.

**Comment by jpffitch** [comment]
Thank you. I have adjust that paragraph.

⁣Sent from TypeApp ​

**Comment by tjingboem** [comment]
manual is adjusted
