### ISSUE TITLE
instr opcode does not mention named instruments

### ISSUE THREAD

**Issue by jpffitch** [csound/manual#163]
Still original words with numeric instruments only.  There is a separate page about named instruments but they need to be amalgamated at least in the reference section.

**Comment by tjingboem** [comment]
Link to https://csound.com/manual/OrchNamedInstruments.html and a bit of text on the topic

**Comment by tjingboem** [comment]
changed text from 'must be numbers' to 'must be numbers or names'
and added the link to Named Instruments
