### ISSUE TITLE
update loscilx page

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#17]
loscilx needs good info and a good example

**Comment by jpffitch** [comment]
losilx needs iformation!  What does it do?

**Comment by jpffitch** [comment]
Rewritten and a simple example inserted.Please check`

**Comment by tjingboem** [comment]
i rewrote the example a bit to expose the meaning of losilx better. It shows the purpose of ibeat and the transpose of pitch. 
The old example sounded more like a kalasnikov, not showing different settings of losilx.

This would, in my opinion, a better example for the manual. If you agree, you can replace it with the old one.

<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac     ;;;realtime audio out
;-iadc    ;;;uncomment -iadc if realtime audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o loscilx.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 16
nchnls = 2
0dbfs = 1.0

gS_loop = "kickroll.wav"
gisr filesr gS_loop
gilength filelen gS_loop
gibeats = 16 
gi_sampleleft ftgen 1, 0, 0, 1, gS_loop, 0, 4, 0

instr 1
    idur = p3
    iamp = p4
    ibeat = p5
    itune = p6
    ipos = ibeat / gibeats * gilength * gisr

    aenv linseg iamp, idur - 0.01, iamp, 0.01, 0
    a1, a2 loscilx aenv, itune, 1, 0, 1, ipos, 0
    outs a1, a2
endin

</CsInstruments>
<CsScore>

t 0 170

; Measure 1
i 1 0.0 1 0.707 0 1
i 1 2.0 1 0.707 8 1
i 1 4.0 1 0.707 0 2
i 1 6.0 1 0.707 8 .5

</CsScore>
</CsoundSynthesizer>

**Comment by tjingboem** [comment]
ah...the html code in the example does it tricks again...

**Comment by jpffitch** [comment]
I do not understand.  There has onyever been one examole of loscilx which 
I quite liked.....

**Comment by tjingboem** [comment]
i am still not sure what the window size and frame are all about. How big are the frames, what value ranges are expected?
istrt and iend "are measured in sample frames" too ...
can you provide some information by reading the code, John

**Comment by tjingboem** [comment]
After playing with loscilx again, i do not see too much difference with loscil(3).
2 things are different: 
1. it can take 16 channels wave files
2. iwsize (optiomal) -- window size used in interpolation. Other loscil(3) opcodes do not have this, but i don't know what values are expected. Putting in values like 0, 1, 1000, 100000000 or -100000 does not seem to have any effect on what i hear....

**Comment by vlazzarini** [comment]
I expect the iwsize parameter to be as in diskin2 - quoting from the manual:

``
iwsize (optional, defaults to zero) -- interpolation window size, in samples. Can be one of the following:
1: round to nearest sample (no interpolation, for kpitch=1)
2: linear interpolation
4: cubic interpolation
>= 8: iwsize point sinc interpolation with anti-aliasing (slow)
``

**Comment by tjingboem** [comment]
i was looking at the code but this is abracadabra to me.
If you can look for me, i will put this quote in the manual and close this issue?

**Comment by vlazzarini** [comment]
You can put it. That's what it is.

**Comment by tjingboem** [comment]
i thank thee :)
