### ISSUE TITLE
broken fin example

### ISSUE THREAD

**Issue by hlolli** [csound/manual#170]
The example fin runs but clearly fails without crash.

```Csound
instr 1 

asnd init 0 			;input of fin must be initialized
     fin  "fox.wav", 0, 0, asnd	;read audiofile
aenv follow asnd, 0.01		;envelope follower
kenv downsamp aenv
asig rand kenv			;gate the noise with audiofile
     outs asig, asig 
endin 

</CsInstruments>
<CsScore>

i 1 0 3
e

</CsScore>
```

```
csound -odac fin.csd
0dBFS level = 32768.0
--Csound version 6.14 (double samples) Jan  1 1970
[commit: none]
libsndfile-1.0.28
UnifiedCSD:  fin.csd
STARTING FILE
Creating orchestra
closing tag
Creating score
rtaudio: ALSA module enabled
rtmidi: ALSA Raw MIDI module enabled
Elapsed time at end of orchestra compile: real: 0.001s, CPU: 0.001s
sorting score ...
	... done
Elapsed time at end of score sort: real: 0.001s, CPU: 0.001s
graphics suppressed, ascii substituted
0dBFS level = 1.0
orch now loaded
audio buffered in 256 sample-frame blocks
ALSA output: total buffer size: 1024, period size: 256
writing 512 sample blks of 64-bit floats to dac
SECTION 1:
new alloc for instr 1:
Closing file 'fox.wav'...
B  0.000 ..  3.000 T  3.000 TT  3.000 M:338519533192411586237765885103873982464.00000338519533192411586237765885103873982464.00000
	 number of samples out of range:    43647    43647
Score finished in csoundPerform().
inactive allocs returned to freespace
end of score.		   overall amps:338519533192411586237765885103873982464.00000338519533192411586237765885103873982464.00000
	   overall samples out of range:    43647    43647
0 errors in performance
Elapsed time at end of performance: real: 2.975s, CPU: 0.080s
517 512 sample blks of 64-bit floats written to dac
```

**Comment by jpffitch** [comment]
This looks like a csound bug not a manual one

**Comment by jpffitch** [comment]
Indeed it is a csound bug.  I have a kinda fix, but the opcode is not necessary as diskin does the same only better.

**Comment by AsterixMusic** [comment]
There is maybe an error in the example: 
"fox.wav" is 16 bit integers without header, so you have to write:
fin  "fox.wav", 0, 1, asnd
...but for some reason the audio seems out of range.
I tried to output the file audio and sound "distorted"
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac     ;;;realtime audio out
;-iadc    ;;;uncomment -iadc if realtime audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o fin.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1

instr 1 

asnd init 0 			;input of fin must be initialized
 fin  "fox.wav", 0, 1, asnd	;read audiofile
aenv follow asnd, 0.01		;envelope follower
asig oscili aenv, 440, 1			;gate the sine wave with audiofile
     outch 1, asig
     outch 2, asnd
endin 

</CsInstruments>
<CsScore>
f 1 0 4096 10 1
i 1 0 3
e

</CsScore>
</CsoundSynthesizer>

**Comment by jpffitch** [comment]
The manual suggests that if the input file has a header it takes precedence.  That is not what the code does. It aways opens as raw.
My revised version uses the format argument so it selects header defined (0), raw 16bit (-1),  raw floats (-2).  But not a compatible change

⁣Sent from TypeApp ​

**Comment by jpffitch** [comment]
The example now works; any other problem is a csound one.

**Comment by tgrey1** [comment]
I can't build and test csound from git on this machine, so I'll trust your assessment.  Thanks @jpffitch for fixing, and nice catch on the missing header @tjingboem!
