### ISSUE TITLE
missing syntax for cmp

### ISSUE THREAD

**Issue by joachimheintz** [csound/manual#178]
it should be added:
iOut[] cmp iA[], Sop, iB[]
iOut[] cmp iA[], Sop, ib
iOut[] cmp ia, Sop1, iB[], Sop2, ic   ; e.g.:  iOut[]  cmp 0, "<=", iIn[], "<", 10

**Comment by jpffitch** [comment]
I do not understand the notation here.  It is Eduardo's code and he should provide the manualbentry.
