### ISSUE TITLE
missing syntax for slicearray

### ISSUE THREAD

**Issue by joachimheintz** [csound/manual#179]
i- and S- versions are missing, and obviously slicearray creates the output array (not any more needed to create before).  so probably this is right:
karray[] slicearray kinarray, istart, iend [,istride]
iarray[] slicearray iinarray, istart, iend [,istride]
Sarray[] slicearray Sinarray, istart, iend [,istride]

**Comment by jpffitch** [comment]
I have added the i and S versions.  Might be better written.
