### ISSUE TITLE
missing include file for strfromurl

### ISSUE THREAD

**Issue by joachimheintz** [csound/manual#190]
running the example returns for me:
Cannot open #include'd file http://codemist.co.uk/jpff/test.in

**Comment by jpffitch** [comment]
I e.insed a result that file but csound/curl could not find the domain ; curl alone did read it so I meet work on it

⁣Sent from TypeApp ​

**Comment by jpffitch** [comment]
I understand the problem.  Solving a different issue some time back meant that filenames had a "./" inserted at the start which messes up the URL.  Will see if I can fix

**Comment by jpffitch** [comment]
Committed a quick fix
