### ISSUE TITLE
add exp example

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#204]
like log

**Comment by AsterixMusic** [comment]
<CsoundSynthesizer>

<CsOptions>

; Select audio/midi flags here according to platform
-odac     ;;;realtime audio out
;-iadc    ;;;uncomment -iadc if realtime audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o exp.wav -W ;;; for file output any platform

</CsOptions>
<CsInstruments>

; By Stefano Cucchi 2020

sr = 44100
kr = 4410
nchnls = 2
0dbfs =1


instr 1
i1 = exp(2) 
; BASE = e (2,71828 18284 59045 23536...)
; EXPONENT = 2
print i1
endin



</CsInstruments>
<CsScore>
i 1 0 1
e
</CsScore>
</CsoundSynthesizer>
