### ISSUE TITLE
new example tableshuffle

### ISSUE THREAD

**Issue by AsterixMusic** [csound/manual#205]
```csound
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac   ;;;realtime audio out
;-iadc    ;;;uncomment -iadc if realtime audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o tableshuffle.wav -W ;;; for file output any platform

; By Stefano Cucchi 2020

</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs = 1

instr 1 
kIndex phasor 1/p3
kIndex = kIndex * 16

if kIndex >= 15.99 then 
tableshuffle 2; shuffle table 2
endif

kFreq table kIndex, 2, 0
asound oscili 0.3, kFreq, 1
outch 1, asound
outch 2, asound

endin

</CsInstruments>
<CsScore>

f 1 0 4096 10 1 0 1 0 1
f 2 0	16	-2	200 250 300 350 400 450 500 550 600 650 700 750 800 850 900 950

r2
i1 0 4
s
e

</CsScore>
</CsoundSynthesizer>
```

**Comment by tjingboem** [comment]
Just a thought: if we would simplify the score a bit, like this?
r2
i1 0 4
s

becomes

i1 0 4
i1 5 4

that would leave out ' difficult'  references to score editing.
Thoughts?

**Comment by tgrey1** [comment]
Agreed, much clearer that way.

**Comment by AsterixMusic** [comment]
Better! or maybe without the rest between the 2 events.
i1 0 4
i1 4 4

But it's ok also:
i1 0 4
i1 5 4

**Comment by tgrey1** [comment]
The only reason I'd argue on the side of having the rest is that it makes a more clear audible separation between the first non-shuffled event and the second.  I tend to do this a lot when I'm making examples, that's really a matter of personal preference tho and I think it will be clear enough either way.

This example seems much more approachable and understandable than it did before... great job!

**Comment by tgrey1** [comment]
Can we also remove table 1?  Oscil defaults to a sine wave if no table is specified:
`asound oscili 0.3, kFreq`

We can then move other table references back to 1... sound ok?

Final version looks like this:
``` csd
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac   ;;;realtime audio out
;-iadc    ;;;uncomment -iadc if realtime audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o tableshuffle.wav -W ;;; for file output any platform

; By Stefano Cucchi 2020

</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs = 1

instr 1 
kIndex phasor 1/p3
kIndex = kIndex * 16

if kIndex >= 15.99 then 
tableshuffle 1; shuffle table 1
endif

kFreq table kIndex, 1, 0
asound oscili 0.3, kFreq
outch 1, asound
outch 2, asound

endin

</CsInstruments>
<CsScore>

f 1 0	16	-2	200 250 300 350 400 450 500 550 600 650 700 750 800 850 900 950

i1 0 4
i1 5 4
e

</CsScore>
</CsoundSynthesizer>
```

**Comment by AsterixMusic** [comment]
Ok.

**Comment by csounder** [comment]
NIce.  I really appreciate that I am discovering opcodes that I did not
realize existed!
- this one is pretty great.

THANKS!!!

*Dr. Richard Boulanger*

*Professor of Electronic Production and Design*

*Berklee College of Music*
