### ISSUE TITLE
part2text doesn't have example or even manual entry

### ISSUE THREAD

**Issue by tgrey1** [csound/manual#209]
See: https://github.com/csound/csound/issues/1348

**Comment by vlazzarini** [comment]
it does have an example

https://github.com/csound/manual/blob/master/examples/part2txt.csd

and manual entry

https://github.com/csound/manual/blob/master/opcodes/part2txt.xml

in git

**Comment by tgrey1** [comment]
Oops, I had been checking the live html version and hadn't seen that it was recently added.  Thanks, sorry about that.
