### ISSUE TITLE
spec** information

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#21]
http://csound.github.io/docs/manual/SpectralNonstand.html
i read:
"These unit generators are experimental, and subject to change between releases, they will also be joined by others later." 
Since the succes of the pvs opcodes i don't think that this will be the case.

**Comment by tjingboem** [comment]
Is it allright for everyone if i remove this phrase?

**Comment by gogins** [comment]
Fine with me. But you can put a note to the effect that the PVS opcodes
offer more functionality.

Best,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by kunstmusik** [comment]
I guess we should ask @jpffitch and Richard Dobson if there are any plans
for further constant-Q work.

**Comment by tjingboem** [comment]
i tried to contact Richard Dobson via the Nabble Csound mailinglist email, but gotr no answer. Perhaps one of you have a shorter link to him?

**Comment by tjingboem** [comment]
Richard Dobson agrees.

The sentence mentioned: "These unit generators are experimental, and subject to change between releases, they will also be joined by others later. "
Since this is no longer the case, this sentence is removed.
