### ISSUE TITLE
signum needs simplified example

### ISSUE THREAD

**Issue by tgrey1** [csound/manual#212]
The existing example can probably be made into a musical example?

Here's a first pass at a simplified example:

``` csd
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac     ;;;realtime audio out
;-iadc    ;;;uncomment -iadc if realtime audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o oscil.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr     =    44100
ksmps  =    10
nchnls =    2
0dbfs  =    1

instr 1
	iinput = p4
	isignum = signum(iinput)
	print iinput
	print isignum
endin

</CsInstruments>
<CsScore>
i1 0 .1 100
i1 + . 50
i1 + . .25
i1 + . 0
i1 + . -.25
i1 + . -50
i1 + . -100
</CsScore>
</CsoundSynthesizer>
```

Might simplify further, but I think it's a good starting point.

**Comment by vlazzarini** [comment]
Not sure about musical about if you put a sine into a signum function you should get a (dirty) square wave.

**Comment by vlazzarini** [comment]
but it can be used for modulation.

**Comment by tgrey1** [comment]
It produces a pleasing enough sound.  I figured using it as a basis with a few score based notes as a mini musical example would be pretty simple.  Or yes, using it as a modulator to a more pure sounds could be done too.

Either way, just saying that I don't feel the need to get rid of the existing example entirely, it can be worked with... but definitely wanted something that showed the mathematic concepts more clearly to make it more approachable for everyone.

**Comment by vlazzarini** [comment]
The math concept might be shown in a musical way by using modulation: put a sine through it and use two carriers in stereo. One with the smooth modulation from the sine and the other the stepping mod from the signum. What do you think?

**Comment by tgrey1** [comment]
I think that would be a great way to do it musically!  I can try to take a stab at that approach after the weekend.

**Comment by tgrey1** [comment]
I wasn't expecting to get a chance to write this until Monday, but surprise.  Here's my first try...  The score section is really just a placeholder, easily replaced with something nicer sounding.

``` csd
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac     ;;;realtime audio out
;-iadc    ;;;uncomment -iadc if realtime audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o oscil.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>
sr = 44100
ksmps = 10
nchnls = 2
0dbfs = 1

instr 1
	iFreq = p4
	iMode = p5

	; generate a sine lfo @5hz
	kMod lfo 1, 5

	; if p5 is non-zero, take the negative/positive sign of the lfo
	; this squares off the lfo!
	if(iMode!=0) then
		kMod signum kMod
	endif

	; gerate signal with modulation included
	aSig oscil kMod, iFreq

	outs aSig, aSig
endin

</CsInstruments>
<CsScore>
i1	0	.5	440
i1	+	.	550
i1	+	.	660	1 ; this event gets "squared" modulation due to non-zero p5
</CsScore>
</CsoundSynthesizer>
```

**Comment by vlazzarini** [comment]
that's what I had in mind, looks good.

**Comment by tjingboem** [comment]
both the simple and the musical examples are added
