### ISSUE TITLE
midiarp a few issues

### ISSUE THREAD

**Issue by jeanette-c** [csound/manual#221]
In the Syntax section there is a space missing between kCounter and midiarp
Convention: The second output argument is called "kCounter", where its function suggests a "usual" name for it would be "kTrig", "ktrig" or "ktrig_out" to better describe its functionality.
Also the kRate input argument could use a specification of its unit in the Initialization section (rate in Hz, rate in BPM?).
Also why is kRate under the heading "Initialization" and not "Performance". No explanation is given.

**Comment by rorywalsh** [comment]
These are good point Jeannette, and I apoligise for taking so long to fix them! I've updated the manual entry for this opcode. I'll let the manual maintainers close this out if they are happy with the updates.

**Comment by tjingboem** [comment]
done
