### ISSUE TITLE
Jacko opcodes all miss examples

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#229]
-

**Comment by gogins** [comment]
I wrote an all-in-one example here:
https://csound.com/docs/manual/JackoOpcodes.html.

Best,
Mike



-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by tjingboem** [comment]
True. I forgot it was there...
I'm thinking about a link to this example for every one of these opcodes to this page.

Can you perhaps think of another and different example situation where (some of) these opcodes would be of use?

**Comment by gogins** [comment]
Yes, link from every opcode.

Best,
Mike

**Comment by tjingboem** [comment]
Right, will do.
Can you perhaps think of another and different example situation where (some of) these opcodes would be of use?
