### ISSUE TITLE
no example GEN 43

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#231]
-

**Comment by tjingboem** [comment]
i am having fun in suppressing  some reverb and noise present in finneganswake1.flac.

Following may be part of the manual page:
![reverbnoise](https://user-images.githubusercontent.com/6670911/118308858-c082a100-b4ec-11eb-972e-b6d94e61e37e.png)
- finding the selection and duration of the reverb and noise to remove from the flac file using Audacity
- using Csound utility _pvanal_ to analyze this selection and writing  the result to a pvx file: menno@mennoASUSZ170 ~ $ pvanal -b1.04 -d0.8  finneganswake1.flac reverbnoise.pvx 
 analysing 35280 sample frames (0.8 secs) from timepoint 1.0
 frameSize=1024
1024 infrsize, 256 infrInc
....
164 1-chan blocks written to reverbnoise.pvx

[reverbnoise.pvx.zip](https://github.com/csound/manual/files/6480526/reverbnoise.pvx.zip)

- the example itself will be
```
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac      ;;;realtime audio out
;-iadc    ;;;uncomment -iadc if realtime audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o pvstencil.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

; by Menno Knevel 2021

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1

instr 1 ; original signal, includes some reverb and background noise

asig    diskin2   "finneganswake1.flac", 1
outs    asig, asig

endin

instr 2 ; reverb is masked by reverbnoise.pvx
asig    diskin2   "finneganswake1.flac", 1  
fsig    pvsanal   asig, 1024, 256, 1024, 1
fclean  pvstencil fsig, 0, 1, 1 ; maximum cleaning
aclean  pvsynth   fclean
outs aclean, aclean
endin

</CsInstruments>
<CsScore>

f1 0 -1024 -43 "reverbnoise.pvx" 0  ; can be found in examples folder
; if it does not run, you have to create the .pvx first on your system

i 1 0 12.7
i 2 15 12.7

e
</CsScore>
</CsoundSynthesizer>
```

But i have a question about the length of the table.
How can i get to know the table size of the pvx file?  Right now i use f1 0 -1024 -43 "reverbnoise.pvx" 0,
but what is the formula?

**Comment by tjingboem** [comment]
still have to investigate if table length of pvx file is now correct.
Now i do: 44100 x 2 x 0.8 = 70560
because samples/sec x (amp+freq=2) x 0.8 sec

```
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac      ;;;realtime audio out
;-iadc    ;;;uncomment -iadc if realtime audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o GEN43.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

; by Menno Knevel 2021

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1

instr 1 ; untreated signal, contains some reverb and noise

asig    diskin2   "finneganswake1.flac", 1
outs    asig, asig
endin

instr 2 ; reverb is masked by .pvx file
ipvx    ftgen 1, 0, 70560, -43, "reverbnoise.pvx", 0    ; can be found in examples folder
asig    diskin2   "finneganswake1.flac", 1  
fsig    pvsanal   asig, 1024, 256, 1024, 1
fclean  pvstencil fsig, 0, 1, ipvx ; maximum cleaning
aclean  pvsynth   fclean
outs    aclean, aclean
endin

</CsInstruments>
<CsScore>
i 1 0 12.7
i 2 15 12.7
e
</CsScore>
</CsoundSynthesizer>
```

**Comment by tjingboem** [comment]
it is getting crazier and crazier...
1. call pvanal 
2. play untreated
3. play cleaned signal

```
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac      ;;;realtime audio out
;-iadc    ;;;uncomment -iadc if realtime audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o GEN43.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

; by Menno Knevel 2021

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1

; Audacity shows the selection of reverb and noise- see screenshot

instr 1 ; analyze this selection and output result to pvx file
ires system_i 1,{{     
    pvanal -b1.04 -d0.8 finneganswake1.flac reverbnoise.pvx
        }}
endin

instr 2 ; untreated signal, contains some reverb and noise
asig    diskin2   "finneganswake1.flac", 1
outs    asig, asig
endin

instr 3 ; use .pvx file the remove reverb and noise
ipvx    ftgen 1, 0, -70560, -43, "reverbnoise.pvx", 0    ; created in instr 1
asig    diskin2   "finneganswake1.flac", 1  
fsig    pvsanal   asig, 1024, 256, 1024, 1
fclean  pvstencil fsig, 0, 1, ipvx ; maximum cleaning
aclean  pvsynth   fclean
outs    aclean, aclean
endin

</CsInstruments>
<CsScore>
i1 0   2       ; first analyze
i2 5  12.7     ; untreated signal
i3 20 12.7     ; denoised gignal
e
</CsScore>
</CsoundSynthesizer>
```
i hope someone can test?

**Comment by csounder** [comment]
Wow.  Nice.  Lots of great tricks in here to learn from and model.

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music

**Comment by csounder** [comment]
Will be testing tonight or tomorrow 

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music

**Comment by csounder** [comment]
It worked perfectly, when I ran in terminal from CsoundQt (with the latest
brew of Csound and everything simlink'd.
When I just rant from CsoundQt - it did not report any errors, but it did
not create the .pvx file and so, it only played the original file and
nothing else.


*- dB*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division

**Comment by csounder** [comment]
run in terminal seems to be required to correctly use the system_i opcode?

*- dB*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division

**Comment by tjingboem** [comment]
also check (Menno) if it is clear from the text that: 

GEN43 reads the whole file and produces 1 DFT frame.

because it was not for me-

**Comment by vlazzarini** [comment]
Well, it says this:

"This subroutine loads a PVOCEX file containing the PV analysis (amp-freq) of a soundfile and calculates the average magnitudes of all analysis frames of one or all audio channels. It then creates a table with these magnitudes for each PV bin."

How else would it create an average of all analysis frames to create a table with these magnitudes? I think anyone using this should understand first how the phase vocoder works, when they do it's not that difficult to see. 

Anyway, you can add text to this if you want.

**Comment by tjingboem** [comment]
I don't think i quite agree with you on this one. The present example on this manual page is so minimal and it is not a complete example; yes, it is meant for those who understand how the phase vocoder works and understand how to interpret this information.
But what i am hoping to achieve with a complete example is that people who do not exactly understand how the phase vocoder and GEN 43 works, will obtain easier access to this knowledge by explaining it with an example.  

My proposed example above creates a pvx file, and outputs text in the terminal the frameSize of 1024. The 2nd instrument shows the non-processed sound, and the 3rd instrument shows the table size (the 1024/2) of the pvx file. It is then used to remove the reverb and noise from the sample. The listener can compare and hear the difference.
Would you please check if my example is now complete and correct?

In instrument 3 i added:
; pvanal created 1 frame of 1024- see Csound Output
; so size of table for GEN 43 = 512 (fftsize/2)
so i don't think anything needs to be added to the manual text.

I plan to add this example once it is ready and keep the:  
f1 0 512   43  "viola.pvx" 1
f1 0 -1024 -43 "noiseprint.pvx" 0
and accompagnying text in the same section 'Examples' as they contain important information.

**Comment by csounder** [comment]
I love this example that does all the work in Csound.

I am just reporting that, at present, the cool example you shared only runs in the terminal on my Mac Catalina 

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music

**Comment by tjingboem** [comment]
Thanks, Richard.
It is true that at one point the Csound Manual Team decided that examples should work from the terminal on all major platforms, and not from some kind of frontend. 
I have had some issues with some examples as well when i used them with Blue as a frontend, so we decided to go back to the basics and we decided that all examples should work out-of-the-box from terminal.

I have always had problems with CsoundQt, hanging in Linux,quite annoying, and the CMT found the solution in working with VScode; it is an editor but when it runs, it uses the terminal.

I believe there is an option in CsoundQt where you can run from the terminal as well, bypassing the frontend side of CsoundQt? Did you try that as well?

(Hopefully we can pinpoint better what is going on, but right now it looks like a CsoundQt issue and should be reported there. I'm sure that a workaround or a repair can be found)

**Comment by csounder** [comment]
Yes.  All good.  This is exactly what I was saying.  In CsoundQt (which works pretty great on the Mac and is really appreciated by my Csound and DSP students) your cool example does run from the terminal.

I like that you do the analysis in the example.  
You should consider adding that feature to other LPC and classic PVOC examples too.

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music

**Comment by tjingboem** [comment]
Richard, i'd like to hear your opinion on the updated page for GEN43: https://csound.com/manual/GEN43.html
on 2 things if you please:
1. as English is not my native tongue, is my text okay: "This is a selection of some reverb and noise of the sound file. The selection has a duration of 0.8 seconds. We need this duration for pvanal to analyze and create the pvocex file."
2. i'm not quite satisfied with this text being below the image of Audacity- there would be a better balance between text and image if i put the text before this image i think...

The text at the bottom of the page:"This table can be used as a masking table for pvstencil and pvsmaska. The first example uses a 1024-point FFT phase vocoder analysis file from which the first channel is used. The second uses all channels of a 2048-point file, without post-normalisation. For noise reduction applications with pvstencil, it is easiest to skip table normalisation (negative GEN code)."
will be better off when it gets split, like:

"These tables can be used as a masking table for pvstencil and pvsmaska."

f1 0 512   43  "viola.pvx" 1
f1 0 -1024 -43 "noiseprint.pvx" 0

The first example uses a 1024-point FFT phase vocoder analysis file from which the first channel is used. The second uses all channels of a 2048-point file, without post-normalisation. For noise reduction applications with pvstencil, it is easiest to skip table normalisation (negative GEN code).

Regarding doing the analysis inside the example for LPC and PVOC examples, perhaps ATSA and HETRO as well- i do think this would be an upgrade for these opcodes, and it will drag them into the 21st century; having a sound file analyzed and doing something with it in one example is fast and 'modern'....and would make people consider to use them more easily...

**Comment by tjingboem** [comment]
i think it looks much better now.
If you'd check my English, i can close the issue.

**Comment by csounder** [comment]
I am happy to review the wording and get back to you tomorrow. 

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music

**Comment by tjingboem** [comment]
GEN43 got new text, removed image
