### ISSUE TITLE
no turnon example 

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#235]
-

**Comment by AsterixMusic** [comment]
```csd
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac      ;;;realtime audio out
;-iadc    ;;;uncomment -iadc if realtime audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o turnon.wav -W ;;; for file output any platform

; By Stefano Cucchi 2020

</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs = 1

gasend1 init 0
gasend2 init 0

instr 1 ; produce a sound and turn on instr 100 & 101 (effects)
 
abar barmodel  2, 2, p4, 0.000001, 0.0103, 20, p5, p6, p7
outs abar*p8, abar*p8
turnon 100 ; the instruments 100 & 101 are ON also when instr 1 is no longer playng
turnon 101 
gasend1 = gasend1 + (abar*p8)      
gasend2 = gasend2 + (abar*p8)        
endin


instr 2 ; producing another sound

a1 oscili 0.01, 440
; NO local output

gasend1 = gasend1 + a1
gasend2 = gasend2 + a1

endin

instr 100

aphaser phaser1 gasend1, 4700, 1000, -0.8
outs aphaser*0.8, aphaser*0.8
clear gasend1

endin

instr 101

afold fold  gasend2, 9
outs afold*0.5, afold*0.5
clear gasend2

endin

</CsInstruments>
<CsScore>


i 1 0 10 1  0.132 500   0.009  0.4 
i 1 7 6  14 0.02  5000  0.09   0.01
; instumennt 1 stop playing - instrument 100 & 101 are ON until the end of the score. 
i 2 13 4 ; (you can hear the sine wave of instrument 2 trough instrument 100 & 101) 

e

</CsScore>
</CsoundSynthesizer>

 ```

**Comment by csounder** [comment]
It is interesting that you are showing that the effect instruments stay on
even when turned on from another instrument and when the other instrument
is stopped
- but what is going on soundwise is not particularly clear in this example.

I would like to recommend that you

1. turn on a reverb and an echo effect
2. play several shorter notes with barmodel, so that we can clearly hear
them in a reverberant space and hear them echoing
3. the second instrument needs an envelope or some texture and
articulation, so that we can hear it in the FX clearly
4. the second instrument should play several notes as well.

Also, does turnon work from instrument 0?  (outside of any
instr/endin block?).
- if so, you might want to include an example that shows this more typical
use (first) and then this more advanced example (second)

*Dr. Richard Boulanger*

**Comment by AsterixMusic** [comment]
Another version with echo & reverb.
Added a dummy instrument to let effects play after the end of the score event.
Tried tu put "turnon" inside & outside an instrument.
Something not clear to me: 
"turnon" INSIDE a instrument: when you have a gap between notes (no events) in the score? It seems stopping.
If you put turnon100 & turnon101 inside instrument 1 you can hear a glitch at the end of the note event.
``` csd

<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac      ;;;realtime audio out
;-iadc    ;;;uncomment -iadc if realtime audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o turnon_02.wav -W ;;; for file output any platform

; By Stefano Cucchi 2020

</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs = 1

gasend1 init 0
gasend2 init 0

turnon 100
turnon 101
 
instr 1 
   
abar barmodel  2, 2, p4, 0.000001, 0.0103, 20, p5, p6, p7
kenvelope linseg 0, 0.03, 1, p3-0.06, 1, 0.03, 0
abar = abar * kenvelope * p8
; NO local output
gasend1 = gasend1 + (abar*p8)      
gasend2 = gasend2 + (abar*p8)        
endin


instr 2 

kdensity expseg 0.01, p3, 0.51
apulse mpulse 0.2, kdensity 
kenvelope linseg 0, 0.3, 1, p3-0.6, 1, 0.3, 0
apulse = apulse * kenvelope
; NO local output

gasend1 = gasend1 + apulse
gasend2 = gasend2 + apulse

endin

instr 100

aphaser phaser1 gasend1, 4700, 1000, -0.8
arevphaser reverb aphaser, 1.8
outs arevphaser*0.2, arevphaser*0.2
clear gasend1

endin

instr 101

afold fold  gasend2, 9
adelfoldL multitap afold, 0.62, 0.52, 1.19, 0.44
adelfoldR multitap afold, 0.94, 0.64, 1.426, 0.54
outs adelfoldL*0.5, adelfoldR*0.5
clear gasend2

endin
; dummy instrument to let the reverb and delay play.
instr 200

endin

</CsInstruments>
<CsScore>

i 200 0 20

i 1 0    2   1     0.132    500   0.009  0.9  
i 1 2.2  3   14    0.02     5000  0.09   0.26 
i 1 5.8  6   11    0.1      145   0.1    0.8  

i 2 11 6
e


</CsScore>
</CsoundSynthesizer>

```

**Comment by csounder** [comment]
There are some things going on with clear and with globals for sure - but
here is a version of your instrument that is a bit clearer (to me)
- you can hear the phaser in the end
- you can hear the folding
- you can hear the multiTap
- you can hear the densities of the impulses - which is very cool and I had
not ever done that - THANKS!

and you also teach to extend the score with a value after the e - statement
(which removes the need for an "empty" instrument

Hope you like it - got the inspiration from you to have some fun this
morning - thanks

<CsoundSynthesizer>


<CsOptions>

; Select audio/midi flags here according to platform

-odac ;;;realtime audio out

;-iadc ;;;uncomment -iadc if realtime audio input is needed too

; For Non-realtime ouput leave only the line below:

; -o turnon_02.wav -W ;;; for file output any platform


; By Stefano Cucchi 2020


</CsOptions>


<CsInstruments>

sr = 44100

ksmps = 32

nchnls = 2

0dbfs = 1


gasend1 init 0

gasend2 init 0


turnon 100

turnon 101

instr 1

abar barmodel 2, 2, p4, 0.000001, 0.0103, 20, p5, p6, p7

kenvelope expseg 1, p3, .01

abar = abar * kenvelope * p8

; NO local output

gasend1 = gasend1 + abar*p8

gasend2 = gasend2 + abar*p8

endin


instr 2

idenStart = p4

kdensity expseg p4, p3, 0.001

apulse mpulse 1, kdensity

kenvelope expseg 1, p3, .001

apulse = apulse * kenvelope

; NO local output

gasend1 = gasend1 + apulse

gasend2 = gasend2 + apulse

endin


instr dry

idryLeft = p4

idryRight = p5

outs gasend1*p4, gasend2*p5

endin


instr 100

aphaser phaser1 gasend1, 4700, 1000, -0.8

arevphaser reverb aphaser, 1.8

outs arevphaser*0.2, arevphaser*0.2

clear gasend1

endin


instr 101

afold fold gasend2, 9

adelfoldL multitap afold, 0.62, 0.52, 1.19, 0.44

adelfoldR multitap afold, 0.94, 0.64, 1.426, 0.54

outs adelfoldL*0.5, adelfoldR*0.5

clear gasend2

endin

</CsInstruments>


<CsScore>

i1 0 1 10 0.13 300 0.3 0.8

i2 0 3 .07

i2 0 3 .02


i1 2 2 14 0.02 500 0.2 0.7

i2 2 4 .06


i2 4 5 .05

i2 4 6 .01

i1 4.2 3 9 0.13 145 0.1 0.6

i1 4.3 3 11 0.10 245 0.2 0.5


i1 9 7 8 0.11 125 0.1 0.6

i1 9.01 6 28 0.13 280 0.3 0.8

i1 9.02 5 39 0.02 600 0.2 0.7

i1 9.03 4 39 0.02 600 0.2 0.7

i2 9.04 18 .09

i2 9.05 11 .05

i2 9.06 4 .01


i1 18 5 8.1 0.12 105 0.12 0.56

i1 18.01 6 8.8 0.13 205 0.52 0.46

i1 18.02 5 8.2 0.15 745 0.42 0.26

i1 18.03 7 8.3 0.14 905 0.62 0.36


i2 26 3 .05


i"dry" 0 25 .8 .8


e 35 ; score extended to allow for reverb and multitap tails to ring out by
keeping instr 100 and 101 "turned on" for 26 seconds (until end of score)

</CsScore>


</CsoundSynthesizer>

*Dr. Richard Boulanger*

*Professor of Electronic Production and Design*

*Berklee College of Music*

Professional Writing and Technology Division


*skype*: radiobaton

*facebook*: https://www.facebook.com/richard.boulanger.58

*about*: http://www.boulangerlabs.com/#about

*about*: http://www.csounds.com/community/developers/dr-richard-boulanger/

*music*:
http://www.csounds.com/community/developers/dr-richard-boulanger/dr-richard-boulanger-music/

*Boulanger Labs* - http://boulangerlabs.com

*The Csound Book* - http://mitpress.mit.edu/books/csound-book

*The Audio Programming Book* -
http://mitpress.mit.edu/books/audio-programming-book

**Comment by AsterixMusic** [comment]
I like it!

**Comment by csounder** [comment]
Thanks.

I made a few more changes.
- see if you like this a little better.  hope so.
- there are interesting things going on in here - haunting.

<CsoundSynthesizer>


<CsOptions>

; Select audio/midi flags here according to platform

-odac ;;;realtime audio out

;-iadc ;;;uncomment -iadc if realtime audio input is needed too

; For Non-realtime ouput leave only the line below:

; -o turnon_02.wav -W ;;; for file output any platform


; By Stefano Cucchi 2020

</CsOptions>


<CsInstruments>

sr = 44100

ksmps = 16

nchnls = 2

0dbfs = 1


gasend1 init 0

gasend2 init 0


turnon 100

turnon 101

instr 1

abar barmodel 2, 2, p4, 0.000001, 0.0103, 20, p5, p6, p7

kenvelope expseg 1, p3, .01

abar = abar * kenvelope * p8

; NO local output

gasend1 = gasend1 + abar*p8

gasend2 = gasend2 + abar*p8

endin


instr 2

idenStart = p4

kdensity expseg p4, p3, 0.001

apulse mpulse 1, kdensity

kenvelope expseg 1, p3, .001

apulse = apulse * kenvelope

; NO local output

gasend1 = gasend1 + apulse

gasend2 = gasend2 + apulse

endin


instr dry

idryLeft = p4

idryRight = p5

kgate adsr .01,.01,1,0

outs (gasend1*kgate) * p4, (gasend2*kgate) * p5

endin


instr 100

aphaser phaser1 gasend1, 4700, 1000, -0.8

arevphaser reverb aphaser, 1.618

outs arevphaser * 0.2, arevphaser * 0.2

clear gasend1

endin


instr 101

afold fold gasend2, 26

adelfoldL multitap afold, 0.62, 0.52, 1.19, 0.44

adelfoldR multitap afold, 0.94, 0.64, 1.42, 0.54

outs adelfoldL * 0.5, adelfoldR * 0.5

clear gasend2

endin

</CsInstruments>


<CsScore>

i2 0 6 .07

i "dry" 0 2 .87 .2


i1 3 4 10 0.13 300 0.3 0.8


i2 7 5 .007

i "dry" 7 3 .12 .86


i1 11 9 09 0.09 400 0.23 0.78


i2 15 9 .01

i "dry" 15 12 .94 .09


s


i "dry" 0 26.9 .78 .58


i 2 0.0 4 .07

i 2 0.1 4 .02

i 1 0.21 1 08 0.13 300 0.3 0.8


i 1 2 2 14 0.02 500 0.2 0.7

i 2 2 5 .06


i 2 4 5 .05

i 2 4 6 .01

i 1 4.3 3 9 0.08 1145 0.1 0.6

i 1 4.5 3 11 0.10 245 0.2 0.5


i 1 8.00 7 08 0.11 125 0.1 0.6

i 1 8.01 6 28 0.13 280 0.3 0.8

i 1 8.02 5 39 0.02 600 0.2 0.7

i 1 8.03 4 39 0.02 600 0.2 0.7

i 2 8.24 18 .09

i 2 8.75 11 .05

i 2 8.99 4 .01


i 1 18 9 8.1 0.12 105 0.12 0.56

i 1 18.01 8 8.8 0.13 205 0.52 0.46

i 1 18.02 7 8.2 0.15 745 0.42 0.26

i 1 18.03 11 8.3 0.14 905 0.62 0.36



i "dry" 25 .85 .32 .38

i 2 25 4 .8


i "dry" 27 .74 .62 .68

i 2 27 5 .2


i "dry" 32.3 .42 .72 .78

i 2 32.3 14 .005


i 1 36 13 9.90 0.233 333 0.23 0.63

i 1 38 12 8.79 0.323 403 0.34 0.53

i 1 41 10 7.89 0.423 583 0.42 0.73


e 53 ; score extended to allow for reverb and multitap tails to ring out by
keeping instr 100 and instr 101 "turned on" for 53 seconds (until end of
score)

</CsScore>


</CsoundSynthesizer>

*Dr. Richard Boulanger*

*Professor of Electronic Production and Design*

*Berklee College of Music*

Professional Writing and Technology Division


*skype*: radiobaton

*facebook*: https://www.facebook.com/richard.boulanger.58

*about*: http://www.boulangerlabs.com/#about

*about*: http://www.csounds.com/community/developers/dr-richard-boulanger/

*music*:
http://www.csounds.com/community/developers/dr-richard-boulanger/dr-richard-boulanger-music/

*Boulanger Labs* - http://boulangerlabs.com

*The Csound Book* - http://mitpress.mit.edu/books/csound-book

*The Audio Programming Book* -
http://mitpress.mit.edu/books/audio-programming-book

**Comment by csounder** [comment]
OK - final version from me...
- this one is a little better I think.

<CsoundSynthesizer>


<CsOptions>

; Select audio/midi flags here according to platform

-odac ;;;realtime audio out

;-iadc ;;;uncomment -iadc if realtime audio input is needed too

; For Non-realtime ouput leave only the line below:

; -o turnon_02.wav -W ;;; for file output any platform


; By Stefano Cucchi 2020

</CsOptions>


<CsInstruments>

sr = 44100

ksmps = 16

nchnls = 2

0dbfs = 1


gasend1 init 0

gasend2 init 0


turnon 100

turnon 101

instr 1

abar barmodel 2, 2, p4, 0.000001, 0.0103, 20, p5, p6, p7

kenvelope expseg 1, p3, .01

abar = abar * kenvelope * p8

; NO local output

gasend1 = gasend1 + abar*p8

gasend2 = gasend2 + abar*p8

endin


instr 2

idenStart = p4

kdensity expseg p4, p3, 0.001

apulse mpulse 1, kdensity

kenvelope expseg 1, p3, .001

apulse = apulse * kenvelope

; NO local output

gasend1 = gasend1 + apulse

gasend2 = gasend2 + apulse

endin


instr dry

idryLeft = p4

idryRight = p5

kgate adsr .01,.01,1,0

outs (gasend1*kgate) * p4, (gasend2*kgate) * p5

endin


instr 100

aphaser phaser1 gasend1, 4700, 1000, -0.8

arevphaser reverb aphaser, 1.618

outs arevphaser * 0.2, arevphaser * 0.2

clear gasend1

endin


instr 101

afold fold gasend2, 26

adelfoldL multitap afold, 0.62, 0.52, 1.19, 0.44

adelfoldR multitap afold, 0.94, 0.64, 1.42, 0.54

outs adelfoldL * 0.5, adelfoldR * 0.5

clear gasend2

endin

</CsInstruments>


<CsScore>

i2 0 6 .07

i "dry" 0 2 .87 .2


i1 3 4 10 0.13 300 0.3 0.8


i2 7 5 .007

i "dry" 7 3 .12 .86


i1 11 9 09 0.09 400 0.23 0.78


i2 15 9 .01

i "dry" 15 12 .94 .09


s


i "dry" 0 26.9 .78 .58


i 2 0.0 4 .07

i 2 0.1 4 .02

i 1 0.21 1 08 0.13 300 0.3 0.8


i 1 2 2 14 0.02 500 0.2 0.7

i 2 2 5 .06


i 2 4 5 .05

i 2 4 6 .01

i 1 4.3 3 9 0.08 1145 0.1 0.6

i 1 4.5 3 11 0.10 245 0.2 0.5


i 1 8.00 7 08 0.11 125 0.1 0.6

i 1 8.01 6 28 0.13 280 0.3 0.8

i 1 8.02 5 39 0.02 600 0.2 0.7

i 1 8.03 4 39 0.02 600 0.2 0.7

i 2 8.24 18 .09

i 2 8.75 11 .05

i 2 8.99 4 .01


i 1 18 9 8.1 0.12 105 0.12 0.56

i 1 18.01 8 8.8 0.13 205 0.52 0.46

i 1 18.02 7 8.2 0.15 745 0.42 0.26

i 1 18.03 11 8.3 0.14 905 0.62 0.36


i "dry" 25 .85 .32 .38

i 2 25 5 .71


i "dry" 27 .74 .62 .68

i 2 27 6 .11


i "dry" 32.3 .42 .32 .38

i 2 32.3 14 .005


i 1 36 13 9.9 0.233 333 0.23 0.63

i 1 39 12 8.9 0.323 403 0.34 0.53

i 1 42 10 7.8 0.123 283 0.42 0.73


i 1 48.01 9 8.11 0.122 108 0.13 0.54

i 1 48.03 8 8.82 0.135 208 0.50 0.44

i 1 48.05 7 8.23 0.158 748 0.40 0.24

i 1 48.08 11 8.35 0.147 908 0.60 0.34


e 60 ; score extended to allow for reverb and multitap tails to ring out

; keeping instr 100 and instr 101 "turned on" for 60 seconds

</CsScore>


</CsoundSynthesizer>

*Dr. Richard Boulanger*

*Professor of Electronic Production and Design*

*Berklee College of Music*

Professional Writing and Technology Division


*skype*: radiobaton

*facebook*: https://www.facebook.com/richard.boulanger.58

*about*: http://www.boulangerlabs.com/#about

*about*: http://www.csounds.com/community/developers/dr-richard-boulanger/

*music*:
http://www.csounds.com/community/developers/dr-richard-boulanger/dr-richard-boulanger-music/

*Boulanger Labs* - http://boulangerlabs.com

*The Csound Book* - http://mitpress.mit.edu/books/csound-book

*The Audio Programming Book* -
http://mitpress.mit.edu/books/audio-programming-book

**Comment by AsterixMusic** [comment]
Wonderful!
Ii noticed in the 2' section some "samples out of range" so I added a volume control in instr2 and I lowered some notes in 2' section (you can see the commented ones)

```csd

<CsoundSynthesizer>
<CsOptions>

; Select audio/midi flags here according to platform
-odac ;;;realtime audio out
;-iadc ;;;uncomment -iadc if realtime audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o turnon_02.wav -W ;;; for file output any platform


</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 16
nchnls = 2
0dbfs = 1

gasend1 init 0
gasend2 init 0

turnon 100
turnon 101

instr 1

abar barmodel 2, 2, p4, 0.000001, 0.0103, 20, p5, p6, p7
kenvelope expseg 1, p3, .01
abar = abar * kenvelope * p8
; NO local output

gasend1 = gasend1 + abar*p8
gasend2 = gasend2 + abar*p8

endin


instr 2

idenStart = p4
kdensity expseg p4, p3, 0.001
apulse mpulse 1, kdensity
kenvelope expseg 1, p3, .001
apulse = apulse * kenvelope * p5
; NO local output

gasend1 = gasend1 + apulse
gasend2 = gasend2 + apulse

endin


instr dry

idryLeft = p4
idryRight = p5
kgate adsr .01,.01,1,0
outs (gasend1*kgate) * p4, (gasend2*kgate) * p5

endin


instr 100

aphaser phaser1 gasend1, 4700, 1000, -0.8
arevphaser reverb aphaser, 1.618
outs arevphaser * 0.2, arevphaser * 0.2
clear gasend1

endin


instr 101

afold fold gasend2, 26
adelfoldL multitap afold, 0.62, 0.52, 1.19, 0.44
adelfoldR multitap afold, 0.94, 0.64, 1.42, 0.54
outs adelfoldL * 0.5, adelfoldR * 0.5
clear gasend2

endin

</CsInstruments>
<CsScore>



i2 0 6 .07  1

i "dry" 0 2 .87 .2

i1 3 4 10 0.13 300 0.3 0.8

i2 7 5 .007  1

i "dry" 7 3 .12 .86

i1 11 9 09 0.09 400 0.23 0.78

i2 15 9 .01 1


i "dry" 15 12 .94 .09


s


i "dry" 0 26.9 .68 .48 ; lowered

i 2 0.0 4 .07  1
i 2 0.1 4 .02  1

i 1 0.21 1 08 0.13 300 0.3 0.8 
i 1 2 2 14 0.02 500 0.2 0.7 

i 2 2 5 .06  0.8 ; lowered
i 2 4 5 .05  0.7 ; lowered
i 2 4 6 .01  0.6 ; lowered


i 1 4.3 3 9 0.08 1145 0.1 0.5 ; lowered
i 1 4.5 3 11 0.10 245 0.2 0.4 ; lowered

i 1 8.00 7 08 0.11 125 0.1 0.6
i 1 8.01 6 28 0.13 280 0.3 0.8
i 1 8.02 5 39 0.02 600 0.2 0.7
i 1 8.03 4 39 0.02 600 0.2 0.7

i 2 8.24 18 .09 1
i 2 8.75 11 .05 1
i 2 8.99 4 .01 1



i 1 18 9 8.1 0.12 105 0.12 0.56
i 1 18.01 8 8.8 0.13 205 0.52 0.46

i 1 18.02 7 8.2 0.15 745 0.42 0.26
i 1 18.03 11 8.3 0.14 905 0.62 0.36

i "dry" 25 .85 .32 .38

i 2 25 5 .71 1

i "dry" 27 .74 .62 .68

i 2 27 6 .11 1

i "dry" 32.3 .42 .32 .38

i 2 32.3 14 .005  1


i 1 36 13 9.9 0.233 333 0.23 0.63
i 1 39 12 8.9 0.323 403 0.34 0.53
i 1 42 10 7.8 0.123 283 0.42 0.73

i 1 48.01 9 8.11 0.122 108 0.13 0.54
i 1 48.03 8 8.82 0.135 208 0.50 0.44
i 1 48.05 7 8.23 0.158 748 0.40 0.24
i 1 48.08 11 8.35 0.147 908 0.60 0.34

e 60 ; score extended to allow for reverb and multitap tails to ring out

; keeping instr 100 and instr 101 "turned on" for 60 seconds

</CsScore>


</CsoundSynthesizer>
```

**Comment by csounder** [comment]
Excellent.  Thanks.

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music
