### ISSUE TITLE
rifft?

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#24]
Not a biggie, but why does "rifft" show up in the manual between "inz" and "JackoAudioIn"?

**Comment by jpffitch** [comment]
Look OK to me

**Comment by tjingboem** [comment]
![schermafdruk van 2015-03-24 08 59 33](https://cloud.githubusercontent.com/assets/6670911/6797595/2e5499f4-d204-11e4-9260-15732aa11011.png)

**Comment by jpffitch** [comment]
it seems as if te ame it is undexed ubder is irfft not rifft
