### ISSUE TITLE
sensekey 2nd example uses FLTK

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#304]
-

**Comment by AsterixMusic** [comment]
```csd

<CsoundSynthesizer>
<CsOptions>


; Select audio/midi flags here according to platform
-odac -d   ;;;realtime audio out
;-iadc    ;;;uncomment -iadc if realtime audio input is needed too
; For Non-realtime ouput leave only the line below:

; By Stefano Cucchi - 2020


</CsOptions>
<CsInstruments>

; Initialize the global variables.
sr = 44100
ksmps = 32
nchnls = 2
0dbfs = 1


instr 1
; Instr 1 trigger instr 2: every time you press any key, instr 2 produce a note.
; the pitch of the tone produced by instr 2 is equal to the ASCII code of the key pressed.

gkNumber, gkPress sensekey 
 
  if changed(gkPress) == 1 then
        if (gkPress == 1) then
            event "i", 2, 0, 0.3
       endif 
       endif
        
endin

instr 2
  
iCps init i(gkNumber)
print iCps

asig oscili 0.2, iCps, 1 
kenvelope linseg 0, 0.1, 1, 0.1, 1, 0.1, 0

outs asig*kenvelope, asig*kenvelope
endin

</CsInstruments>f
<CsScore>

f 1 0 4096 10 1 1 0.3 0 0.2 0.3 0.5

i 1 0 2000

</CsScore>
</CsoundSynthesizer>

```

**Comment by csounder** [comment]
Stefano,

great.  and fun,


*Dr. Richard Boulanger*

*Professor of Electronic Production and Design*

*Berklee College of Music*

Professional Writing and Technology Division




*skype*: radiobaton

*facebook*: https://www.facebook.com/richard.boulanger.58

*about*: http://www.boulangerlabs.com/#about

*about*: http://www.csounds.com/community/developers/dr-richard-boulanger/

*music*:
http://www.csounds.com/community/developers/dr-richard-boulanger/dr-richard-boulanger-music/

*Boulanger Labs* - http://boulangerlabs.com

*The Csound Book* - http://mitpress.mit.edu/books/csound-book

*The Audio Programming Book* -
http://mitpress.mit.edu/books/audio-programming-book
