### ISSUE TITLE
no scanhammer example

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#307]
and why is scanhammer 1 of the Scanned Synhtesis opcodes?

**Comment by tjingboem** [comment]
in 4_20.Notes i read: 
scantable, scanhammerb -- alternative and simpler implementations of
scanned synthesis

**Comment by csounder** [comment]
Yes they are.  Scantable uses a circular string matrix, is quite stable,
and does not require so many parameters and function tables - but it is
less versatile.  Still it is very beautiful.  It is a bit more in line with
Max Mathews' simple model of scanned synthesis as a 'string'

*- dB*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division

**Comment by csounder** [comment]
I don't know much about scanhammerb - will explore more and all later in
the week.

*- dB*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division

**Comment by tjingboem** [comment]
my guess is that scanhammerb has become scanhammer...
Another guess is, since scantable and scanhammer(b) are such good friends, and created both by Matt Gilliard, 
that they are meant to be used in one example??
And indeed, scanhammer does work, it amplifies a tables' content.

But i do not know when scanhammer could be useful, since one could simply modify the table itself instead of multiplying the table later. Seems redundant but possible something escapes me...

Just to test it, i varied the matrix here, but it is meant for 'This opcode can be used to “hit” a string in the scanned synthesis code.'

```
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac --limiter=0.9 ;;;realtime audio out
;-iadc    ;;;uncomment -iadc if realtime audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o scantable.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1

; by Menno Knevel 2021

instr 1	

initial ftgen 1, 0, p5, 10, 1                         ; initial position = sine wave
imass   ftgen 2, 0, p5, -7, .1, p5, 1                 ; masses
imatrx  ftgen 3, 0, p5, -7, 0, p5*.3, 100*p5, p5*.7, 0   ; matrix
idamp   ftgen 4, 0, p5, -7, 1, p5, 1                  ; damping
ivelo   ftgen 5, 0, p5, -7, 0, p5, 0.5                ; initial velocity

iamp = .05
ipch  = cpsmidinn(p4) 
asigR scantable iamp, ipch, 1, 2, imatrx, 4, 5
scanhammer 3, 3, 0, p6
asigL scantable iamp, ipch, 1, 2, 3, 4, 5
asigL   butlp  asigL, 3500
asigR   butlp  asigR, 3500
asigL dcblock asigL
asigR dcblock asigR
outs asigL, asigR

endin

</CsInstruments>
<CsScore>

i1	0	20	50  128 2
i1	10	10	70  .   1
i1	15	3	40  .   .1

e
</CsScore>
</CsoundSynthesizer>
```

**Comment by tjingboem** [comment]
This one actually makes sense.
The sine wave now has 3 different amplitudes for the same note. And you do get, not only some amplitude effect, but also the timbre changes when hit not so hard. mmmmm
```

<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac --limiter=0.9 ;;;realtime audio out
;-iadc    ;;;uncomment -iadc if realtime audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o scantable.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1

; by Menno Knevel 2021

instr 1	

initial ftgen 1, 0, p5, 10, 1                         ; initial position = sine wave
imass   ftgen 2, 0, p5, -7, .1, p5, 1                 ; masses
imatrx  ftgen 3, 0, p5, -7, 0, p5*.3, 100*p5, p5*.7, 0   ; matrix
idamp   ftgen 4, 0, p5, -7, 1, p5, 1                  ; damping
ivelo   ftgen 5, 0, p5, -7, 0, p5, 0.5                ; initial velocity

iamp = .15
ipch  = cpsmidinn(p4) 
scanhammer 1, 1, 0, p6
asig scantable iamp, ipch, 1, 2, 3, 4, 5
asig   butlp  asig, 3500
asig dcblock asig
outs asig, asig

endin

</CsInstruments>
<CsScore>

i1	0	10	50  128 2 
i1	11	10	50  .   1
i1	22	10	50  .   .1

e
</CsScore>
</CsoundSynthesizer>
```

**Comment by csounder** [comment]
As I understand it, Matt was a student of John ffitch and this was his
thesis work - it is very nice and yes, I would presume that the two are
related - it might be that the (b) version reads binary matrix files to
design or change the default hammer/displacement 'shape' (and
possibly 'size so that only a certain portion of the entire surface is
displaced - not end to end)

in your example - the comments might be clearer is they were initial
displacement
and to think of velocity as the depth of the displacement of the surface -
john explained to me how, internally - velocity is calculated as a
combination of acceleration, mass, stiffness, etc... you might ask him to
explain in detail.  like a MIDI event, one might think of it a velocity,
but it is 'not' really velocity at all.

-R


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division

**Comment by tjingboem** [comment]
indeed, the wording should be cleverly chosen. 
This last example is the first example for scanhammer that makes sense: when you hit harder, the more movements and waves in the timbre, while a gentle strokes will not only be much less loud but also modulating less...it sounds very physical this way.

I will talk with John on the wording etc., but i'll wait until 6.16 is released.

**Comment by tjingboem** [comment]
first proposal for scanhammer
...not sure about how to see the table seize...possibly scantable example has to be adjusted...

```
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac --limiter=0.9 ;;;realtime audio out and limiter
;-iadc    ;;;uncomment -iadc if realtime audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o scanhammer.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1

; by Menno Knevel 2021

instr 1	

initial ftgen 1, 0, p5, 10, 1                         ; initial position = sine wave
imass   ftgen 2, 0, p5, -7, .1, p5, 1                 ; masses
imatrx  ftgen 3, 0, p5, -7, 0, p5*.3, 100*p5, p5*.7, 0   ; matrix
idamp   ftgen 4, 0, p5, -7, 1, p5, 1                  ; damping
ivelo   ftgen 5, 0, p5, -7, 0, p5, 0.5                ; initial velocity

iamp = .35
ipch  = cpsmidinn(p4) 
scanhammer 1, 1, 0, p6                                ;
asig scantable iamp, ipch, 1, 2, 3, 4, 5
asig   butlp  asig, 3000                              ; lowpass filter
asig dcblock asig
outs asig, asig

endin

</CsInstruments>
<CsScore>
s   ;       note    seize
i1	0	10	50      128     2   ; hit very hard
i1	11	10	50      .       1   ; hit normally
i1	22	10	50      .       .3  ; hit soft
s
i1	1	10	50      32      2   ; different table seize 
i1	12	10	50      .       1
i1	23	20	50      .       .3
e
</CsScore>
</CsoundSynthesizer>
```

**Comment by tjingboem** [comment]
second proposal
Now the masses stay in proportion (0.8*p5)
and it uses foscil to hit

```
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac --limiter=0.9 ;;;realtime audio out and limiter
;-iadc    ;;;uncomment -iadc if realtime audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o scanhammer.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1

; by Menno Knevel 2021

instr 1	

initial ftgen 1, 0, p5, 10, 1                         ; initial position = sine wave
imass   ftgen 2, 0, p5, -7, .1, p5, 1                 ; masses
imatrx  ftgen 3, 0, p5, -7, 0, p5*.3, 0.8*p5, p5*.7, 0   ; matrix
idamp   ftgen 4, 0, p5, -7, 1, p5, 1                  ; damping
ivelo   ftgen 5, 0, p5, -7, 0, p5, 0.5                ; initial velocity

iamp = .20
ipch  = cpsmidinn(p4) 
scanhammer 1, 1, 0, p6                                ; scale initial position wave 
asig3 scantable iamp, ipch, 1, 2, 3, 4, 5             ; set ftables in motion
asig    foscili iamp, ipch, 1.414, .03, 1, 1          ; but use FM sound with slow vibrato
asig   butlp  asig, 2000                              ; lowpass filter
asig dcblock asig
outs asig, asig

endin

</CsInstruments>
<CsScore>
s   ;       note    seize
i1	0	10	50      128     2   ; hit very hard
i1	11	10	50      .       1   ; hit normally
i1	22	10	50      .       .3  ; hit soft
s
i1	1	10	50      32      2   ; different table seize 
i1	12	10	50      .       1
i1	23	20	50      .       .3
e
</CsScore>
</CsoundSynthesizer>
```

**Comment by tjingboem** [comment]
last example is committed

**Comment by csounder** [comment]
nice.  note - spelling in comment - 'different table seize' should be 'size'

*-R*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division
