### ISSUE TITLE
pvstencil example incomplete

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#320]
-

**Comment by tjingboem** [comment]
firts attempt, using fox.pvx from examples

```
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac      ;;;realtime audio out
;-iadc    ;;;uncomment -iadc if realtime audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o pvstencil.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

; by Menno Knevel 2021

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1

instr 1 ; clean signal, includes reverb

asig    diskin2   "finneganswake1.flac", 1
outs    asig, asig

endin

instr 2 ; reverb is masked by fox.pvx
asig    diskin2   "finneganswake1.flac", 1  
fsig    pvsanal   asig, 1024, 256, 1024, 1
fclean  pvstencil fsig, 0, 1, 1
aclean  pvsynth   fclean
outs aclean, aclean
endin

</CsInstruments>
<CsScore>

f1 0 -1024 -43 "fox.pvx" 0  ; can be found in examples folder
; if it does not run, you have to create the .pvx first on your system

i 1 0 5
i 2 5 5

e
</CsScore>
</CsoundSynthesizer>
```

related to no example GEN 43 #231

**Comment by tjingboem** [comment]
i am having fun in suppressing  some reverb and noise present in finneganswake1.flac.

Following may be part of the manual page:
![reverbnoise](https://user-images.githubusercontent.com/6670911/118308858-c082a100-b4ec-11eb-972e-b6d94e61e37e.png)
- finding the selection and duration of the reverb and noise to remove from the flac file using Audacity
- using Csound utility _pvanal_ to analyze this selection and writing  the result to a pvx file: menno@mennoASUSZ170 ~ $ pvanal -b1.04 -d0.8  finneganswake1.flac reverbnoise.pvx 
 analysing 35280 sample frames (0.8 secs) from timepoint 1.0
 frameSize=1024
1024 infrsize, 256 infrInc
....
164 1-chan blocks written to reverbnoise.pvx
- the example itself will be
```
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac      ;;;realtime audio out
;-iadc    ;;;uncomment -iadc if realtime audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o pvstencil.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

; by Menno Knevel 2021

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1

instr 1 ; clean signal, includes reverb and noise

asig    diskin2   "finneganswake1.flac", 1
outs    asig, asig

endin

instr 2 ; reverb is masked by fox.pvx
asig    diskin2   "finneganswake1.flac", 1  
fsig    pvsanal   asig, 1024, 256, 1024, 1
fclean  pvstencil fsig, 0, 1, 1 ; maximum cleaning
aclean  pvsynth   fclean
outs aclean, aclean
endin

</CsInstruments>
<CsScore>

f1 0 -1024 -43 "reverbnoise.pvx" 0  ; can be found in examples folder
; if it does not run, you have to create the .pvx first on your system

i 1 0 12.7
i 2 15 12.7

e
</CsScore>
</CsoundSynthesizer>
```

But i have a question about the length of the table.
How can i get to know the table size of the pvx file?  Right now i use f1 0 -1024 -43 "reverbnoise.pvx" 0,
but what is the formula?

**Comment by tjingboem** [comment]
```
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac     ;;;realtime audio out
-iadc    ;;;uncomment -iadc if real audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o pvstencil2.wav -W ;;; for file output any platform
; By Stefano Cucchi - 2021
</CsOptions>
<CsInstruments>
sr     = 44100
ksmps  = 10
nchnls = 2
0dbfs  = 1
instr 1
fsource  pvsdiskin “fox.pvx”, 1, 0.2
kgain1 randomh p4, p5, p6
fstencil1  pvstencil fsource, kgain1, 1, 1
aout1  pvsynth   fstencil1
kgain2 randomh p7, p8, p9
fstencil2  pvstencil fsource, kgain2, 1, 1
aout2 pvsynth   fstencil2
outch 1,   aout1*0.2
outch 2,   aout2*0.2
endin
</CsInstruments>
<CsScore>
f1 0 513 -7 0 128 0.01 256 0 128 0.9
i1 0 10 4 70 4.2 12 95 3.8
e
</CsScore>
</CsoundSynthesizer>
```

**Comment by tjingboem** [comment]
last example is uploaded, so - done

**Comment by csounder** [comment]
nice - dirty masking and stenciling - nice. but is the removing the reverb
example in there too?
- it would be nice to show this technique somewhere

*- dB*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division

**Comment by csounder** [comment]
I do like the idea of this example, and hope you find a place for it.  I am
not sure that reverbnoise.pvx is in the examples folder?

*- dB*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division

**Comment by csounder** [comment]
it might even be more vivid and obvious, if you chose a source that did
have a bit 'more' reverb in it so that the removal, which you show users
how to do with the figures in the manpage, is even more obvious.  I think
it could inspire creative and practical use for many.

*- dB*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division

**Comment by tjingboem** [comment]
- The example for pvstencil that 'made it' in the manual is not about removing noise and reverb. That example can be found on https://csound.com/manual/GEN43.html
When i added the example for GEN43, i also added  reverbnoise.pvx to the examples folder. 

- Yes, a link could be added to the manual page of pvstencil, pointing to GEN43 and another example of pvstencil. Will do so soon!

- i think you are referring to the example for GEN43 when you talk about _'if you chose a source that did
have a bit 'more' reverb in it so that the removal, which you show users
how to do with the figures in the manpage, is even more obvious._' Am i right?

Reason why, at the time,  i did not add a new,  more 'reverby' sample in the examples folder is that i try hard to minimize the already quite heavy download of the manual. 

I added your remark to the Wiki page: https://github.com/csound/manual/wiki/Samples-in-the-manual
and is now part of replace bad and add good samples #537
We have yet to talk about all this in the Csound Manual Team :)
