### ISSUE TITLE
pset small example error

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#327]
text not correct: 
f 0 60	; runs 69 seconds

**Comment by jpffitch** [comment]
Is this fixed?  I could not identify the location

**Comment by tjingboem** [comment]
no it is not fixed yet.
It concerns a typo in the score from the second example:
![Screenshot from 2020-09-26 16-47-50](https://user-images.githubusercontent.com/6670911/94343389-2b43a280-0018-11eb-9b7c-13c2dae56c08.png)

Can you fix it?

**Comment by jpffitch** [comment]
Fixed in git
