### ISSUE TITLE
product: syntax small error

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#328]
kres/iresproduct karr[]/iarr[]  (k- or i-arrays )
must be
kres/ires product karr[]/iarr[]  (k- or i-arrays )

**Comment by jpffitch** [comment]
Is this fixed?  I could not find where it is

**Comment by tjingboem** [comment]
No it is not:
![Screenshot from 2020-09-26 16-50-31](https://user-images.githubusercontent.com/6670911/94343438-7e1d5a00-0018-11eb-9733-9972a1ae8860.png)

There are 2 product manual entries, one for multiplying a-rate signals and the second one calculates the product of an array.
The typo is in the second one.

Can you please fix this?

**Comment by jpffitch** [comment]
fixed in git
