### ISSUE TITLE
bmscan?

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#33]
grep "bmscan" *.html reveals that there still about 20 references to the opcode bmscan.
Is it save to eliminate all these references?

**Comment by jpffitch** [comment]
bmscan is one of a number of opcodes for which the source was never 
provided.  What is it supposed to do?

**Comment by tjingboem** [comment]
regarding Csound, it was before my time 
but i found a csd here:
http://csounds.com/maldonado/OrcSco/Bitmap/Bmscan.csd 
and a refernce here:
http://www.csounds.com/maldonado/Manual/WidgetOpcodes.html

it think it does the same as the image opcodes we have at present?

**Comment by tjingboem** [comment]
in http://field4.co.uk/portfolio/project/report/final%20report.pdf i read that bmscan is designed "to
extract data from the image in real-time"

Also: https://groups.yahoo.com/neo/groups/csound--maths.ex.ac.uk/conversations/topics/29653?o=1&d=-1&var=1&p=1
it says: 
"There is a family of opcodes that allow to take RGB
images as input for generating control signals: bmopen, bmtable,
bmtablei, bmoscil, bmoscili, rgb2hsvl, rgb2hsvl_i, bmscan, bmscani

in :https://github.com/kroger/csound-instruments/tree/master/maldonado
 there is another example.

so bmscan stands for bitmapscan

**Comment by jpffitch** [comment]
As we never hd the sources I think all reference to this opcode should be 
removed and other such operations.
==John

**Comment by gogins** [comment]
I agree particularly as the image opcodes exist.

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by jpffitch** [comment]
I have removed all references
