### ISSUE TITLE
GEN23 documentation doesn't accurately describe the format the routine requires

### ISSUE THREAD

**Issue by mskala** [csound/manual#34]
See https://github.com/csound/csound/issues/455 .  GEN23 goes into an infinite loop on some inputs, and does not behave as documented on others.  The code will probably have to change, and I'm not sure exactly what format it _should_ read, but at such time as that is sorted out, the documentation should also be updated to accurately reflect what the code does.

**Comment by jpffitch** [comment]
Manual adapted.  Comma works as wanted, but non-number haracters arenot comments
