### ISSUE TITLE
no nchnls_hw example

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#358]
-

**Comment by tjingboem** [comment]
got error
WARNING: number of hardware input channels not currently available
INIT ERROR in instr 1 (opcode prints.i) line 24: null string

 from file /media/menno/datae/onderzoek/manualExamples/hw.csd.csd (1)
	prints.i	idacc	
INIT ERROR in instr 1 (opcode prints.i) line 25: null string

 from file /media/menno/datae/onderzoek/manualExamples/hw.csd.csd (1)
	prints.i	iadcc	
	  B  0.000 - note deleted.  i1 had 2 init errors
Score finished in csoundPerform().

```
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac --limiter=0.9 ;;;realtime audio out and limiter
;-iadc    ;;;uncomment -iadc if realtime audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o scanhammer.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1


instr 1 
idacc,iadcc nchnls_hw
prints      idacc
prints      iadcc

endin

</CsInstruments>
<CsScore>
i1 0 1

e
</CsScore>
</CsoundSynthesizer>
```

**Comment by jpffitch** [comment]
Using prints lks odd as idacc/iadcc ae integers

**Comment by tjingboem** [comment]
Yes, that is absolutely odd. 
Using just print works so much better :-)
instr 1:  idacc = 32.000
instr 1:  iadcc = 32.000

Thanks

**Comment by tjingboem** [comment]
and i still have to make an example...

**Comment by tjingboem** [comment]
example above more or less is added
