### ISSUE TITLE
lpslot example incomplete

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#372]
-

**Comment by tjingboem** [comment]
first attempt- but get sementation fault??

```
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac --limiter=0.9 ;;;realtime audio out and limiter
;-iadc    ;;;uncomment -iadc if realtime audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o scanhammer.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1

; by Menno Knevel 2021

ires1 system_i 1,{{ lpanal -a -p40 -h200 -P50  -Q5000 -v1 fox.wav fox1.lpc }}
ires2 system_i 1,{{ lpanal -a -p40 -h200 -P150  -Q2000 -v1 flute-C-octave0.wav beats.lpc }}

instr 1 ; works only with poles files.

isine  ftgen 1, 0, 1024, 10, 1      ; sine wave
ipower init .5                      ; Define sound generator
ifreq  init 440 
asrc   buzz ipower, ifreq, 10, 1
  
ktime  line 0, p3, p3               ; from start to end
       lpslot 0                     ; Read data poles
krmsr, krmso, kerr, kcps lpread ktime,"fox1.lpc"                     
       lpslot 1                     ; Read data poles
krmsr, krmso, kerr, kcps lpread ktime,"beats.lpc"
kmix   line 0, p3, 1                ; mixing the 2 lpc files
       lpinterp 0, 1, kmix          ; and balance power
ares   lpreson asrc
aout   balance ares, asrc
       outs aout, aout

endin

</CsInstruments>
<CsScore>
s 
i1	0	3	

e
</CsScore>
</CsoundSynthesizer>
```

util lpanal:
Reading sound from fox.wav, writing lpfile to fox1.lpc
poles=40 hopsize=200 begin= 0.0 duration= 0.0
lpheader comment:

pch track range:  50.0 - 5000.0 Hz
Using pole storage method
audio sr = 44100, monaural
opening WAV infile /media/menno/datae/csounddata/Samples/fox.wav
analysing 121569 sample frames (2.8 secs)
607 lpc frames written to fox1.lpc
end of score.		   overall amps:      0.0
	   overall samples out of range:        0
0 errors in performance
Elapsed time at end of performance: real: 0.699s, CPU: 0.697s
0dBFS level = 32768.0
--Csound version 6.16 (double samples) Jun  6 2021
[commit: none]
libsndfile-1.0.28
util lpanal:
Reading sound from flute-C-octave0.wav, writing lpfile to beats.lpc
poles=40 hopsize=200 begin= 0.0 duration= 0.0
lpheader comment:

pch track range: 150.0 - 2000.0 Hz
Using pole storage method
audio sr = 44100, monaural
opening WAV infile /media/menno/datae/csounddata/Samples/flute-C-octave0.wav
analysing 101000 sample frames (2.3 secs)
504 lpc frames written to beats.lpc
end of score.		   overall amps:      0.0
	   overall samples out of range:        0
0 errors in performance
Elapsed time at end of performance: real: 0.587s, CPU: 0.579s
orch now loaded
audio buffered in 256 sample-frame blocks
ALSA output: total buffer size: 1024, period size: 256
writing 512 sample blks of 64-bit floats to dac
SECTION 1:
new alloc for instr 1:
ftable 1:
ftable 1:	1024 points, scalemax 1.000

file fox1.lpc (407944 bytes) loaded into memory
WARNING: Using pole type of file.

file beats.lpc (338728 bytes) loaded into memory
WARNING: Using pole type of file.


csound command: Segmentation fault

**Comment by tjingboem** [comment]
no more segmentation fault (repaired) but not quite convinced about the sounding result of lpslot:

```
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac --limiter=0.9 ;;;realtime audio out and limiter
;-iadc    ;;;uncomment -iadc if realtime audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o scanhammer.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1

; by Menno Knevel 2021

ires1 system_i 1,{{ lpanal -a -p40 -h200 -P50  -Q5000 -v1 fox.wav fox.lpc }}
ires2 system_i 1,{{ lpanal -a -p40 -h200 -P150  -Q2000 -v1 stereoJungle.wav stereoJungle.wav.lpc }}

instr 1 ; works only with poles files.

isine  ftgen 1, 0, 1024, 10, 1     ; sine wave
asrc   buzz .5, 440, 10, 1
  
ktime  line 0, p3, p3              ; from start to end for fox.wav
       lpslot 0                    ; Read data poles
krmsr, krmso, kerr, kcps lpread ktime,"fox.lpc"                     
       lpslot 1                    ; Read data poles
krmsr, krmso, kerr, kcps lpread ktime,"stereoJungle.wav.lpc"
kmix   line 0, p3, 1               ; mixing the 2 lpc files
       lpinterp 0, 1, kmix         ; and balance power
ares   lpreson asrc
aout   balance ares, asrc
       outs aout, aout

endin

</CsInstruments>
<CsScore>
s 
i1 0 2.8	
i1 5 8        ; last frame freezes until note end

e
</CsScore>
</CsoundSynthesizer>
```

**Comment by csounder** [comment]
I am still getting a segmentation fault on the Mac

*- dB*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division

**Comment by csounder** [comment]
Note also, in the comments at the top for this example you suggest naming
the output file scanhammer and it has nothing to do with scanned

; For Non-realtime ouput leave only the line below:
; -o scanhammer.wav -W ;;; for file output any platform

*- dB*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division

**Comment by csounder** [comment]
False Alarm - I just 'brewed' the latest Csound and I am no longer getting
segfaults.

*- R*

**Comment by tjingboem** [comment]
lpslot now has the 'modern' example (system_i)
but might get a better sample later.
For now, this is done

**Comment by csounder** [comment]
very good for now.

*- dB*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division
