### ISSUE TITLE
no loop_ge example

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#376]
-

**Comment by AsterixMusic** [comment]
```csd 

<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac     ;;;realtime audio out
;-iadc    ;;;uncomment -iadc if RT audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o loop_ge.wav -W ;;; for file output any platform

; By Stefano Cucchi - 2020

</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1

instr 1 

ininstr = p5 ;number of called instances (number of sub-harmonics)
indx = p5 ; start from 1

loop:
ifreq = p4/(indx) 
iamp  = 1/ininstr
event_i "i", 10, 0, p3, iamp, ifreq
loop_ge indx, 1, 1, loop

endin


instr 10

asig  oscili p4, p5
kdeclick linseg 0, 0.1, 1, p3-0.2, 1, 0.1, 0
outs asig*kdeclick, asig*kdeclick

endin

</CsInstruments>
<CsScore>

i1 0 2 1200 10 ; This note play a tone of 1200 Hz + 9 subharmonics (1200/2, 1200/3, etc...)
e
</CsScore>
</CsoundSynthesizer>
```

**Comment by csounder** [comment]
having a little fun with it.

<CsoundSynthesizer>

<CsOptions>

; Select audio/midi flags here according to platform

-odac ;;;realtime audio out

;-iadc ;;;uncomment -iadc if RT audio input is needed too

; For Non-realtime ouput leave only the line below:

; -o loop_ge.wav -W ;;; for file output any platform


; By Stefano Cucchi - 2020


</CsOptions>

<CsInstruments>


sr = 44100

ksmps = 32

nchnls = 2

0dbfs = 1


instr 1


ininstr = p5 ;number of called instances (number of sub-harmonics)

indx = p5 ; start from 1


loop:

ifreq = p4/(indx)

iamp = 1/ininstr

event_i "i", 10, 0, p3, iamp, ifreq

loop_ge indx, 1, 1, loop


endin



instr 10


asig oscili p4, p5

kdeclick linseg 0, 0.1, .69, p3-0.2, .69, 0.1, 0

outs asig*kdeclick, asig*kdeclick


endin


</CsInstruments>

<CsScore>


t 0 50 8 120 10 10 ; slow fast slower

i1 0 2 1000 10 ; This note plays a tone of 1000 Hz + 9 subharmonics
(1200/2, 1200/3, etc...)

i1 2 2 2000 20 ; This note plays a tone of 2000 Hz + 19 subharmonics
(2000/2, 2000/3, etc...)

i1 4 2 5000 50 ; This note plays a tone of 5000 Hz + 49 subharmonics
(5000/2, 5000/3, etc...)

i1 6 2 10000 100 ; This note plays a tone of 10000 Hz + 99 subharmonics
(10000/2, 10000/3, etc...)

i1 8 1 20000 200 ; This note plays a tone of 20000 Hz + 199 subharmonics
(10000/2, 10000/3, etc...)

i1 9 1 20000 500 ; This note plays a tone of 20000 Hz + 499 subharmonics
(20000/2, 20000/3, etc...)

s

t 0 30

i1 0 3 1000 12

i1 0 2 2000 20

i1 0 1 3000 50

s

t 0 40

i1 0 1 1000 100

i1 0 2 2000 200

i1 0 3 3000 500

s

f0 1

s

t 0 50 8 30

i1 0 2 1000 20

i1 2 2 1000 2

i1 4 2 1000 40

i1 6 2 1000 4

i1 8 2 1000 80

s

t 0 30 2 20

i1 0 2 1000 8

i1 2 4 1000 180

e

</CsScore>

</CsoundSynthesizer>


*Dr. Richard Boulanger*

*Professor of Electronic Production and Design*

*Berklee College of Music*

Professional Writing and Technology Division


*skype*: radiobaton

*facebook*: https://www.facebook.com/richard.boulanger.58

*about*: http://www.boulangerlabs.com/#about

*about*: http://www.csounds.com/community/developers/dr-richard-boulanger/

*music*:
http://www.csounds.com/community/developers/dr-richard-boulanger/dr-richard-boulanger-music/

*Boulanger Labs* - http://boulangerlabs.com

*The Csound Book* - http://mitpress.mit.edu/books/csound-book

*The Audio Programming Book* -
http://mitpress.mit.edu/books/audio-programming-book

**Comment by csounder** [comment]
It would be cool - and clear - and super musical, if you could make a
version of the example that had the subharmonics added like an arpeggio.
as you notice, this is something that i was doing in brute-force - big
blocks, but having these subharmonic "waves" would be pretty awesome.

a thought

*great work!*

**Comment by AsterixMusic** [comment]
One thing I found annoying in my first version was the presence of close-together frequencies in the low register, and the fact you had to calculate the maximum index to avoid infrasonic sounds.

So I added a iMinHarm = p6 : it’s a threshold for the lowest subharmonic. When we add high number subharmonics, subharmonics that fall under this frequency are not calculated.

P.S.
Thinking about a k-rate version...

```csd

<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac     ;;;realtime audio out
;-iadc    ;;;uncomment -iadc if RT audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o loop_ge.wav -W ;;; for file output any platform

; By Stefano Cucchi - 2020

</CsOptions>
<CsInstruments>ì

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1


instr 1 ;master instrument

iMinHarm = p6 ; treshold in Hz for the lower harmonic
ininstr = p5 ;number of called instances (number of sub-harmonics)
indx = p5 

ilowSCORE = p4/p5      ; Actual lowest harmonic in Hz
indxMAX = p4/iMinHarm  ; Maximum index to avoid lower harmonic go below iMinHarm
indxMAX int indxMAX    ; Integer value of indxMAX

if  indx > indxMAX then  ; If the number of harmonics is too high we use indxMAX
    indx = indxMAX

    endif

loop:

ifreq = p4/(indx) 
print ifreq
iamp  = 1/ininstr
event_i "i", 10, 0, p3, iamp, ifreq
loop_ge indx, 1, 1, loop

endin


instr 10

asig  oscili p4, p5
asig butterhp asig, 190
kdeclick linseg 0, 0.1, 1, p3-0.2, 1, 0.1, 0
outs asig*kdeclick, asig*kdeclick

endin

</CsInstruments>
<CsScore>

t 0 50 8 120 10 10 ; slow fast slower

i1 0 2 1000 10   200; This note plays a tone of 1000 Hz + 9 subharmonics
i1 2 2 2000 20   200
i1 4 2 5000 50   200
i1 6 2 10000 100   200;
i1 8 1 20000 200  200 ; 
i1 9 1 20000 500   200; 

s

t 0 30

i1 0 3 1000 12  200
i1 0 2 2000 20  200
i1 0 1 3000 50  200

s

t 0 40

i1 0 1 1000 100  200
i1 0 2 2000 200  200
i1 0 3 3000 500  200

s

f0 1

s

t 0 50 8 30  200
i1 0 2 1000 20  200
i1 2 2 1000 2  200
i1 4 2 1000 40  200
i1 6 2 1000 4  200
i1 8 2 1000 80  200

s

t 0 30 2 20  200
i1 0 2 1000 8  200
i1 2 4 1000 180  200

e

</CsScore>
</CsoundSynthesizer>

```

**Comment by joachimheintz** [comment]
i am not sure it is worth to spend any time here.
the loop_XX opcodes were created before we had a while loop.
in my opinion, we should now encourage the while- (and in a short time: 
the for-) loop, and not these csound-specific ways from another period 
of csound.

**Comment by csounder** [comment]
Examples from floss might find their way into the manual (perhaps?)Dr. Richard BoulangerProfessorElectronic Production and DesignBerklee College of MusicOn Jun 7, 2024, at 5:13 PM, joachimheintz ***@***.***> wrote:﻿
 
 
   i am not sure it is worth to spend any time here.
   the loop_XX opcodes were created before we had a while loop.
   in my opinion, we should now encourage the while- (and in a short time: 
   the for-) loop, and not these csound-specific ways from another period 
   of csound.

**Comment by tjingboem** [comment]
thanks for the feedback, Richard, Joachim, this always helps processing my thoughts a bit more....

i think i will add (if you agree Joachim for me to use it ) the example 03C08 from the FLOSS manual. This will then function as a Group-example (like https://csound.com/manual/adsr.html ) so the user simply sees quickly in what way the different loop_ opcodes do their work.

Furthermore: as long as an opcode is not deprecated, the manual should show an example. 
On the other hand i could add a note to the loop_ opcodes stating to use the modern opcodes while and until.

**Comment by tjingboem** [comment]
```
<CsoundSynthesizer>
<CsOptions>
-odac
</CsOptions>
<CsInstruments>

  instr 1 ;loop_lt: counts from 1 upwards and checks if < 10
icount    =         1
loop:
          print     icount
          loop_lt   icount, 1, 10, loop
          prints    "Instr 1 terminated!%n"
  endin

  instr 2 ;loop_le: counts from 1 upwards and checks if <= 10
icount    =         1
loop:
          print     icount
          loop_le   icount, 1, 10, loop
          prints    "Instr 2 terminated!%n"
  endin

  instr 3 ;loop_gt: counts from 10 downwards and checks if > 0
icount    =         10
loop:
          print     icount
          loop_gt   icount, 1, 0, loop
          prints    "Instr 3 terminated!%n"
  endin

  instr 4 ;loop_ge: counts from 10 downwards and checks if >= 0
icount    =         10
loop:
          print     icount
          loop_ge   icount, 1, 0, loop
          prints    "Instr 4 terminated!%n"
  endin

</CsInstruments>
<CsScore>
i 1 0 0
i 2 0 0
i 3 0 0
i 4 0 0
</CsScore>
</CsoundSynthesizer>
;example by joachim heintz
```

**Comment by joachimheintz** [comment]
of course you are welcome to use any of the floss examples.
and yes, pointing to while/until, and for csound7 to "for", is certainly 
very helpful.
cheers -
	joachim

**Comment by csounder** [comment]
Excellent!Dr. Richard BoulangerProfessorElectronic Production and DesignBerklee College of MusicOn Jun 8, 2024, at 2:24 PM, joachimheintz ***@***.***> wrote:﻿
 
 
   of course you are welcome to use any of the floss examples.
   and yes, pointing to while/until, and for csound7 to "for", is certainly 
   very helpful.
   cheers -
   joachim

**Comment by tjingboem** [comment]
group example and note about modern while opcode is added
