### ISSUE TITLE
hvs1 FLTK example

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#414]
-

**Comment by AsterixMusic** [comment]
I changed few lines of the original example to make it works without FLTK

```csd
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
; Audio out   Audio in    No messages
-odac           -iadc     -d     ;;;RT audio I/O
</CsOptions>
<CsInstruments>

sr=44100
ksmps=100
nchnls=2
0dbfs = 1

; Original Example by Gabriel Maldonado and Andres Cabrera
; No FLTK version By Stefano Cucchi

instr 1

inumLinesX init	16
inumParms  init	3


iOutTab	ftgen	5,0,8, -2,      0
iPosTab	ftgen	6,0,32, -2,     3,2,1,0,4,5,6,7,8,9,10, 11, 15, 14, 13, 12
iSnapTab	ftgen	8,0,64, -2,     1,1,1,   2,0,0,  3,2,0,  2,2,2,  5,2,1,  2,3,4,  6,1,7,    0,0,0, \
                              1,3,5,   3,4,4,  1,5,8,  1,1,5,  4,3,2,  3,4,5,  7,6,5,    7,8,9
tb0_init	iOutTab

    
k1 linseg 0, p3, 1
printk 0.2, k1

    
;               kx,   inumParms,  inumPointsX,  iOutTab,  iPosTab,  iSnapTab  [, iConfigTab] 
        hvs1    k1,  inumParms, inumLinesX, iOutTab, iPosTab, iSnapTab  ;, iConfigTab

k0	init	0
k1	init	1
k2	init	2

printk2	tb0(k0)
printk2	tb0(k1), 10
printk2	tb0(k2), 20

aosc1 oscil tb0(k0)/20, tb0(k1)*100 + 200, 1
aosc2 oscil tb0(k1)/20, tb0(k2)*100 + 200, 1
aosc3 oscil tb0(k2)/20, tb0(k0)*100 + 200, 1
aosc4 oscil tb0(k1)/20, tb0(k0)*100 + 200, 1
aosc5 oscil tb0(k2)/20, tb0(k1)*100 + 200, 1
aosc6 oscil tb0(k0)/20, tb0(k2)*100 + 200, 1

outs (aosc1 + aosc2 + aosc3)*0.5, (aosc4 + aosc5 + aosc6)*0.5
	endin


</CsInstruments>
<CsScore>

f1 0 1024 10 1
;f0 3600
i1 0 10

</CsScore>
</CsoundSynthesizer>
```

**Comment by csounder** [comment]
nice.  thanks, Stefano.  i am especially happy to have non-FLTK (alternate
examples) in the manual.

Is the manual team aware of the fact that when running CsoundQt, on the Mac
(Catalina and Mojave) that if you select the run in the terminal tab
(button), the FLTK opcodes (widgets) do appear and do work, but if you set
the toggle in the CsoundQt settings, to run FLTK in the terminal, that the
FLTK widgets do not appear, but if you wiggle the mouse around and click
around in the blank panel, you do sometimes get lucky and grab an invisible
slider?

This suggests to me that FLTK might have more of a problem with Qt than
with the Mac.

*Dr. Richard Boulanger*

*Professor of Electronic Production and Design*

*Berklee College of Music*

Professional Writing and Technology Division


*skype*: radiobaton

*facebook*: https://www.facebook.com/richard.boulanger.58

*about*: http://www.boulangerlabs.com/#about

*about*: http://www.csounds.com/community/developers/dr-richard-boulanger/

*music*:
http://www.csounds.com/community/developers/dr-richard-boulanger/dr-richard-boulanger-music/

*Boulanger Labs* - http://boulangerlabs.com

*The Csound Book* - http://mitpress.mit.edu/books/csound-book

*The Audio Programming Book* -
http://mitpress.mit.edu/books/audio-programming-book

**Comment by tgrey1** [comment]
@csounder - Even if it appears to run, apparently there are issues with threading interrupting audio processing: https://github.com/csound/csound/issues/1325

**Comment by csounder** [comment]
Yes, you are right about that. There are still issues, but it is encouraging.

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music

**Comment by tjingboem** [comment]
Same example, but tb(0) opcodes is replaced by tab opcode, as tb(0) is deprecated


<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
; Audio out   Audio in    No messages
-odac     ;      -iadc     -d     ;;;RT audio I/O
</CsOptions>
<CsInstruments>
sr=44100
ksmps=32
nchnls=2
0dbfs = 1
; after the original FLTK example by Gabriel Maldonado and Andres Cabrera
; By Stefano Cucchi and Menno Knevel
instr 1
inumLinesX init 16
inumParms  init 3
iOutTab ftgen   5,0,8, -2,      0
iPosTab ftgen   6,0,32, -2,     3,2,1,0,4,5,6,7,8,9,10, 11, 15, 14, 13, 12
iSnapTab    ftgen   8,0,64, -2,     1,1,1,   2,0,0,  3,2,0,  2,2,2,  5,2,1,  2,3,4,  6,1,7,    0,0,0, \
                              1,3,5,   3,4,4,  1,5,8,  1,1,5,  4,3,2,  3,4,5,  7,6,5,    7,8,9
k1 linseg 0, p3, 1
printk 0.2, k1
;               kx,   inumParms,  inumPointsX,  iOutTab,  iPosTab,  iSnapTab  [, iConfigTab]
        hvs1    k1,  inumParms, inumLinesX, iOutTab, iPosTab, iSnapTab  ;, iConfigTab
k0  tab     0, 5
k1  tab     1, 5
k2  tab     2, 5
printk2 k0
printk2 k1, 10
printk2 k2, 20
aosc1 oscil k0/20, k1*100 + 200, 1
aosc2 oscil k1/20, k2*100 + 200, 1
aosc3 oscil k2/20, k0*100 + 200, 1
aosc4 oscil k1/20, k0*100 + 200, 1
aosc5 oscil k2/20, k1*100 + 200, 1
aosc6 oscil k0/20, k2*100 + 200, 1
outs (aosc1 + aosc2 + aosc3)*0.7, (aosc4 + aosc5 + aosc6)*0.7
    endin
</CsInstruments>
<CsScore>
f1 0 1024 10 1
i1 0 10
</CsScore>
</CsoundSynthesizer>

**Comment by tjingboem** [comment]
Same example, but tb(0) opcodes is replaced by tab opcode, as tb(0) is deprecated

```
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
; Audio out   Audio in    No messages
-odac     ;      -iadc     -d     ;;;RT audio I/O
</CsOptions>
<CsInstruments>

sr=44100
ksmps=32
nchnls=2
0dbfs = 1

; after the original FLTK example by Gabriel Maldonado and Andres Cabrera
; By Stefano Cucchi and Menno Knevel

instr 1
inumLinesX init 16
inumParms  init 3
iOutTab ftgen   5,0,8, -2,      0
iPosTab ftgen   6,0,32, -2,     3,2,1,0,4,5,6,7,8,9,10, 11, 15, 14, 13, 12
iSnapTab    ftgen   8,0,64, -2,     1,1,1,   2,0,0,  3,2,0,  2,2,2,  5,2,1,  2,3,4,  6,1,7,    0,0,0, \
                              1,3,5,   3,4,4,  1,5,8,  1,1,5,  4,3,2,  3,4,5,  7,6,5,    7,8,9
k1 linseg 0, p3, 1
printk 0.2, k1
;               kx,   inumParms,  inumPointsX,  iOutTab,  iPosTab,  iSnapTab  [, iConfigTab]
        hvs1    k1,  inumParms, inumLinesX, iOutTab, iPosTab, iSnapTab  ;, iConfigTab

k0  tab     0, 5
k1  tab     1, 5
k2  tab     2, 5

printk2 k0
printk2 k1, 10
printk2 k2, 20

aosc1 oscil k0/20, k1*100 + 200, 1
aosc2 oscil k1/20, k2*100 + 200, 1
aosc3 oscil k2/20, k0*100 + 200, 1
aosc4 oscil k1/20, k0*100 + 200, 1
aosc5 oscil k2/20, k1*100 + 200, 1
aosc6 oscil k0/20, k2*100 + 200, 1
outs (aosc1 + aosc2 + aosc3)*0.7, (aosc4 + aosc5 + aosc6)*0.7

    endin
</CsInstruments>
<CsScore>
f1 0 1024 10 1
i1 0 10
</CsScore>
</CsoundSynthesizer>
```
