### ISSUE TITLE
no getseed example

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#415]
-

**Comment by AsterixMusic** [comment]
@tjingboem 

```csd

<CsoundSynthesizer>
<CsOptions>
-odac -d
; By Stefano Cucchi - 2021
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs = 1

instr 1

seed p4
kseed getseed

printk2 kseed

endin


</CsInstruments>
<CsScore>

i1 0 0.1 0
i1 0.5 0.1 3 

e
</CsScore>
</CsoundSynthesizer>
```

**Comment by tjingboem** [comment]
not a correct example yet, don't know why yet

<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac     ;;;realtime audio out
;-iadc    ;;;uncomment -iadc if RT audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o getseed.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1

instr 1	;different values every time - value is derived from system clock

seed 0					; seed from system clock
kseed   getseed

krnd randomh 100, 200, 5		
     printk2  krnd		
if kseed < 150 then 
    aout poscil 0.8, 440+krnd		; & listen
else
    aout vco2   0.3, 440+krnd
endif
     outs aout, aout

endin
</CsInstruments>
<CsScore>

i1 0 3
e
</CsScore>
</CsoundSynthesizer>

**Comment by tjingboem** [comment]
check https://github.com/csound/csound/issues/1499
for basic information on the example

**Comment by tjingboem** [comment]
something like this:

```
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac     ;;;realtime audio out
;-iadc    ;;;uncomment -iadc if RT audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o getseed.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1

; by Menno Knevel - 2021

seed 0  ; seed from system clock

instr 1	; different values every time - value is derived from system clock

krnd randomh 100, 400, 1		
     printks2    "different values every time Value = %d\n ",  krnd	
aout poscil 0.8, 440+krnd
     outs aout, aout
endin

instr 2	; same values every time - captured by getseed

gised getseed
seed gised
print gised
krnd randomh 100, 400, 1		
     printks2    "get seed value from time clock. Value = %d\n ",  krnd	
aout poscil 0.8, 440+krnd
     outs aout, aout
endin

instr 3	; same values every time - captured by getseed

print gised
seed gised
krnd randomh 100, 400, 1		
     printks2    "reuses seed value of instr 2. Value = %d\n ",  krnd	
aout poscil 0.8, 440+krnd
     outs aout, aout
endin


</CsInstruments>
<CsScore>

i1 0 3  ; 2 notes showing the different
i1 5 3

i2 10 3 ; 1 note & get the seed value

i3 15 3 ; 1 note and use that seed value
e
</CsScore>
</CsoundSynthesizer>
```

**Comment by csounder** [comment]
nice. clear.  helpful.  thanks.

*- dB*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division

**Comment by tjingboem** [comment]
example committed
