### ISSUE TITLE
JackoInit

### ISSUE THREAD

**Issue by hlolli** [csound/manual#42]
In the JackoInit opcode manual it says:

Syntax 
JackoInit SclientName, ServerName 

then

SclientName -- The name of the Jack client; normally, should be "csound". 
ServerName -- The name of the Jack daemon; normally, will be "default". 

But in the example:

instr 1

JackoInit "default", "csound"
JackoInfo

endin

Not sure if the error is in the csound example (switched parameters) or if this opcode is broken as well.

For

JackoInit		"jackd", "csound"

I get

csound -b2048 -B4096 -+rtaudio=jack -odac -+jack_client=csnd-aeolus.csd --env:CSNOSTOP=yes /home/hlolli/Programs/csoundqt-0.9.0-src/bin/csnd-aeolus.csd 
virtual_keyboard real time MIDI plugin for Csound
WARNING: STK opcodes not available: define environment variable RAWWAVE_PATH
(points to rawwaves directory) to use STK opcodes.
0dBFS level = 32768.0
Csound version 6.07 (double samples) Nov 26 2015
libsndfile-1.0.25
Reading options from $HOME/.csound6rc
UnifiedCSD:  /home/hlolli/Programs/csoundqt-0.9.0-src/bin/csnd-aeolus.csd
STARTING FILE
Creating options
Creating orchestra
Creating score
rtaudio: JACK module enabled
rtmidi: ALSA Raw MIDI module enabled
WARNING: STK opcodes not available: define environment variable RAWWAVE_PATH
(points to rawwaves directory) to use STK opcodes.
instr jackin uses instrument number 2
Elapsed time at end of orchestra compile: real: 0.003s, CPU: 0.003s
sorting score ...
	... done
Elapsed time at end of score sort: real: 0.003s, CPU: 0.003s
--Csound version 6.07 (double samples) Nov 26 2015
graphics suppressed, ascii substituted
0dBFS level = 1.0
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
**Could not create Jack client "csound" -- is Jack server "jackd" running? Status: 17**
inactive allocs returned to freespace
end of score.		   overall amps:  0.00000  0.00000
	   overall samples out of range:        0        0
0 errors in performance
Elapsed time at end of performance: real: 0.007s, CPU: 0.003s

Press return to continue

(obviously jack is running on my machine)

**Comment by jpffitch** [comment]
Looking at the code the order is server, client.  But as this is C++ 
peraps someone else should check.

I think the anual is wrong

**Comment by gogins** [comment]
It is server, client. "default" in the example is the server, "csound" is
the client.

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by jpffitch** [comment]
Changed manual -- but there is still a problem;  what is the Sname argument?
