### ISSUE TITLE
manual example not working: vstinit

### ISSUE THREAD

**Issue by boulangerlabs** [csound/manual#44]
STARTING FILE
Creating options
Creating orchestra
Creating score
rtaudio: PortAudio module enabled ...
using blocking interface
error: syntax error, unexpected T_IDENT (token "vstinit") from file /Users/rboulanger/Desktop/vst4cs.csd (1)
line 14:
>>>gipianoteq vstinit <<<
Unexpected untyped word gipianoteq when expecting a variable
Parsing failed due to invalid input!
Stopping on parser failure
cannot compile orchestra

**Comment by jpffitch** [comment]
Not all buids have vst opcodes -- licences etc
