### ISSUE TITLE
should opcode 'changed' be moved over to Deprecated Section?

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#448]
-

**Comment by jpffitch** [comment]
What should be moved?  Sorry not to understand

**Comment by tjingboem** [comment]
yes i understand the confusion, sorry.
The opcode 'changed'  is no longer an active part and is replaced by 'changed2'. So i think the manual page for 'changed' could be moved to the Deprecated Section.

**Comment by jpffitch** [comment]
I think not.  changed and changed2 are different and both have their uses.  At least I was told so when changed2 was introduced

**Comment by tjingboem** [comment]
i get this output when i use 'changed' instead of 'changed2':
..........
Creating score
rtmidi: ALSA Raw MIDI module enabled
rtaudio: JACK module enabled
opcode changed deprecated
.............

**Comment by tgrey1** [comment]
That text should be removed.  changed and changed2 have very different uses, especially in some specific corner-cases of cabbage where you might not want the init pass setting of a widget's variable to be considered a "change".

**Comment by joachimheintz** [comment]
this is my opinion, too.  'changed' shpuld not be marked as deprecated.

**Comment by jpffitch** [comment]
Will do the change to change asap

⁣Get TypeApp for Android ​

**Comment by jpffitch** [comment]
As far as I can see it was only he string form of changed that was 
deprecated.  I have remoed the tag

**Comment by tjingboem** [comment]
then it is settled. I'll close the issue.
