### ISSUE TITLE
VST opcodes

### ISSUE THREAD

**Issue by boulangerlabs** [csound/manual#46]
Victor tells me that "due to licensing issues" these opcodes are not distributed with the binary builds of Csound.  Perhaps it should be noted in the manual that one needs to build from sources to explore these opcodes - (and there might be others in the category too?)  And.  there need to be clear, step-by-step instructions in the manual for how to build from sources on each OS.

**Comment by gogins** [comment]
A Windows installer with both vst4cs and CsoundVST is available on my web
site.

Best,
Mike
