### ISSUE TITLE
change "old" SF to "other" SF

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#461]
On
https://csound.com/manual/SiggenSample.html#SiggenSampleSF
there is mention of "Old" Soundfont opcodes. (sfplay etc.)
I think that this is not a good classification; for example, oscil is older than poscil, but in the manual there is no mention of an 'old' oscil.

I propose to change the word 'old'  to 'other' .
The reason why these not-fluid opcodes are not redundant is already correctly stated in the manual:
" These opcodes can also use soundfonts to generate sound. sfplay etc. were created for one purpose -- to use the **samples** in SoundFonts. The fluid opcodes were created for another purpose -- to use SoundFonts more or less the way they were designed to be used, i.e. using keyboard mappings, layers, internal processing, etc."

**Comment by tgrey1** [comment]
I'm not at all familiar with these opcodes, but instead of _old_ or _other_, how about _original_?  This still maintains the implication of which existed first, while not potentially carrying the negative connotation of being outdated?

I'll read up a little about these and think on it, perhaps we can discuss it Sunday.

**Comment by csounder** [comment]
Like the wording "original"

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music

**Comment by tjingboem** [comment]
+1

**Comment by csounder** [comment]
Note that the wterrain2 manual example does not run
- I am not sure that the opcode exists?

**Comment by csounder** [comment]
Note that. What's new in Csound 6.15.0

appears in the online preface of the latest manual:
https://csound.com/docs/manual/PrefaceWhatsNew.html#:~:text=Release%20Notes%20for%20Csound%206.15,which%20has%20long%20been%20requested.&text=lufs%20opcode%20calculates%20a%20momentary,and%20short%2Dterm%20loudness%20meter
.

But it does not appear in the 6.15 manual that is included with CsoundQt

-dB

**Comment by jpffitch** [comment]
Changed

**Comment by tjingboem** [comment]
Thanks, John. Much better :)
