### ISSUE TITLE
move portion of text from manual page on cpumeter over to better position on that page

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#463]
At the bottom:
'New in Csound version 5.14, for Linux/Unix and OSX only'

the part: 'for Linux/Unix and OSX only'
could get better attention when put higher on the manual page as a NOTE.
Like it is done on the manual page for joystick

**Comment by jpffitch** [comment]
Words adjusted.  Are they OK?

**Comment by tgrey1** [comment]
That looks great, thanks John!

**Comment by csounder** [comment]
This is a slightly improved manual example for the cntCreate opcode

<CsoundSynthesizer>

<CsOptions>
-odac -Mhw:1,0,0
</CsOptions>

<CsInstruments>
nchnls = 2
0dbfs = 1

 gicntA cntCreate 1     ; a toggle
 gicntNoteA cntCreate 1 ; ignore note-off message - turn MIDI notes into
toggles
 gicntB cntCreate 1
 gicntNoteB cntCreate 1
 gicntC cntCreate 1
 gicntNoteC cntCreate 1

instr 1

kkey sensekey
printk2 kkey

if (kkey == 97) then  ; ASCII 'a' = 97
 k1 count gicntA
 if k1==0 then
  event "i", 2, 0, -1
 else
  event "d", 2, 0, -1
 endif
endif

if (kkey == 115) then  ; ASCII 's' = 115
 k1 count gicntB
 if k1==0 then
  event "i", 3, 0, -1
 else
  event "d", 3, 0, -1
 endif
endif

if (kkey == 100) then  ; ASCII 'd' = 100
 k1 count gicntC
 if k1==0 then
  event "i", 4, 0, -1
 else
  event "d", 4, 0, -1
 endif
endif

inote notnum
print  inote

if (inote == 60) then
 i2 count_i gicntNoteA
 print i2
 if i2==0 then
  event_i "i", 2, 0, -1
 else
  event_i "d", 2, 0, -1
 endif
endif

if (inote == 62) then
 i2 count_i gicntNoteB
 print i2
 if i2==0 then
  event_i "i", 3, 0, -1
 else
  event_i "d", 3, 0, -1
 endif
endif

if (inote == 64) then
 i2 count_i gicntNoteC
 print i2
 if i2==0 then
  event_i "i", 4, 0, -1
 else
  event_i "d", 4, 0, -1
 endif
endif

endin


instr 2
kenv linenr .25,.1,.1,.01
asig oscil kenv, 261.63
outs asig,asig
endin

instr 3
kenv linenr .25,.05,.1,.01
asig oscil kenv, 293.665
outs asig,asig
endin

instr 4
kenv linenr .25,.02,.1,.01
asig oscil kenv, 329.628
outs asig,asig
endin

</CsInstruments>

<CsScore>
i1 0 z
</CsScore>

</CsoundSynthesizer>


*Dr. Richard Boulanger*

*Professor of Electronic Production and Design*

*Berklee College of Music*

Professional Writing and Technology Division


*skype*: radiobaton

*facebook*: https://www.facebook.com/richard.boulanger.58

*about*: http://www.boulangerlabs.com/#about

*about*: http://www.csounds.com/community/developers/dr-richard-boulanger/

*music*:
http://www.csounds.com/community/developers/dr-richard-boulanger/dr-richard-boulanger-music/

*Boulanger Labs* - http://boulangerlabs.com

*The Csound Book* - http://mitpress.mit.edu/books/csound-book

*The Audio Programming Book* -
http://mitpress.mit.edu/books/audio-programming-book
