### ISSUE TITLE
What's New in Csound 6.15 - missing from Preface (in CsoundQt version of the manual)

### ISSUE THREAD

**Issue by csounder** [csound/manual#465]
Note that. What's new in Csound 6.15.0 appears in the online preface of the latest manual on the web:
https://csound.com/docs/manual/PrefaceWhatsNew.html#:~:text=Release%20Notes%20for%20Csound%206.15,which%20has%20long%20been%20requested.&text=lufs%20opcode%20calculates%20a%20momentary,and%20short%2Dterm%20loudness%20meter.

But... it does not appear in the 6.15 manual that is included with CsoundQt

-dB

**Comment by tgrey1** [comment]
We don't really have control over the docs included with QT from here, as far as I know that's all handled by the QT team when they package up a release.

I was going to refer you to their issue tracker, but it looks like you already found it! 👍 

https://github.com/CsoundQt/CsoundQt/issues/341
