### ISSUE TITLE
new link to CsoundQt

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#475]
new link on https://csound.com/manual/OviewFrontEnds.html for CsoundQt should be
https://csoundqt.github.io/

**Comment by tgrey1** [comment]
At the same time, let's update Blue and Cabbage.

For Blue: csounds.com redirects, but we can link directly to https://blue.kunstmusik.com/
  Already confirmed OK with Steven.

For Cabbage: the manual links directly to the install of an ancient version frozen in time from 2016.  It should go to the actual Cabbage home page and let Rory decide which versions to point a user towards: https://www.cabbageaudio.com/
  Will confirm with Rory on this day cycle for him ;)

**Comment by tgrey1** [comment]
I updated all of these links when testing the appveyor build process.  Couldn't find a reason it'd failed last time, so needed a simple change to test with.

Fixed with: https://github.com/csound/manual/commit/aa8fdda75749b3a5305a7672a5d316f8eb196d24
