### ISSUE TITLE
Dead link on "User defined opcode database "

### ISSUE THREAD

**Issue by johannphilippe** [csound/manual#482]
https://csound.com/docs/manual/OrchUDO.html
The "User defined opcode database" link is a non maintained website. I suggest it could be replaced with  
http://iainmccurdy.org/csound.html

**Comment by tjingboem** [comment]
The new link of this database is https://www.csounds.com/community/user-defined-opcode-database/
This now has been corrected in the manual.

Thanks for reporting!

**Comment by csounder** [comment]
nice

*- Dr.B*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division
