### ISSUE TITLE
midiarp uses FLTK

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#486]
midiarp example will be one without FLTK

**Comment by rorywalsh** [comment]
I've added a new example that use a simple MIDI file, but it won't work until a new release is made as the midiarp opcode was broken. I'll let you close this out if you are satisfied that the issue has been dealt with.

**Comment by tjingboem** [comment]
great example, thanks.
Your midiChords.mid midi file will be of use in other examples also.
