### ISSUE TITLE
platerev.csd example does not sound like a plate reverb

### ISSUE THREAD

**Issue by boulangerlabs** [csound/manual#49]
perhaps some work can be done on this .csd to give it more of a "plate" sound.  Dr.B.

**Comment by boulangerlabs** [comment]
The opcode needs to be optimized!  It is the "only" reverb opcode in Csound that will not currently run in real-time.  -dB

**Comment by jpffitch** [comment]
The algoritm is very expensive; already 50 times faster that the original.  It needs a cuda implementation rather than optimisation, but not everyone has the hardware.  It sounds like it sounds
