### ISSUE TITLE
EXPERIMENTAL: CUDA opcodes for partitioned convolution direct convolution and sliding phase vocoding;

### ISSUE THREAD

**Issue by boulangerlabs** [csound/manual#50]
Don't work without special hardware?
- can they be made to work - even in non-realtime/offline.

WARNING: could not open library '/Users/rboulanger/Desktop/CCsoundQt-d-cs6.app/Contents/MacOS/../Frameworks/CsoundLib64.framework/Resources/Opcodes64/libwiimote.dylib' (-1)
STARTING FILE
Creating options
Creating orchestra
Creating score
rtmidi: virtual_keyboard module enabled
rtaudio: PortAudio module enabled ... 
using blocking interface
error: syntax error, unexpected T_IDENT  (token "asig") from file /Library/Frameworks/CsoundLib64.framework/Resources/Manual/examples/cudasliding.csd (1)
 line 20:
>>>asig <<<
Parsing failed due to invalid input!
Stopping on parser failure
cannot compile orchestra

**Comment by vlazzarini** [comment]
The CUDA opcodes are only offered in source code at the moment as they depend on NVIDIA hardware and the CUDA library. With these in place, they can be built with cmake (with the option -DBUILD_CUDA_OPCODES=1). I have added a note to this effect in the manual pages.

NB: these opcodes are liable to change as they get further developed. This is another reason for not including them in a binary release. They will possibly offered as an add-on in the future.
