### ISSUE TITLE
pset-midi.csd has FLTK example

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#511]
replace

**Comment by tjingboem** [comment]
this new example shows better what pset is all about:

<CsoundSynthesizer> 
<CsOptions> 
; Select audio/midi flags here according to platform
-odac   ;;;realtime audio out
;-iadc    ;;;uncomment -iadc if realtime audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o pset.wav -W ;;; for file output any platform
</CsOptions> 
<CsInstruments> 

sr = 44100 
ksmps = 32 
0dbfs  = 1 
nchnls = 2 

; by Menno Knevel - 2021
;this shows an example with non-midi use
instr 1 

pset 1, 0, 1, 220, 0.05 
asig poscil p5, p4
     outs asig, asig
 
endin 

instr 2 

asig poscil p5, p4
     outs asig, asig

endin 
</CsInstruments> 
<CsScore> 
s
i 1 0 1         ; pset completes p fields 
i 1 1 1 440     ; pset completes p fields  
i 1 2 1 880 0.1 ; this note has all p fields 
s
i 2 0 1         ; no sound, incomplete p fields
i 2 1 1 440     ; no sound, incomplete p fields
i 2 2 1 880 0.1 ; this note has all p fields

e
</CsScore> 
</CsoundSynthesizer> 

pset-midi example follows soon

**Comment by tjingboem** [comment]
pset-midi example, to be reviewed

<CsoundSynthesizer> 
<CsOptions> 
; Select audio/midi flags here according to platform
-odac  	-d    -m0d --midi-key-oct=4 --midi-velocity=5   -F midiChords.mid 
;-iadc    ;;;uncomment -iadc if realtime audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o pset-midi.wav -W ;;; for file output any platform
</CsOptions> 
<CsInstruments> 

; by Menno Knevel - 2021

sr = 44100 
ksmps = 32
0dbfs  = 1 
nchnls = 2 

; takes midiChords.mid from examples folder

instr 1

            pset 1, 0, .1

istarttime  = p2
iattack     = 0.005
isustain    = p3
irelease    = 0.06
p3          = isustain + iattack + irelease

ifrequency cpsmidi
iamplitude  = p5*.2			;lower volume

print p1, p2, p3, p4, p5
asig STKBandedWG ifrequency, iamplitude
     outs asig, asig

endin
</CsInstruments>
<CsScore>
i1 0 60  ; runs for 1 minute, midifile time lasts for 35 seconds
</CsScore>
</CsoundSynthesizer>

**Comment by csounder** [comment]
nice.  clear.

*Dr. Richard Boulanger*

Professor of Electronic Production and Design

*Berklee College of Music*

Professional Writing and Technology Division

**Comment by tjingboem** [comment]
example added
