### ISSUE TITLE
veloc.csd has FLTK example

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#514]
replace

**Comment by tjingboem** [comment]
takes midiChords.mid from examples folder and uses its velocity

<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac 	-d    -m0d --midi-key-cps=4  -F midiChords.mid
;-iadc    ;;;uncomment -iadc if realtime audio input is needed too
</CsOptions>
<CsInstruments>

; by Menno Knevel - 2021

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1

; takes midiChords.mid from examples folder

instr 1

ivel veloc 0, 1			;re-scale velocity to 0 - 1
print ivel				;print velocity
asig vco2 .1*ivel, p4   ;
     outs asig, asig
       
endin
</CsInstruments>
<CsScore>

i1 0 35     ;midi file = 35 seconds

e
</CsScore>
</CsoundSynthesizer>

**Comment by csounder** [comment]
Note:

WARNING: instr 1 uses 4 p-fields but is given 3


-dB

**Comment by tjingboem** [comment]
thanks for checking!
I don't get that report...are you running from terminal or CsoundQt?

(Kevin and Stefano, perhaps Pablo will review all new examples also. We will only commit examples when they work from the terminal on all 3 major platforms.)

**Comment by csounder** [comment]
Both - and it could not find the .mid file from both either.

**Comment by tjingboem** [comment]
right- noted. Will check again.
It uses a midifile recently uploaded by Rory to the examples folder but you can find it here: https://github.com/csound/manual/blob/master/examples/midiChords.mid
Rory uploaded it for his midiarp example.

**Comment by tjingboem** [comment]
examples added
