### ISSUE TITLE
hrtfearly example .csd - can't find the required "hrtf files" from the manual

### ISSUE THREAD

**Issue by boulangerlabs** [csound/manual#52]
Note that most examples in the manual that use samples are able to "locate" them from the manual example itself.  In this case, one needs to set up paths, or environment variables, or copy the example .csd plus the needed hrtf.dat files to a folder or the desktop.  It is working great, but requires more work than most examples to get it to work.

**Comment by vlazzarini** [comment]
I have copied the files into the examples directory.
