### ISSUE TITLE
New stereo audio files for MID-SIDE processing

### ISSUE THREAD

**Issue by AsterixMusic** [csound/manual#521]
Proposal for adding 2 new audio files.
In Csound, there is not a specialzed opcode for the MidSide & stereo technique. Here is an example that shows how to encode a stereo sound to MidSide and shows how to decode a MidSide sound.
It uses the samples Stereo2MS.wav and MS2Stereo.wav

``` csd 


<CsoundSynthesizer>
<CsOptions>
-odac -d
</CsOptions>
<CsInstruments>


; By Stefano Cucchi 2021


sr = 44100
ksmps = 32
nchnls = 2
0dbfs = 1



instr 1 ; MID-SIDE decoding: from mid-side to stereo
        ; In mid-side audio you have the MID on the LEFT and the SIDE on the RIGHT

aMID, aSIDE diskin "MS2Stereo.wav"

aLEFT = aMID + aSIDE
aRIGHT = aMID + (aSIDE * -1 )

outch 1, aLEFT
outch 2, aRIGHT

endin


instr 2 ; MID_SIDE encoding from a STEREO file

aLEFT, aRIGHT diskin "Stereo2MS.wav"

aMID =  aLEFT + aRIGHT ; The MID is the MONO part of the signal
aSIDE = aLEFT - aRIGHT ; The SIDE is the difference between LEFT and RIGHT


outch 1, aMID 
outch 2, aSIDE


endin

</CsInstruments>
<CsScore>


i1 0 7
i2 8 7


</CsScore>
</CsoundSynthesizer>

```

**Comment by tjingboem** [comment]
this example and samples can be found in the examples folder, as usual.
On the page https://csound.com/manual/SigmodPanspatl.html this text could be added:

_Note: MidSide stereo
In Csound, there is not a specialzed opcode for the MidSide stereo technique. Here is an example that shows how to encode a stereo sound to MidSide and shows how to decode a MidSide sound.
It uses the samples Stereo2MS.wav and MS2Stereo.wav._

where the word 'Here'  is a link to the downloadable MS example.

**Comment by csounder** [comment]
Forgive me, but I can't seem to locate the files? 
I am excited to check out this example 

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music

**Comment by tjingboem** [comment]
discussion on the Csound manual are on the Slack manual channel.
The wavs can be downloaded there

But this all is a proposal- we are talking about wanting to have 2  _real_  midside opcodes, like bformenc1 and bformdec1

**Comment by csounder** [comment]
Thanks!  I will set things up and get into the slack discussion too.  Sorry if I am not using the best means of communicating 

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music

**Comment by tjingboem** [comment]
link to this issue: https://github.com/csound/csound/issues/1427
new opcode for MidSide processing #1427

**Comment by tjingboem** [comment]
closing this as examples and samples for MS are committed
