### ISSUE TITLE
fareylen — returns the length of a Farey Sequence. 

### ISSUE THREAD

**Issue by csounder** [csound/manual#523]
missing .csd example

**Comment by AsterixMusic** [comment]
I have found that it is not necessary to use "fareyleni" in conjunction with  "genfarey" as you can se in the example below:

```csd

<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>

sr=44100
ksmps=10
nchnls=1


instr 10

gifarn init 4
gires fareyleni gifarn  
print gires

endin

</CsInstruments>
<CsScore>

i 10 0 1

</CsScore>
</CsoundSynthesizer> 
```

but when I try "fareylen" at krate I have an error: "null iopadr"
Maybe there is something wrong in my example:

```  csd

<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>

sr=44100
ksmps=10
nchnls=1


instr 10

kfarnf randomi 1, 16, 4
kfarn ceil kfarnf
printk2 kfarn

klenght fareylen kfarn  
printk2 klenght

endin

</CsInstruments>
<CsScore>

i 10 0 3

</CsScore>
</CsoundSynthesizer> 
```

**Comment by jpffitch** [comment]
Not your fault. There is an error in the OENTRY table for fareylen.  I have fixed it here and will commit asap

⁣Sent from TypeApp ​

**Comment by tjingboem** [comment]
new try

```
<CsoundSynthesizer>
<CsOptions>
-n
</CsOptions>
<CsInstruments>

sr=44100
ksmps=32
nchnls=1


instr 10

kfarnf randomi 1, 10, 4
kfarn ceil kfarnf

klenght fareylen kfarn  
printks "farey length of %d = %d\n",.1,  kfarn, klenght

endin

</CsInstruments>
<CsScore>

i 10 0 3
e
</CsScore>
</CsoundSynthesizer> 
```

**Comment by csounder** [comment]
nice

**Comment by tjingboem** [comment]
the fareyleni manual page has a sounding example, the example of fareylen only prints values.
I'm fine with this, so this issue can be closed...

**Comment by csounder** [comment]
yes. all good.

*- Dr.B*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division
