### ISSUE TITLE
beadsynth example contains 'dangerous' wav

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#524]
the file 'fox.mtx.wav'  is not an ordinary file, as i found out when i played it.
Luckily my speakers were set to a low volume, but, for the protection of ears/speakers, can this analyse file be renamed to 'fox.mtx'?
When renaming both the analysis file in the examples folder and renaming it in the csd to 'fox.mtx', it would be more safe as then it is clearly NOT a sound file. 
I tried this and the example works just as good.

**Comment by csounder** [comment]
excellent idea.  (to be safe and clear) It is a great sounding opcode.  Is
there any way the 'required' analysis utility could be compiled and
distributed (like HETRO, PVANAL, LPANAL, ATSA) and distributed with these
as command-line utilities with the upcoming 6.16 and added to the Utilities
Page of CsoundQt?  Hope so.  If so... everyone would be using this.

-dB

*Dr. Richard Boulanger*

Professor of Electronic Production and Design

*Berklee College of Music*

Professional Writing and Technology Division

**Comment by tjingboem** [comment]
the file 'fox.mtx.wav' is used in the getrowlin.csd too

**Comment by jpffitch** [comment]
according to sndfile-info that file is a 4.646s wav mono file in IEEE 
format as 44.1kHz wih maximum amplitude 81.56dB

In the beadsynth examle .csd file he reads some values from the ftable 
loaded with fox.mxt.wav and ues then a data for he opcode.  \All very 
strange.

We need to know what this file format is, and how to create it, at the 
least.

**Comment by tjingboem** [comment]
in the example i read:
This example uses the analysis file fox.mtx.wav which was produced with
loristrck_pack, see https://github.com/gesellkammer/loristrck

**Comment by tjingboem** [comment]
fox.mtx.wav is now fox.mtx, adjusted beadsynth.csd and getrowlin.csd accordingly
