### ISSUE TITLE
mandel example does not contain use of mandel

### ISSUE THREAD

**Issue by genell** [csound/manual#525]
I just picked an opcode at random to try the web assembly playable manual, and happened to choose 'mandel'. I realized that the example does not seem to use the mandel opcode at all. 

/Anders

**Comment by tgrey1** [comment]
Nice catch, thanks for letting us know!

The link for more info near the bottom of the page is also a dead link that we should remove.

**Comment by tjingboem** [comment]
the link to the paper from Evans can be taken out, no longer valid

**Comment by AsterixMusic** [comment]
Also the link "See Also" doesn't work

**Comment by AsterixMusic** [comment]
First attempt.
We should hear a  "fractal" behavior?

```csd

<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac     ;;;realtime audio out
;-iadc    ;;;uncomment -iadc if realtime audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o mandel.wav -W ;;; for file output any platform

; By Stefano Cucchi 2021

</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 10
nchnls = 2
0dbfs  = 1

instr 1

ksig oscil 1, 4

ktrig trigger ksig, 0, 2

kx linseg p9, p3, p10 ; in the range -1 1
ky linseg p7, p3, p8 ;; in the range -1 1
kmaxIter linseg p5, p3*0.5, p6, p3*0.5, p5

kiter, koutrig mandel  ktrig, kx, ky, kmaxIter

asig foscili 0.3, 1, p4, kiter, 10, 1
outs asig, asig

endin


</CsInstruments>
<CsScore>


f 1 0 4096 10 1 1 0 1

i 1 0 10 440 110 2000 -1 1 -1 1

e
</CsScore>
</CsoundSynthesizer>


















```

**Comment by csounder** [comment]
Interesting and exciting
- time for another etude!

It would be good to have several notes showing several ranges of the curve
(essentially, several ZOOM levels)
- and several rates of the trigger to enjoy the contour more.

Any way to plot the behavior into a ftable too?
- to see the fractal shape as well as hear it.


*- dB*

**Comment by AsterixMusic** [comment]
Trying to find a useful example for "mandel" and to see/hear fractal behaviour.
Here a simple "octave" program plotting kiter (in blue) and koutrig (in red).
The values are generated and written in 2 files with the "dumpk" opcode.

OCTAVE (MATLAB) CODE:
------------------------
%by Daniele Cucchi 2021

clear

close all

figure (1)


%load textfile 
data1 = load('kiter'); 

%plot data 
plot(data1(:,1)); 

hold on

%load textfile 
data2 = load('koutrig'); 

%plot data 
plot(data2(:,1)); 

------------------------------

```csd 
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac     ;;;realtime audio out
;-iadc    ;;;uncomment -iadc if realtime audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o mandel.wav -W ;;; for file output any platform

; By Stefano Cucchi 2021

</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 10
nchnls = 2
0dbfs  = 1

instr 1

ksig oscil 1, p10

ktrig trigger ksig, 0, 2

kx linseg p8, p3, p9 ; in the range -1 1
ky linseg p6, p3, p7 ;; in the range -1 1
kmaxIter linseg p4, p3*0.5, p5, p3*0.5, p4

kiter, koutrig mandel  ktrig, kx, ky, kmaxIter
printks2 "maximum iterations =  %d\n", kiter  ; show them
dumpk kiter, "kiter", 8, 0
dumpk koutrig, "koutrig", 8, 0

insnd   = 10 
ibasfrq = 44100 / ftlen(insnd) ; Use original sample rate of insnd file 

kamp   expseg 0.001, p3*0.2, 0.2, p3*0.6, 0.2, p3*0.2, 0.001 ;a swell in amplitude
kpitch = 1
kdens  = kiter
kaoff  line 0, p3, .1
kpoff  = 0
kgdur  line .002, p3, .002
imaxgdur =  .5 

asig  grain kamp, kpitch, kdens, kaoff, kpoff, kgdur, insnd, 5, imaxgdur, 0.0 

outs asig, asig

endin

</CsInstruments>
<CsScore>

f5  0 512  20 2 ; Hanning window 

f 10 0 4096 10 1 

;            Iter  Iter      X     X    Y   Y   Trigger
i1   0   10   120   1        0     1   -1   0     100

e
</CsScore>
</CsoundSynthesizer>

```

![01](https://user-images.githubusercontent.com/68651266/106779197-0bb42a80-6647-11eb-8d45-126fd6718ce6.gif)

**Comment by csounder** [comment]
nice!

*- dB*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division

**Comment by MyrtleV** [comment]
I am working on a musicalisation of the Mandelbrot set using csound within MaxMSP, and came across your conversation.

I do get a musical phrase when running the original mandel.csd, despite it not containing the mandel opcode. I also get a small musical phrase from running your code. Could you please assist me with deciphering: 

- Kx/ky/maxIter: why choose p8, p3, p9 etc when the range is -1 1?
- Which part of this code makes it a representation of the Mandelbrot set, compared to the original code in mandel.csd?

Thank you very much!
Charlotte

**Comment by ST-Music** [comment]
FWIW I did make an attempt to create something using the mandel opcode. I don't know if it qualifies as "Mandelbrot music", whatever that may be.  I've tried posting here with no luck so here's a link: 
https://forum.csound.com/t/mandel-csd-new-version/

Any comments or advice to a noob is always welcome.

**Comment by csounder** [comment]
a very nice example, but I don't think we need links to his SoundCloud or
Youtube channel in the manual as that is not standard.

*- Dr.B*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division

**Comment by ST-Music** [comment]
I agree, the links were simply intended for viewers in the forum. I have no
opposition to edits being made to present the example in keeping with
tradition, I would simply ask to be involved with any. Thank you all for
your interest.

Scott Daughtrey

**Comment by csounder** [comment]
Scott,

I hope you didn't read that the wrong way.  

I was excited to see your links and am especially excited about your instrument and generative/algorithmic piece!  We don't typically have personal links on manpages - that's all. And I do hope that your example will be added to the manual.

I was just showing things like this to my students yesterday - and now - for sure - I will share your work with them in next week's class.  Your example is excellent for the manuals too.  I have been encouraged that we should have more "musical" and "contextual" examples for each opcode, and this is excellent.

**Comment by gogins** [comment]
There are many ways to get the Mandelbrot set or its dual, the Julia set,
to generate musical scores.

One way is shown in your example.

Another way is to iterate a point on the border of the Mandelbrot set,
which has an orbit that is a strange attractor and never repeats, or near
the border, which will be attracted to a fixed point inside the Mandelbrot
set or to infinity. With this approach, each iteration of the complex point
can be interpreted as two pitches, i.e. as two points. Here is a link to an
example I just wrote:
https://github.com/gogins/michael.gogins.studio/blob/master/music/mandelbrot_orbit.csd
.

There are of course other ways. One can generate the Julia set
corresponding to a point in the Mandelbrot set, and somehow interpret the
entire Julia set as a score.

Best,
Mike
-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by csounder** [comment]
Lovely Michael.

Thanks for sharing.

Hopefully, I will see you at the ICSC in Ireland!

I wish I could attend the monthly Zoom Meetings you host, but I am teaching
this semester on Wednesdays.

Take care

*- Dr.B*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division

**Comment by tjingboem** [comment]
second proposal from Scott Daughtrey
a bit more to the 'standard example presentation' of the Csound manual

```
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac     ;;;RT audio out
;-iadc    ;;;uncomment -iadc for RT audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o mandel.wav -W ;;; for file output any platform 
</CsOptions>
<CsInstruments>

; example by Scott Daughtrey [ST Music]

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1
    
seed 0       ; different random result at each run

gaRvbL  init ; initialize global reverb
gaRvbR  init
; table is 5th mode of Hungarian Minor Scale
giNotes ftgen 0, 0, 0, 2, 6.07, 6.08, 6.11, 7.00, 7.02, 7.03, 7.06, \  
        7.07, 7.08, 7.11, 8.00, 8.02, 8.03, 9.06, \
        8.07, 8.08, 8.11, 9.00, 9.02, 9.03, 9.06, \
        9.07

    instr Trigger 
kTrig = gausstrig(1, 1.85, 1.5) ; randomly trigger mandel opcode and timing of note production
kX    = trandom(kTrig, -1.6, 0) ; randomly select X coordinates
kY    = randomh(0, 1.2, 10) ; randomly select Y coordinates
kIter, kOutrig mandel  kTrig, kX, kY, 21 ; set range of iterations between 0-21
  schedkwhen kOutrig, 0, 0, "Mandel", 0, .7, p4, kIter ; trigger Mandel instr and send relevant parameters
    endin

    instr Mandel
iNote = table(p5, giNotes, 0, 0, 0) ; table uses mandel iterations to select indexed notes from giNotes ftable
iFreq = cpspch(iNote+p4) ; convert notes to cps
 if iFreq == 10.07 then
  iFreq = 7.07
 endif
iRand = random(.5, .99) ; randomize amplitude and pluck position (iPlk)
aSig  = wgpluck2(iRand, .3*iRand, iFreq, .2, .3)
iPan  = random(.2, .8) ; randomize pan position
aL, aR  pan2 aSig, iPan ; pan each note
  outs aL, aR ; output stereo signal
gaRvbL  +=  aL*.3 ; send a little to global reverb channels
gaRvbR  +=  aR*.3
    endin

    instr Reverb ; reverb instrument
aL, aR reverbsc gaRvbL, gaRvbR, .93, 2^14
  outs aL, aR
   clear gaRvbL, gaRvbR
    endin

</CsInstruments>
<CsScore>
i"Trigger" 0 3600 0
i .       .1 3600 1
i"Reverb"  0 3606
e
</CsScore>
</CsoundSynthesizer>
```

**Comment by tjingboem** [comment]
> Scott,
> 
> I hope you didn't read that the wrong way.

Yes it was just a dirty copy and paste action from my side, to the issue on examples for every opcode (mandel in this case).
So that it didn't get lost in all the email traffic that is going on, i parked it there...

> I was excited to see your links and am especially excited about your instrument and generative/algorithmic piece! We don't typically have personal links on manpages - that's all. And I do hope that your example will be added to the manual.

> I was just showing things like this to my students yesterday - and now - for sure - I will share your work with them in next week's class. Your example is excellent for the manuals too. I have been encouraged that we should have more "musical" and "contextual" examples for each opcode, and this is excellent.

Why not have a few links for **musical examples** on a manual page, pointing to the **musical collection** of csds in https://github.com/csound/manual/tree/master/examples/musical?
csds are lightweight as long as there are no big samples are used, and they are fun and inspiring.

A nice picture of the Mandelbrot set would be nice to have on the manual page as well, but then it should not conflict with the copyrights nightmare.

**Comment by tjingboem** [comment]
I'm trying to get some structure on the manual page of the **mandel** opcode, looking for the balance of explaining (manual!) and inspiring (fun!)...

- I have combined the 2 csds above from Stefano to one csd. The 2 instruments are variations on the same theme, and together in one csd they remain a simple and transparent instrument . I think this would be great to have on the manual page- not too long or complicated but still explains (a bit) what **mandel** is about
- then copy the musical examples from Michael and Scott to the **musical collection** folder https://github.com/csound/manual/tree/master/examples/musical
and create a link to these 2 examples on the **mandel** manual page. 
- to add an image to the manual page of this Mandelbrot set, where the X and Y lines are seen. This would help explaining the "coordinates of a given point belonging to the complex plane" **kx** and **ky**
![6f437431ab06ab94cc7c8c6d39f4842048a21572](https://user-images.githubusercontent.com/6670911/195981923-95acb304-8076-4216-b249-d865893f2af9.png)


This is the combined instrument example from Stefano. This could function as the basic example on the manual page: 
[mandelStafano.csd.zip](https://github.com/csound/manual/files/9791805/mandelStafano.csd.zip)

What do you/we think?

**Comment by csounder** [comment]
A great plan - and a nice combined instrument too.

*- Dr.B*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division

**Comment by tjingboem** [comment]
done.
This new manual page can be admired at https://csound.com/manual/mandel.html

**Comment by ST-Music** [comment]
Very cool, thank you for including my example.

Scott Daughtrey
