### ISSUE TITLE
MS decoding example

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#529]
this example shows the decoding of an interleaved sample and 2 separate samples (M and S as separate mono)

New samples are made:

[MSjungle_interleaved.wav.zip](https://github.com/csound/manual/files/6291828/MSjungle_interleaved.wav.zip)
[Mjungle.wav.zip](https://github.com/csound/manual/files/6291830/Mjungle.wav.zip)
[Sjungle.wav.zip](https://github.com/csound/manual/files/6291832/Sjungle.wav.zip)

```
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac     ;;;realtime audio out
;-iadc    ;;;uncomment -iadc if RT audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o ms2st.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1

; by  Menno Knevel - 2021
; sample = ambient sound of waterfall + animals (monkey)

instr 1 

am, as    diskin2    "MSjungle_interleaved.wav", 1, 0, 1 ; interleaved stereo, MS encoded
kwidth = p4                                              ; left = M, right = S
al, ar ms2st  am, as, kwidth
outs al, ar
endin

instr 2 

am    diskin2    "Mjungle.wav", 1       ; M sound as a separate mono sound
as    diskin2    "Sjungle.wav", 1       ; S sound as a separate mono sound
kwidth = p4     
al, ar ms2st  am, as, kwidth
outs al, ar

endin
</CsInstruments>
<CsScore>

i1 0 6.7 0         ; M only
i1 + 6.7 .3        ; M and a bit of S
i1 + 6.7 .5        ; M + S equal volume
i1 + 6.7 1         ; S only 

i2 28 6.7 0         ; M only
i2 +  6.7 .3        ; M and a bit of S
i2 +  6.7 .5        ; M + S equal volume
i2 +  6.7 1         ; S only
e
</CsScore>
</CsoundSynthesizer>
```

On the manual page an image of the interleaved stereo MS file and an image of the 2 separate mono files M and S will be shown, so the user knows of the different possible states of the MS samples to be decoded:
![MSjungle_interleaved](https://user-images.githubusercontent.com/6670911/114305610-2c7e7d80-9ad9-11eb-93ad-6d6b47e3e3ef.png)
![MSjungle_separate](https://user-images.githubusercontent.com/6670911/114305614-386a3f80-9ad9-11eb-8394-3fec32419502.png)

**Comment by csounder** [comment]
Wonderful!  Can't wait to share with class.

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music

**Comment by tjingboem** [comment]
done
a second sample may follow later
