### ISSUE TITLE
!= example .csd - perf error vco2 not initialized

### ISSUE THREAD

**Issue by boulangerlabs** [csound/manual#53]
STARTING FILE
Creating options
Creating orchestra
Creating score
rtaudio: PortAudio module enabled ... 
using blocking interface
Elapsed time at end of orchestra compile: real: 0.001s, CPU: 0.001s
sorting score ...
	... done
Elapsed time at end of score sort: real: 0.001s, CPU: 0.001s
--Csound version 6.06 (double samples) Sep 29 2015
midi channel 1 using instr 1
midi channel 2 using instr 1
midi channel 3 using instr 1
midi channel 4 using instr 1
midi channel 5 using instr 1
midi channel 6 using instr 1
midi channel 7 using instr 1
midi channel 8 using instr 1
midi channel 9 using instr 1
midi channel 10 using instr 1
midi channel 11 using instr 1
midi channel 12 using instr 1
midi channel 13 using instr 1
midi channel 14 using instr 1
midi channel 15 using instr 1
midi channel 16 using instr 1
0dBFS level = 1.0
orch now loaded
audio buffered in 1024 sample-frame blocks
PortAudio V19-devel (built Sep  4 2014 22:30:30)
   0: adc0 (Built-in Microph)
PortAudio: selected input device 'Built-in Microph'
reading 4096-byte blks of shorts from adc (RAW)
   0: dac0 (Built-in Output)
PortAudio: selected output device 'Built-in Output'
writing 2048 sample blks of 64-bit floats to dac 
SECTION 1:
ftable 1:
new alloc for instr 1:
new alloc for instr 1:
instr 1:  ipch = 277.190
new alloc for instr 1:
PERF ERROR in instr 1: vco2: not initialised
asig	vco2	.7	ipch	0	0	0	0	
   note aborted
PERF ERROR in instr 1: vco2: not initialised
asig	vco2	.7	ipch	0	0	0	0	
   note aborted
B  0.000 ..  0.500 T  0.500 TT  0.500 M:  0.81636  0.81636
Score finished in csoundPerformKsmps().
inactive allocs returned to freespace
end of score.		   overall amps:  0.81636  0.81636
	   overall samples out of range:        0        0
2 errors in performance
Elapsed time at end of performance: real: 0.774s, CPU: 0.049s
closing device
22 2048 sample blks of 64-bit floats written to dac

**Comment by jpffitch** [comment]
Works for me

**Comment by jpffitch** [comment]
What input are you using?  O tried vco2.csd

**Comment by jpffitch** [comment]
You mean notequal.csd I think

**Comment by jpffitch** [comment]
Replaced with working version
