### ISSUE TITLE
MS encoding example

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#530]
this is the proposal for an example for st2ms:
 
```
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac     ;;;realtime audio out
;-iadc    ;;;uncomment -iadc if RT audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o st2ms.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1

; by  Menno Knevel - 2021
; sample = ambient sound of waterfall + animals (monkey)

instr 1 

al, ar    diskin2    "STereoJungle.wav", 1, 0, 1    ; stereo sample
am, as st2ms  al,ar
fout "MSJungleEncoded.wav", -1, am *.6, as *.6   ; write to audio wav file as well
outs am *.6, as *.6                                 ;  but reduce volume a bit

endin
</CsInstruments>
<CsScore>

i1 0 6.7 0         ; encoded signal

e
</CsScore>
</CsoundSynthesizer>
```

using the stereo ambient sample:
[STereoJungle.wav.zip](https://github.com/csound/manual/files/6291934/STereoJungle.wav.zip)

the stereo sample to be encoded.

**Comment by tjingboem** [comment]
perhaps it would be nice to write the created MS file to disk as well.
Isn't there a recent modern opcode that can do this?

**Comment by vlazzarini** [comment]
fout writes to disk

**Comment by tjingboem** [comment]
Thanks!

![Screenshot from 2021-04-11 12-25-06](https://user-images.githubusercontent.com/6670911/114309322-12e43280-9ae7-11eb-86c0-d747db321ec7.png)

i found that st2ms has settled in a strange place...

**Comment by vlazzarini** [comment]
right, the link got in the wrong position. Will fix.

**Comment by tjingboem** [comment]
still testing...

```
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac     ;;;realtime audio out
;-iadc    ;;;uncomment -iadc if RT audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o st2ms.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1

; by  Menno Knevel - 2021
; sample = ambient sound of waterfall + animals (monkey)

instr 1 
al, ar    diskin2    "STereoJungle.wav", 1, 0, 1    ; stereo sample
am, as st2ms  al,ar
fout "MSJungleEncoded.wav", -1, am *.6, as *.6   ; write MS audio wav file to disk
outs am *.6, as *.6                                 ;  but reduce volume a bit

endin

instr 2 
al, ar    diskin2    "MSJungleEncoded.wav", 1, 0, 1    ; encoded sample
am, as ms2st  al,ar, p4                                               ; now decode it!
outs am, as                             

endin

</CsInstruments>
<CsScore>

i1 0 6.7          ; encode signal, write to disk
i2 10 6.7 .5      ; read encoded file from disk and decode 1:1
i2 17 6.7 .7      ; decode but with more width than original sample


e
</CsScore>
</CsoundSynthesizer>
```

**Comment by tjingboem** [comment]
examples and samples are committed, ready for release 6.16

**Comment by csounder** [comment]
nice - and a nice sample to have with the manual - many of the manual
samples could use a face-lift.

*- dB*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division

**Comment by csounder** [comment]
NICE

*- dB*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division

**Comment by tjingboem** [comment]
i have opened a new issue where we can discuss what manual samples do not or no longer meet the criteria- and what are the criteria?- or should be added.
replace and add good samples #537

There we can discuss what samples should be replaced or added and why.
Hope to see you there :)

**Comment by csounder** [comment]
I will be there 

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music
