### ISSUE TITLE
Linear Algebra Opcodes- no info

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#538]
https://csound.com/manual/linearalgebraopcodes.html

all of these opcodes have no manual page and i have no idea what they do.
Also on the manual page there are 2 links that are both dead links.
Yet they are part of the basic Csound.

I'm sure they have their use, although some of them are replaced by Csound array opcodes?
How can we approach this issue? Should all individual LAO get their individual manual page and examples?

**Comment by tjingboem** [comment]
link must be https://getfem.org/gmm/index.html

**Comment by tjingboem** [comment]
a link has been added: https://csoundjournal.com/issue22/linearAlgebra.html
to the LA opcodes manual page.
So these opcodes did have some exposure and might actually be in use by some.

Manual pages for every one of these opcodes seems overkill to me.

The LA opcodes manual page stays available, but apart from the link will not be expanded upon- nor will it be deleted.

**Comment by gogins** [comment]
Thanks!
