### ISSUE TITLE
Soundfont Appendix G reallocation?

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#539]
i would like to add the important information on Soundfonts in the Appendix  (https://csound.com/manual/MiscSf2.html) and how they work internally, to be added to https://csound.com/manual/SiggenSample.html#SiggenSampleSF
This information seems a bit lost and hard to find if you are not aware of it, so it is better off imo when concentrated on the manual page on all the different Soundfont opcodes.

Also, i would like to add a nice image that shows the internal of the Soundfont, from sample to instrument to preset.

Please feel free to differ and provide some arguments.

**Comment by csounder** [comment]
Wonderful plan!!

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music

**Comment by tjingboem** [comment]
good!
I copypasted the text to see how it all fits on the page https://csound.com/manual/SiggenSample.html#SiggenSampleSF

image showing the internal of the Soundfont will follow soon

**Comment by csounder** [comment]
you might also consider including a few links to soundfont editors for each
platform
- when I show these opcodes to my students (I always try to give them a few
free or inexpensive SF editors for the mac so that they can convert their
samples or map/make new ones

*- dB*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division

**Comment by tjingboem** [comment]
The ones i would recommend are Swami http://www.swamiproject.org/download/
and Polyphone https://www.polyphone-soundfonts.com/download
These 2 are free for download and multi-platform.

**Comment by csounder** [comment]
COOL - I didn't know about SWAMI

*- dB*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division

**Comment by tjingboem** [comment]
proposal for the image explaining the soundfont
![SF](https://user-images.githubusercontent.com/6670911/118864081-eb4f6980-b8df-11eb-8a1a-366c5744ab7f.png)

comments are welcome

**Comment by csounder** [comment]
Nice

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music

**Comment by tjingboem** [comment]
done
