### ISSUE TITLE
show info on manual page about it being a plugin

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#540]
As the manual page continue to contain the opcode now being a plugin, it should be mentioned on this manual page if these particular opcodes : "is NOT part of Csound distribution" and that it "should be build separately from the Csound plugin repo"
This would inform the user why he/she gets a warning about a not-found library.

"This is actually very experimental and it should become effective with Csound7."

**Comment by tjingboem** [comment]
only the py opcodes do not mention: Plugin opcode in blah.

**Comment by tjingboem** [comment]
this seems to be a double issue entry: https://github.com/csound/manual/issues/582
This work is already done.

**Comment by csounder** [comment]
excellent.

*- Dr.B*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division
