### ISSUE TITLE
include Csound Analyze Utilities in examples

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#541]
The different Csound Utilities analyze the soundfile in their own ways, and are sometimes system dependent (cvanal, 32 or 64 bit).
The updated examples based on these analysis files can be analyzed AND read back (+transformed) in 1 csd file:
1. by using the system opcode in instr 1, calling the Csound Utility and create the analyze file
2. then use the created analyzed file- possibly the existing instr that would become instr 2 or 3

If all is done in 1 csd then the analysis dependency is no longer relevant.
Another benefit is that analyze and reading back/transformation is done in 30 seconds- it is a fast method, much faster than an example for analyzing, writing the result to disk, load an example for reading back...

Examples for the manual pages of the Analyze Utilities can have at least 2 completely different analyze settings. The reading back should be as simple as possible to just show these differences.

**Comment by tjingboem** [comment]
template for the examples would be ( in this case for lpread):

```
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac     ;;;realtime audio out
;-iadc    ;;;uncomment -iadc if realtime audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o lpread.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1

; by Menno Knevel

instr 1 ; analyze this selection and output result to pvx file
ires system_i 1,{{     
    lpanal -p34 -h200 -P100 finneganswake1.flac finneganswake1.lpc
        }}
endin

instr 2 ; untreated signal
asig    diskin2   "finneganswake1.flac", 1
outs    asig, asig
endin

instr 3
ilen  filelen "finneganswake1.flac"	    ; get length of soundfile
prints "finneganswake1.flac = %f seconds\\n",ilen

ktime line 0, p3, p4                    ; timepointer
krmsr,krmso,kerr,kcps lpread ktime,"finneganswake1.lpc"
krmso *=.00005			                ; lower volume
aout  vco2 krmso, kcps
aout  butlp aout, 5000                  ; filter low pass
krmsr *=.0003			                ; lower volume
asig  rand krmsr                        ; use residual for the noise 
      outs aout+asig, aout+asig	        ; add saw wave and noise

endin
</CsInstruments>
<CsScore>
i1 0 2
i2 2 12.7       ; untreated signal
i3 14 10 1	    ; first words only, stretched for 10 seconds
i3 25 12.7 12.7	; whole sentence
e
</CsScore>
</CsoundSynthesizer>
```

**Comment by tjingboem** [comment]
first attempt: template for the examples for all Analyze Utilities

```
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac     ;;;realtime audio out
;-iadc    ;;;uncomment -iadc if realtime audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o lpread.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1

; by Menno Knevel

instr 1 ; analyze sound file and output result to lpc file
ires system_i 1,{{     
    lpanal -p34 -h200 -P50 -Q500 -v1 finneganswake1.flac finneganswake1.lpc
        }}
endin

instr 2 ; analyze sound file and output result to a second lpc file
ires system_i 1,{{     
    lpanal -p50 -h300 -P70 -Q100 -v1 finneganswake1.flac finneganswake2.lpc
        }}
endin

instr 3 ; untreated signal
asig    diskin2   "finneganswake1.flac", 1
outs    asig, asig
endin

instr 4
ilen  filelen "finneganswake1.flac"	    ; get length of soundfile
prints "finneganswake1.flac = %f seconds\\n",ilen

ktime line 0, p3, ilen                    ; timepointer
krmsr,krmso,kerr,kcps lpread ktime, p4
krmso *=.00005			                ; lower volume
aout  foscil krmso, kcps, 1, 10, 1
aout  butlp aout, 5000                  ; filter low pass
krmsr *=.0003			                ; lower volume
asig  rand krmsr                        ; use residual for the noise 
      outs aout+asig, aout+asig	        ; add saw wave and noise

endin
</CsInstruments>
<CsScore>
s
i1 0 2        ; lpc file 1
i2 0 2        ; lpc file 2
s
i3 0 12.7       ; untreated signal
s
i4 0 12.7 "finneganswake1.lpc"	; whole sentence
i4 15 12.7 "finneganswake2.lpc"	; whole sentence
e
</CsScore>
</CsoundSynthesizer>
```

**Comment by tjingboem** [comment]
thanks for checking this- changed already ;-)
I'll also try to get the analysis time down a bit, to let say: 0.1 sec
Should be possible, because system_i is init time.

All runs _almost_ realtime now!  
And it is nice to see that this approach makes all analysis files  'not-computer-dependent', because all is done on the same machine in one csd file.

I'm also thinking about a message in the output console, something like:
"at the moment, you are listening to the first analysis file- please sit back and enjoy the ride..."
but perhaps this too much...

**Comment by csounder** [comment]
yes - a little more feedback in the console is a great thing too.
- but this is super exciting for everyone, but beginners especially - to
see the whole process taking place inside the .csd

super.



*- dB*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division

**Comment by tjingboem** [comment]
i played around with the messaging command and even fell back to some 80's type of messaging in the output. It sure does bring back memories...but, it is true, with the minimal options i have, the text does stand out now.

This example has become one that really shows the result of 2 ways of analyze settings, but it now has become a rather complicated example - in fact, more of a demonstration of different analyze settings. 

I don't think it is suited for explaining the opcodes, but can demonstrate different settings and the according result. So this could be a template for the Utility pages only.

```
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac   -m0  ;;;realtime audio out
;-iadc    ;;;uncomment -iadc if realtime audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o lpanal.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1

; by Menno Knevel 2021

gilen  filelen "finneganswake1.flac"	    ; get length of soundfile

instr 1 ; analyze sound file and output result to lpc file
ires system_i 1,{{     
    lpanal -p34 -h200 -P50 -Q500 -v1 finneganswake1.flac finneganswake1.lpc
        }}
endin

instr 2 ; analyze sound file and output result to a second lpc file
ires system_i 1,{{     
    lpanal -p50 -h300 -P70 -Q100 -v1 finneganswake1.flac finneganswake2.lpc
        }}
endin

instr 3 ; untreated signal
asig    diskin2   "finneganswake1.flac", 1
prints  "\n---***YOU NOW HEAR THE UNTREATED SOUND***---\n"

prints "\n---***the soundfile 'finneganswake1.flac' has a duration of %f seconds***---\\n",gilen
outs    asig, asig
endin

instr 4

prints  "\n---***YOU NOW HEAR THE RESULT OF THIS ANALYZED FILE:***---\n"
ktime line 0, p3, gilen                    ; timepointer
krmsr,krmso,kerr,kcps lpread ktime, p4
krmso *=.00005			                ; lower volume
aout  foscil krmso, kcps, 1, 10, 1
krmsr *=.0003			                ; lower volume
asig  rand krmsr                        ; use residual for the noise 
      outs aout+asig, aout+asig	        ; add FM and noise

endin
</CsInstruments>
<CsScore>

i1 0 .1        ; lpc file 1
i2 0 .1        ; lpc file 2

i3 0 12.7       ; untreated signal

i4 15 12.7 "finneganswake1.lpc"	; whole sentence
i4 30 12.7 "finneganswake2.lpc"	; whole sentence, but analyzed with different settings
e
</CsScore>
</CsoundSynthesizer>
```

**Comment by tjingboem** [comment]
this is the first serious attempt for an example for _lpanal_ https://csound.com/manual/lpanal.html
I am using the fox as this is such a versatile sample

```
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac   -m0 --limiter=.95 ;;;realtime audio out, with limiter protection
; For Non-realtime ouput leave only the line below:
; -o lpanal.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1

; by Menno Knevel 2021

gilen  filelen "fox.wav"	    ; get length of soundfile

instr 1 ; analyze sound file and output result to 2 lpc files
ires1 system_i 1,{{ lpanal -p34 -h200 -P50  -Q5000 -v1    fox.wav fox1.lpc }}
ires2 system_i 1,{{ lpanal -p50 -h400 -P250 -Q500  -v1    fox.wav fox2.lpc }}
ires3 system_i 1,{{ lpanal -p50 -h400 -P30  -Q100  -v1 -a fox.wav fox3.lpc }}
endin

instr 2 ; untreated signal
asig    diskin2   "fox.wav", 1
prints  "\n---***YOU NOW HEAR THE UNTREATED SOUND SAMPLE***---\n"
prints "---*duration of soundfile is %f seconds*---\\n",gilen
outs    asig, asig
endin

instr 3
prints  "\n---***YOU NOW HEAR THE RESULT OF THIS ANALYZED FILE:***---\n"
ktime line 0, p3, gilen                         ; timepointer = equal to soundfile duration
krmsr,krmso,kerr,kcps lpread ktime, p4
asig    buzz      krmso, kcps, int(sr/2/kcps), 1
abuzz   lpreson   asig
aref    oscil     .8,100
abuzz   balance2   abuzz, aref                  ; try to get amplitudes under control
krmsr   *=  .0003       		                ; lower volume for the noise
anoise  rand krmsr                              ; use residual for the noise 
outs (abuzz+anoise)*.1, (abuzz+anoise)*.1	    ; buzz and noise but lower volume
endin

</CsInstruments>
<CsScore>
f 1 0 8192 10 1         ; sine for buzz
i1 0 .1                 ; lpc file 1,2&3

i2 1 2.7                ; untreated signal

i3 5 2.7  "fox1.lpc"	; whole sentence
i3 10 2.7 "fox2.lpc"	; whole sentence, but analyzed with different settings
i3 15 2.7 "fox3.lpc"	; whole sentence, and again analyzed with different settings
e
</CsScore>
</CsoundSynthesizer>
```

I am using the time that the sample fox is playing so that the analysis of the 3 files can finish, also on slower systems.
The printing to the screen corresponds to what you here at that given moment- at least, it does on my machine...
Comments are welcome.

**Comment by tjingboem** [comment]
Now that the template is set, this is a proposal for the hetro example for https://csound.com/manual/hetro.html
It does do quite some printing, so the fox starts 2 seconds in the csd- to make way for reading the messages in the Output.

```
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac   -m0 --limiter=.95 ;;;realtime audio out, with limiter protection
; For Non-realtime ouput leave only the line below:
; -o hetro.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1

; by Menno Knevel 2021

gilen  filelen "fox.wav"	    ; get length of soundfile

instr 1 ; analyze sound file and output result to 3 hetro files
ires1 system_i 1,{{ hetro fox.wav fox1.het }}           ; default settings
ires2 system_i 1,{{ hetro -f250 fox.wav fox2.het }}     ; high starting frequency
ires3 system_i 1,{{ hetro -f100 -h180 fox.wav fox3.het }}; up to 18kHz!
endin

instr 2 ; untreated signal
asig    diskin2   "fox.wav", 1
prints  "\n---***YOU NOW HEAR THE UNTREATED SOUND SAMPLE***---\n"
prints "---*duration of soundfile is %f seconds*---\\n",gilen
outs    asig, asig
endin

instr 3
prints  "\n---***YOU NOW HEAR THE RESULT OF THIS ANALYZED FILE:***---\n"
asig      adsyn     1, 1, 1, p4     ; use residual for the noise 
outs asig, asig	    
endin

</CsInstruments>
<CsScore>
f 1 0 8192 10 1         ; sine for buzz

i1 0 .1                 ; hetro file 1,2&3

i2 2 2.7                ; untreated signal

i3 5 2.7  "fox1.het"	; whole sentence
i3 10 2.7 "fox2.het"	; whole sentence, but analyzed with different settings
i3 15 2.7 "fox3.het"	; whole sentence, and again analyzed with different settings
e
</CsScore>
</CsoundSynthesizer>
```

**Comment by tjingboem** [comment]
proposal example for _atsa_  utility https://csound.com/manual/UtilityAtsa.html
every time in the output, i get when all is finished:
free(): invalid pointer
csound command: Aborted
might be a bug??

```
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac   -m0 --limiter=.95 ;;;realtime audio out, with limiter protection
; For Non-realtime ouput leave only the line below:
; -o atsa.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1

; by Menno Knevel 2021

gilen  filelen "fox.wav"	    ; get length of soundfile

instr 1 ; analyze sound file and output result to 3 hetro files
ires1 system_i 1,{{ atsa fox.wav fox1.ats }}            ; default settings
ires2 system_i 1,{{ atsa -h.8 fox.wav fox2.ats }}       ; some smearing
ires3 system_i 1,{{ atsa -h.1 -c2 fox.wav fox3.ats }}   ; only 2 cycles
endin

instr 2 ; untreated signal
asig    diskin2   "fox.wav", 1
prints  "\n---***YOU NOW HEAR THE UNTREATED SOUND SAMPLE***---\n"
prints "---*duration of soundfile is %f seconds*---\\n",gilen
outs    asig, asig
endin

instr 3
prints  "\n---***YOU NOW HEAR THE RESULT OF THIS ANALYZED FILE:***---\n"
ktime line 0, p3, gilen                         ; timepointer = equal to soundfile duration
asig ATSsinnoi ktime, 1, .4, 1, p4, 167         ; maximum # of partials = 167
outs asig, asig	    
endin

</CsInstruments>
<CsScore>
i1 0 .1                 ; atsa file 1,2&3

i2 2 2.7                ; untreated signal

i3 5 2.7  "fox1.ats"	; whole sentence
i3 10 2.7 "fox2.ats"	; whole sentence, but analyzed with different settings
i3 15 2.7 "fox3.ats"	; whole sentence, and again analyzed with different settings
e
</CsScore>
</CsoundSynthesizer>
```

**Comment by jpffitch** [comment]
Sounds like a bug.  Will add it to the list of things to look at

**Comment by vlazzarini** [comment]
Btw, it does not crash here on MacOS, but that doesn't mean much if this is a memory problem.

```
Score finished in csoundPerform().
inactive allocs returned to freespace
end of score.		   overall amps:  1.00000  1.00000
	   overall samples out of range:        0        0
0 errors in performance
closing device
763 2048 sample blks of 64-bit floats written to dac
```

**Comment by tjingboem** [comment]
demonstration proposal of _cvanal_ https://csound.com/manual/cvanal.html
Uses the short file from the examples folder: 
[rv_stereo.wav.zip](https://github.com/csound/manual/files/6531252/rv_stereo.wav.zip)

But there is something going on here:  the other demonstrations above of _lpanal, hetro_ and _atsa_ work out-of-the-box, but not this one. The _cvanal_ demonstration, when there is no path given for the creation of the impulse file, outputs its files to the Output folder of Csound, while the other demonstrations of _lpanal, hetro_ and _atsa_ create their files to where i run the example from. In my case i run all from the manualExamples.

```
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac   -m0  --limiter=.99 ;;;realtime audio out, with limiter protection
; For Non-realtime ouput leave only the line below:
; -o cvanal.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1

; by Menno Knevel 2021

gilen  filelen "rv_stereo.wav"	    ; get length of impulse soundfile

instr 1 ; analyze sound file and output result to 3 hetro files
ires1 system_i 1,{{ cvanal rv_stereo.wav rv_stereo1.con }}                  ; default settings
ires2 system_i 1,{{ cvanal -d.15 rv_stereo.wav rv_stereo2.con }}            ; use only first portion
ires3 system_i 1,{{ cvanal -b.25 -d.001 rv_stereo.wav rv_stereo3.con }}    ; take very short portion from the end
endin

instr 2 ; untreated signal
asig    diskin2   "beats.wav", 1
prints  "\n---***YOU NOW HEAR THE UNTREATED SOUND SAMPLE***---\n"
outs    asig, asig
endin

instr 3

prints  "\n---***YOU NOW HEAR THE RESULT OF THIS ANALYZED FILE:***---\n"
prints "--**used duration of impulse file = %5.3f seconds (total =%5.2f)**--\\n", p5, gilen

adry    diskin2 "beats.wav"                 ; input (dry) audio
awet1, awet2 convolve adry*.8, p4           ; stereo convolved (wet) audio
awet1  *=  p6                               ; scale amplitude of impulse sound, Left
awet2  *=  p6                               ; & Right channel
adrydel delay   adry, p5                    ; delay dry signal to align it with convolved signal
outs    (adrydel+awet1)*.8,(adrydel+awet2)*.8 ; mix wet & dry signals 
endin

</CsInstruments>
<CsScore>
i1 0 .1         ; cvanal file 1,2&3

i2 1 2          ; untreated signal

i3 4 3  "rv_stereo1.con"    0.39    .01	; use total impulse
i3 8 3  "rv_stereo2.con"    0.15    .01	; first portion of impulse
i3 12 3 "rv_stereo3.con"    0.001    1	; very short portion of impulse, starting from 0.25 sec, & scale amp
e
</CsScore>
</CsoundSynthesizer>
```

**Comment by tjingboem** [comment]
proposal for demonstrating the _pvanal_ utility https://csound.com/manual/pvanal.html

Again, there was no problem in that the pvx files were written to the folder i am running this example from.
It seems that only cvanal has this issue in writing to Output...

Here i slowed down the speed 2.4 times, so you can hear clearly what is happening with the different analyze settings.

```
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac   -m0  --limiter=.95 ;;;realtime audio out, with limiter protection
; For Non-realtime ouput leave only the line below:
; -o pvanal.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1

; by Menno Knevel 2021

gilen  filelen "fox.wav"	    ; get length of impulse soundfile

instr 1 ; analyze sound file and output result to 3 pvoc-ex files
ires1 system_i 1,{{ pvanal fox.wav fox1.pvx }}          ; default settings
ires2 system_i 1,{{ pvanal -K -w1 fox.wav fox2.pvx }}   ; very low indow setting
ires3 system_i 1,{{ pvanal -n256 fox.wav fox3.pvx }}    ; different frame size
endin

instr 2 ; untreated signal
asig    diskin2   "fox.wav", 1
prints  "\n---***YOU NOW HEAR THE UNTREATED SOUND SAMPLE***---\n"
outs    asig*.8, asig*.8
endin

instr 3

prints  "\n---***YOU NOW HEAR THE RESULT OF THIS ANALYZED FILE:***---\n"
ktime line 0, p3, gilen/2.4     ; slow down to have a good listen at what happens
asig  pvoc ktime, 1, p4, 1 
prints  "(playback is slowed down & limited to 'the quick brown fox')\n"
      outs asig*.8, asig*.8
endin

</CsInstruments>
<CsScore>
i1 0 .1                 ; pvanal file 1,2&3

i2 1 2.76               ; untreated signal

i3  5 10  "fox1.pvx"    ; default but slowed down
i3 16 10  "fox2.pvx"    ; low window setting
i3 27 10  "fox3.pvx"    ; smearing
e
</CsScore>
</CsoundSynthesizer>
```

Now all Analyzing utilities are done-

**Comment by tjingboem** [comment]
atsa, hetro and pvanal have their example.
Awaiting repairs of some opcodes for cvanal and lpanal examples

**Comment by csounder** [comment]
Wonderful

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music

**Comment by tjingboem** [comment]
lpanal has its example. https://csound.com/manual/lpanal.html

Now only awaiting repairs for cvanal and then i can close the issue

**Comment by jpffitch** [comment]
About cvanal can you give more details?  Your eamle ran for me with no 
problem so not sure wa you are expeting as a fix

**Comment by tjingboem** [comment]
yes, https://github.com/csound/csound/issues/1493
i was expecting that, like all other utilities, the analyze file was written to the place i am running the example from.

It does not here. All the other utilities do.
It outputs the analyze file to  the Output folder of Csound. I always forget, but is that SFDIR? or SSDIR?

So i have to set the specific path for the analyzed file to save  to wqhere the example is running from.

https://csound.com/manual/UtilityTop.html states that: _Resultant analysis files are written into the current directory, or to the named directory if a path is included._

**Comment by tjingboem** [comment]
the example is looking for the analyze file in the place the example is running from, but it is not there:
INIT ERROR in instr 2 (opcode convolve.i) line 37: CONVOLVE cannot load rv_stereo13.con
 from file /media/menno/datae/onderzoek/manualExamples/cvanal.csd (1)

**Comment by jpffitch** [comment]
Do you have the environmemt variable $SFDR set to anything?  I tried 
reading the cde and it may try to file the outout in the sound file 
directory.

If this variale does otexis (ie has the valur NULL) then it will use the 
dcurrent directory.

Does that explin it?

**Comment by tjingboem** [comment]
SFDIR=/media/menno/datae/csounddata/Output
and that is in fact the folder the analyze file is writing to.

**Comment by jpffitch** [comment]
So the issue is should we make a change in behavour or cange the 
dodumentation.

**Comment by tjingboem** [comment]
I have been thinking about this some more, and in https://csound.com/manual/OrchDirFiles.html it is established that:
* _Soundfiles for reading are sought in the current directory. Or SSDIR or SFDIR_
So they should be written to one of these places so they can be found.
* _Analysis control files for reading are sought in the current directory. Or SADIR_
So they should be written to one of these place in order to be found.

For backward compatibilty reasons this should not change, imo.

All the utily examples i made (ATSA, HETRO, LPANAL, PVANAL) write their Analysis file to the current dir.
So, when running these examples from the current dir, all analyzed files are found.

CVANAL should write his analyzed file to current dir or SADIR. But it is not. instead It writes to SFDIR. 
So, when running the example it checks not the current dir nor SFDIR.

(Now i must say that on my system i have had issues for Csound to find files from SFDIR, SSDIR and SADIR for a long time. 
So it may be that this fault is on my system only. But still CVANAL is not writing to the right dirs)

As CVANAL does not write to current dir, as opposed to the other Utilities, it can not be found when trying to look for it. 
And the Analyzed file is not written to SADIR but to SFDIR instead- wrong dir, and it can not be found:
```
cannot load rv_stereo13.con
INIT ERROR in instr 2 (opcode convolve.i) line 37: CONVOLVE cannot load rv_stereo13.con
 from file /media/menno/datae/onderzoek/manualExamples/cvanalJOHN.csd (1)
```

These are my env:
SSDIR=/media/menno/datae/csounddata/Samples
SADIR=/media/menno/datae/csounddata/Analyses
SFDIR=/media/menno/datae/csounddata/Output


Is the example working out of the box on your machine? Where does it write the Analyzed file to?

**Comment by jpffitch** [comment]
Are you suggesting that cvanal should write to SADIR (rather than SFDIR) or curent directory?

⁣Sent from TypeApp ​

**Comment by tjingboem** [comment]
I am suggesting that cvanal should be writing to the place where all utilities write to.
I don't know why the behavior of cvanal is different in that respect. At least, on my system.

All other analyze utilities on my computer write to the current directory; the directory where the example is running from. 
This provides clean examples that run out-of-the-box on all systems for every user. 
cvanal is the exception, and i wondered why and if that is correct.

**Comment by tjingboem** [comment]
cvanal example is committed.
All utilities have their examples.

The issue regarding the cvanal writing and reading path has been copied to CVANAL paths #1493- a Csound matter, not a manual matter.

**Comment by csounder** [comment]
I am really enjoying how these do all the work for the user - in the .csd.
From the terminal on the Mac.  Wonderful.

*- dB*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division

**Comment by tjingboem** [comment]
great- may i ask, Richard, that you try out the cvanal example? 
On my system it does not find the path and i have to set it manually, but i wonder if it works from the terminal on the Mac.

**Comment by csounder** [comment]
The cab al example works too, from terminal on the Mac 

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music

**Comment by tjingboem** [comment]
thank you for testing, good to know.

**Comment by csounder** [comment]
And the feedback that you give in the console, while the .csds are running
is excellent too!

*- dB*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division
