### ISSUE TITLE
src_conv missing example

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#543]
.

**Comment by AsterixMusic** [comment]
In my Csound I don't have "src_conv" utility...or maybe I'm wrong?
I'm working from terminal.
We should take care if we add an example because there is the risk to change/overwrite the original audio file used in many examples.

<img width="426" alt="Screenshot 2021-05-25 at 09 48 49" src="https://user-images.githubusercontent.com/68651266/119460168-b3608000-bd3e-11eb-9fbe-726a5c8a9225.png">

**Comment by tjingboem** [comment]
i get the same but i don't think src_conv can be called from Csound, but as a standalone:

![Screenshot from 2021-05-25 09-57-47](https://user-images.githubusercontent.com/6670911/119461365-e5bead00-bd3f-11eb-9e8a-95a865ec97bd.png)

Has to do with licensing that it cannot be part of the Csound itself.

**Comment by tjingboem** [comment]
don't know much about licensing, but can we use zitaresample as an opcode?
![Screenshot from 2021-05-25 10-10-35](https://user-images.githubusercontent.com/6670911/119462965-91b4c800-bd41-11eb-8992-da0eb36e8c20.png)

**Comment by tjingboem** [comment]
i got the right result when using:

menno@mennoASUSZ170 /media/menno/datae/onderzoek/manualExamples $ src_conv -o pietje.wav -r96000 fox48.wav
wrote 264640 frames converting sr 48000.00 to 96000.00

The result is indeed a new sample 'pietje.wav' with sr 96000

I think the example can now be made.

**Comment by tjingboem** [comment]
Manual says: 
src_conv [flags] infile

and there is no output.
Why bother to use this program if there is no output?
Better change it in the syntax to:
src_conv [flags] infile [-o outfile]
so that user immediately sees the infile and the outfile

**Comment by tjingboem** [comment]
First but not final attempt to show that it works:

```
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac   
; For Non-realtime ouput leave only the line below:
; -o src_conv.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1

; by Menno Knevel 2021

instr 1 
ires1 system_i 1,{{ src_conv -r48000 -Q5 beats.wav -o beats48.wav }}
endin

instr 2
ires2 system_i 1,{{ sndinfo -i beats48.wav }}
endin

</CsInstruments>
<CsScore>
i1 0 1
i2 0 1                 

e
</CsScore>
</CsoundSynthesizer>
```

**Comment by tjingboem** [comment]
Second attempt:

```
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac   
; For Non-realtime ouput leave only the line below:
; -o src_conv.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr = 48000  ; sample rate of beats.wav = 44100
ksmps = 32  ; and will be resampled to 48000
nchnls = 2
0dbfs  = 1

; by Menno Knevel 2021

; resample in the highest qualty, name the new sample 'beats48.wav'
gires system_i 1,{{ src_conv -r48000 -Q5 beats.wav -o beats48.wav }}

instr 1
ires system_i 1,{{ sndinfo -i beats48.wav }} ; check sample rate
aout    diskin2 "beats48.wav", 1
outs    aout, aout  
endin

</CsInstruments>
<CsScore>
i1 0 2              

e
</CsScore>
</CsoundSynthesizer>
```

**Comment by tjingboem** [comment]
done
