### ISSUE TITLE
add extension to scans matrices and trajectories

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#547]
For the scanu opcodes, make a distinction in extension so it is clear that it is meant to be used by these opcodes.

So far the best candidates are:
.matrx
.traj

And for the xscanu opcodes:
.xmatrx
.xtraj

**Comment by csounder** [comment]
I like it.

*- dB*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division

**Comment by tjingboem** [comment]
Quote from Richard:
As a note: john pointed out to me that there are two 'types' of matrix files - one that is Binary and one that is Text.
- he is suggesting that we differentiate them (in the naming at least, since both are supported by the opcodes) by using the '.matrxB' or '.matrxT' extensions

**Comment by jpffitch** [comment]
Te original matrix files are binary and are used via gen1.  Way I have 
intrduced is a textual form that nees conersion by gen44, so users can 
create their own toplogoie.  Using the text file when te binary is 
expected anf vice cversa with lead to failures, so they should nbe 
differentiated.  The gen44 examole uses this naming structure but the 
scanu/scanu2 manual pages do not (yet).

Are ou happy with this change?

**Comment by tjingboem** [comment]
Ah, i didn't know that: f3 0 16384 -23 "string-128.matrix" passed by GEN1 internally. 
![Screenshot from 2021-06-04 21-18-27](https://user-images.githubusercontent.com/6670911/120852409-74ba9900-c57a-11eb-8609-b772c2e463f8.png)
Yes, that would make sense to give these files the extension .matrxB

For the xscan opcodes, the matrix looks like this:
![Screenshot from 2021-06-04 21-22-24](https://user-images.githubusercontent.com/6670911/120852869-17731780-c57b-11eb-9454-ae657f6cc9b2.png)
The extension for these matrices could be .XmatrxT

In the manual examples i have detected only one trajectory: 
128-spiral-8,16,128,2,1over2
that could be renamed 128-spiral-8,16,128,2,1over2.traj as both the X and the non-Xscan opcodes can use this.
![Screenshot from 2021-06-04 21-30-16](https://user-images.githubusercontent.com/6670911/120853524-17274c00-c57c-11eb-8aa9-95bebb540179.png)

**Comment by csounder** [comment]
A trajectory can be made with a gen or an opcode like linseg.   If the tables are 128 values, the trajectory line can go from 0-128 or an expon can go from .001-128 or a large linseg could go back and forth 0 64 128 64 0 or an expseg can go from .001 32 128 32 .001 32 64 32 128. (for a zigzag) or you could feature paris’ fancy fractal trajectory.

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music

**Comment by csounder** [comment]
I would recommend that you put in some more simple trajectories too!

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music

**Comment by tjingboem** [comment]
Each example can show several options in trajectory creation and matrices, but i have not yet thought fully out on what would be the best structure of the csd to demonstrate all these options.

For now, i think it would be best to get a grip on things in the naming:
- clear extensions for the files to identify their goal right away
- i've seen in scanu2 words like ifndisplace and ifnmatrix etc. that make more sense to me than what i see on the manual page of scanu. Some or all of this renaming can be used for all scan manual pages and examples
- perhaps images of the used trajectories and matrices as used in the example- but that can take a lot of space on the page. It could be something as you see on the manual page for GEN18 https://csound.com/manual/GEN18.html

**Comment by csounder** [comment]
Thanks Menno,

I agree completely - the renaming of the parameters actually does explain
better what they are doing - and they should be changed in the scanu man
page as well
- I think that John might have planned to do that, but it would be cool if
you do,

Yes, clear extensions intuitively indicate what is happening or what the
use might be. Great

And, I just wanted you to know that there are many many options for the
scans trajectory - not just the one provided by Paris in his original paper
and demo.
- it is a cool one for sure and does give a roller-coaster sense of how one
might 'ride' (hear) the evolving surface of the resulting scanu wave.

The mini waveform views in gen18 are very cool and help one better
understand (visualize) for sure.

*- dB*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division

**Comment by tjingboem** [comment]
i think i will start with renaming the matrices and the trajectory, those that are used in the present examples.
i will show a proposal for this here soon. When you agree and there is no error, the renamed matrices and trajecory will be committed and changed in all the present examples.

If John wants to do the renaming of the parameters before release, very good.

Making better/more complete examples will follow later, after the release of 6.16- i have yet to think things through regarding all options in the examples and how to produce those nice images. 
I presume this is not a task to do before the release, right??

(I remember making those images for GEN18 but forgot which program i used to create them)

> And, I just wanted you to know that there are many many options for the
> scans trajectory - not just the one provided by Paris in his original paper
> and demo.

I know-  the one provided by Paris but also some line or linsegs will be present in the examples and as images.

**Comment by tjingboem** [comment]
oops wrong button

**Comment by jpffitch** [comment]
Ichanged the arg nams in scanu manuak age

**Comment by tjingboem** [comment]
can you do the same for xscanu as well?

**Comment by tjingboem** [comment]
These will be renamed:

128,8-cylinderX --> 128,8-cylinder.XmatrxT
128,8-gridX --> 128,8-grid.XmatrxT
128,8-torus --> 128,8-torus.matrxB
128,8-torusX --> 128,8-torus.XmatrxT
128-left_rightX --> 128-left_right.XmatrxT
128-spiral-8,16,128,2,1over2 --> 128-spiral-8,16,128,2,1over2.traj
128-stringcircular --> 128-stringcircular.matrxB
128-stringcircular --> 128-stringcircular.XmatrxT
128-stringX --> 128-string.XmatrxT
cylinder-128,8 --> cylinder-128,8.matrxB
string-128 --> string-128.matrxB
string_with_extras-16.matrxT --> already done

So for the Xscan opcodes, the X in the name will be part of the extension.
Shall i proceed?

**Comment by csounder** [comment]
Love it,

*- dB*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division

**Comment by tjingboem** [comment]
renamed matrices and trajectory committed- will check tomorrow if all examples still work

**Comment by csounder** [comment]
Hopefully Shengzheng’s piece is still in there.  With John’s improvements it sounds even more beautiful.

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music

**Comment by tjingboem** [comment]
- matrices and trajectory renamed 
- old matrices and trajectory removed from examples folder
- examples updated to match new names, including Shengzheng’s piece. All runs as it did before as far as i can see

I'll open a new issue for updating some examples for (x)scan opcodes as present issue is implemented.
For sure scans2.csd needs updating, but all scan examples will be looked at again.

**Comment by csounder** [comment]
Fantastic.

*- dB*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division
