### ISSUE TITLE
extra note (freeze frame) lpread & lpslot & lpinterp & lpreson & lpfreson

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#552]
Victor:

>  I think that is expected,once the value of ktimpt goes beyond the max duration in the lpc file, it holds that last frame, and what you hear is the last frame only, frozen. And you will get the warning because you have reached the final frame and the time has been truncated to it.
> 
> In my example, that final duration time is not reached and there is no message.
> 
> If the final frame is near silence, you would probably hear nothing or very little, because the frozen amplitudes are near zero.

**Comment by tjingboem** [comment]
lpread done: extra freeze note + lpanal utility

to do: lpslot

**Comment by csounder** [comment]
nice.  all these LPC examples are wonderful, clear, enlightening, and
inspiring.  thanks

*- dB*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division

**Comment by tjingboem** [comment]
Thanks!
Nice thing about these examples is that they create the analyze file and they play it nearly realtime; this also eliminates any system dependency and there is a fast result.

**Comment by csounder** [comment]
Sadly, this morning anyway, for some reason, that 'system_i' opcode is not
running correctly on the Mac - from CsoundQt.
- doing a little bit more exploring.

*- dB*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division

**Comment by csounder** [comment]
Yes.  Wonderful - and running from the terminal on the Mac M1 this morning
- just not from CsoundQt for some reason.
- or from 'run in terminal' button on CsoundQt either.  Interesting.  Do
you use CsoundQt at all with Linux?  You might try it from there.

*- dB*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division

**Comment by tjingboem** [comment]
you might want to report this to the CsoundQt developers. It is strange that it does not run from the terminal inside CsoundQt; it seems there is still a layer between the terminal and the terminal in CsoundQt preventing the example from running the system opcode. 
As you report, the examples do run from the terminal on the Mac directly.

I would expect that all our examples that do work from the terminal, should work from the terminal in CsoundQt.   
(CsoundQt never worked for me on Linux and i simply stopped trying...)

We make and check all examples with Visual Studio Code. I have never noticed that an example that runs from VSC does not run in a terminal like bash etc.

**Comment by csounder** [comment]
I will report this as a bug to the CsoundQt team.  It is odd.

*- dB*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division

**Comment by tjingboem** [comment]
wouldn't it be wonderful if all examples do work from the or a terminal in CsoundQt? That would be a win win situation.

**Comment by tjingboem** [comment]
lpinterp will get the same example as for lpslot

**Comment by tjingboem** [comment]
lpfreson with limiter:

```
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac  --limiter=0.95   ;;;realtime audio out, limit loud pops
;-iadc    ;;;uncomment -iadc if realtime audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o lpfreson.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1
;do not use -a option when analyzing "fox.wav" with lpfreson as
;it needs a filter coefficient type of file
ires  system_i 1,{{ lpanal -p40 -h200 -P50  -Q15000 -v1 fox.wav fox_coef.lpc }}

instr 1

ilen  filelen "fox.wav"	                  ; length of soundfile
prints "fox.wav = %f seconds\\n",ilen

ktime line 0, p3, p4
krmsr,krmso,kerr,kcps lpread ktime,"fox_coef.lpc"
krmso = krmso*.00001			      ; low volume
asig  buzz krmso, kcps, int(sr/2/kcps), 1 ; max harmonics without aliasing
aout  lpfreson asig, p5                   ; Pole file not supported!!
      outs aout, aout

endin
</CsInstruments>
<CsScore>
; sine
f1 0 4096 10 1
;          dur    ratio
i 1 0 2.8   1       1   ; first words   
i 1 4 2.8   1       .5  ; same, but lower ratio
i 1 8 2.8   2.8     1   ; whole sentence

e
</CsScore>
</CsoundSynthesizer>
```

**Comment by tjingboem** [comment]
funny to see that lpreson- in contrast to lpfreson- takes both poles filter and filter coefficient files. But then you can't change the ratio as you can with lpfreson.

Like the famous dutch football player Johan Cruijff says:" every advantage has its disadvantage..."
```

<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac  --limiter=0.95   ;;;realtime audio out, limit loud pops
;-iadc    ;;;uncomment -iadc if realtime audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o lpreson.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1

ires1  system_i 1,{{ lpanal -a -p40 -h200 -P50  -Q15000 -v1 fox.wav fox_poles.lpc }}  ; pole filter file      
ires2  system_i 1,{{ lpanal -p40 -h200 -P50  -Q15000 -v1 fox.wav fox_coeff.lpc }}     ; filter coefficient file

instr 1

ilen  filelen "fox.wav"	                  ; length of soundfile
prints "fox.wav = %f seconds\\n",ilen

ktime line 0, p3, p4
krmsr,krmso,kerr,kcps lpread ktime,"fox_poles.lpc"
krmso = krmso*.00001			      ; low volume
asig  buzz krmso, kcps, int(sr/2/kcps), 1 ; max harmonics without aliasing
aout  lpreson asig                        ; Pole file not supported!!
      outs aout, aout
endin

instr 2

ktime line 0, p3, p4
krmsr,krmso,kerr,kcps lpread ktime,"fox_coeff.lpc"
krmso = krmso*.00001			      ; low volume
asig  buzz krmso, kcps, int(sr/2/kcps), 1 ; max harmonics without aliasing
aout  lpreson asig                        ; Pole file not supported!!
      outs aout, aout
endin

</CsInstruments>
<CsScore>
; sine
f1 0 4096 10 1
s
;          dur
i 1 0 2.8   1   ; first words of fox_poles.lpc 
i 1 4 2.8   2.8 ; whole sentence
s
i 2 0 2.8   1   ; first words of fox_coeff.lpc  
i 2 4 2.8   2.8 ; whole sentence

e
</CsScore>
</CsoundSynthesizer>
```

**Comment by tjingboem** [comment]
replacement for lpreson-2.csd, where we  get a nice vocoder effect

```
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac  --limiter=0.95   ;;;realtime audio out & limit loud pops
;-iadc    ;;;uncomment -iadc if realtime audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o lpreson-2.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1

; by Menno Knevel - 2021
;works with or without -a option when analyzing "fox.wav" from the manual
;both options sound a little different
ires  system_i 1,{{ lpanal -a -p40 -h200 -P50  -Q15000 -v1 fox.wav fox_poles.lpc }}  ; pole filter file

instr 1

ilen   filelen "fox.wav"	;length of soundfile 1
prints "fox.wav = %f seconds\\n",ilen

ktime  line 0, p3, ilen
krmsr,krmso,kerr,kcps lpread ktime,"fox_poles.lpc"
krmso  *= .0001             ; scale amplitude
asig   diskin2	"flute.aiff", p4     ; use pitch deifferences from the flute
asig   *= krmso             ; & use the scaled back "krmso"
aout   lpreson asig
ares   balance aout, asig
       outs ares, ares

endin
</CsInstruments>
<CsScore>
s
;           pitch
i 1 0 2.8     1
i 1 3 2.8     1.5
s
i 1 0 2.8     1      ; chord
i 1 0 2.8     .7
i 1 0 2.8     1.3
e
</CsScore>
</CsoundSynthesizer>
```

**Comment by csounder** [comment]
Nice.

Some serious samples out of range in the first two, but all 'classic' LPC
sounds and the final vocoder version with fox and flute is a very nice
'conclusion'.
- inspiring.

-R


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division

**Comment by tjingboem** [comment]
the filter coefficient type of LPC can create short and loud pops- by default the limiter is on ( --limiter=0.95). The overall volume is decent however.
Could try and see if balance helps in these cases...

**Comment by tjingboem** [comment]
lpfreson example with balance 2 + limiter. Still extreme amplitude pops, but manageable

```
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac  --limiter=0.95   ;;;realtime audio out, limit loud pops
;-iadc    ;;;uncomment -iadc if realtime audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o lpfreson.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1

; by Menno Knevel - 2021
;do not use -a option when analyzing "fox.wav" with lpfreson as
;it needs a filter coefficient type of file
ires  system_i 1,{{ lpanal -p50 -h200 -P50  -Q15000 -v1 fox.wav fox_coef.lpc }}

instr 1

ilen  filelen "fox.wav"	                  ; length of soundfile
prints "fox.wav = %f seconds\\n",ilen
aref  diskin "fox.wav", 1                 ; don't play this, but use this as an amplitude reference

ktime line 0, p3, p4
krmsr,krmso,kerr,kcps lpread ktime,"fox_coef.lpc"
krmso *= .000007			              ; scale amplitude
asig  buzz krmso, kcps, int(sr/2/kcps), 1 ; max harmonics without aliasing
aout  lpfreson asig, p5                   ; Pole file not supported!!
abal  balance2 aout, aref                 ; use amplitude of diskin as reference       
      outs abal, abal

endin
</CsInstruments>
<CsScore>
; sine
f1 0 4096 10 1
;          dur    ratio
i 1 0 2.8   1       1   ; first words   
i 1 4 2.8   1       .5  ; same, but lower ratio
i 1 8 2.8   2.756   1   ; whole sentence
i 1 12 2.8  2.756   2   ; same, but higher ratio

e
</CsScore>
</CsoundSynthesizer>
```

**Comment by tjingboem** [comment]
same for instr 2 of lpreson

```
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac  --limiter=0.95   ;;;realtime audio out, limit loud pops
;-iadc    ;;;uncomment -iadc if realtime audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o lpreson.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1

; by Menno Knevel - 2021

ires1  system_i 1,{{ lpanal -a -p40 -h200 -P50  -Q15000 -v1 fox.wav fox_poles.lpc }}  ; pole filter file      
ires2  system_i 1,{{ lpanal    -p40 -h200 -P50  -Q15000 -v1 fox.wav fox_coeff.lpc }}  ; filter coefficient file

instr 1

ilen  filelen "fox.wav"	                  ; length of soundfile
prints "fox.wav = %f seconds\\n",ilen

ktime line 0, p3, p4
krmsr,krmso,kerr,kcps lpread ktime,"fox_poles.lpc"
krmso *= .000007			  ; scale amplitude
asig  buzz krmso, kcps, int(sr/2/kcps), 1 ; max harmonics without aliasing
aout  lpreson asig                        ; Pole file not supported!!
      outs aout, aout
endin

instr 2

aref  diskin "fox.wav", 1                 ; don't play this, but use this as an amplitude reference
ktime line 0, p3, p4
krmsr,krmso,kerr,kcps lpread ktime,"fox_coeff.lpc"
krmso *= .000007			      ; scale amplitude
asig  buzz krmso, kcps, int(sr/2/kcps), 1 ; max harmonics without aliasing
aout  lpreson asig                        ; Pole file not supported!!
abal  balance2 aout, aref                 ; use amplitude of diskin as reference       
      outs abal, abal
endin

</CsInstruments>
<CsScore>
; sine
f1 0 4096 10 1
s
;          dur
i 1 0 2.8   1      ; first words of fox_poles.lpc 
i 1 4 2.8   2.756  ; whole sentence
s
i 2 0 2.8   1      ; first words of fox_coeff.lpc  
i 2 4 2.8   2.756  ; whole sentence

e
</CsScore>
</CsoundSynthesizer>
```

**Comment by tjingboem** [comment]
2nd vocoder chord example for lpreson

```
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac  --limiter=0.95   ;;;realtime audio out & limit loud pops
;-iadc    ;;;uncomment -iadc if realtime audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o lpreson-2.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1

; by Menno Knevel - 2021
;works with or without -a option when analyzing "fox.wav" from the manual
;both options sound a little different
ires  system_i 1,{{ lpanal -a -p40 -h200 -P50  -Q15000 -v1 fox.wav fox_poles.lpc }}  ; pole filter file

instr 1

ilen   filelen "fox.wav"	;length of soundfile 1
prints "fox.wav = %f seconds\\n",ilen

ktime  line 0, p3, ilen
krmsr,krmso,kerr,kcps lpread ktime,"fox_poles.lpc"
krmso  *= .000085             ; scale amplitude
asig   diskin2	"flute.aiff", p4     ; use pitch deifferences from the flute
asig   *= krmso             ; & use the scaled back "krmso"
aout   lpreson asig
ares   balance aout, asig
       outs ares, ares

endin
</CsInstruments>
<CsScore>
s 
;             pitch
i 1 0 2.756     1
i 1 3 2.756     1.5
s
i 1 0 2.756     1      ; chord
i 1 0 2.756     .7
i 1 0 2.756     1.3
e
</CsScore>
</CsoundSynthesizer>
```

**Comment by csounder** [comment]
Better.

Wondering? Could the pops be a result of the amplitude of the source being
too high.
- I always try to keep my sources down -3dB or -6dB prior to processing but
it seems that you have done this with the sources.


*- dB*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division

**Comment by tjingboem** [comment]
thanks for checking these examples. An all examples- great to have feedback, thanks.

The pops exist when the lpc file is a filter coefficient file only. Victor explained this recently that the filter poles file (an extra layer, use the -a option) are far more stable. The manual says:
"When lpread / lpreson are used with pole files, automatic stabilization is performed and the filter should not get wild."

**Comment by csounder** [comment]
great.  I have been going over all your fantastic examples.
- I am especially inspired by your ATSread-2 (the arpeggio stuff is
delicious!)

Maybe include the -a options in your examples as recommended by Victor?
(or do you already?)
- you probably do.

Appreciate all this inspiring work.

*-R*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division

**Comment by tjingboem** [comment]
The ATSread-2  example is from Joachim :-)

My approach is a bit different:
I try to get to the basics for every example, not really to do 'nice things' with them. But showing the basic idea for their existence... 

lpfreson does not work with -a option (stable)
lpreson works with -a (stable) and without (not stable)
lpread works with -a (stable) and without (not stable)
lpinterp/lpslot works with -a (stable) only

I have no idea why this is, but this is what i found when experimenting.

**Comment by csounder** [comment]
You are doing a lot of 'nice things' with the examples - and showing them
working, and working well - is an incredible inspiration


*-R*

**Comment by tjingboem** [comment]
thanks. It is up to the user to do some musical things with the opcodes, and, although i have not checked yet, ATSread-2.csd might get renamed to ATSread-musical.csd?
For now i will close this issue as i think i have covered all lpanal opcodes with decent, modern examples.
If you or your students find some issues, please report :-)
