### ISSUE TITLE
add Visual Studio Code

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#557]
as a frontend for Csound on https://csound.com/manual/OviewFrontEnds.html

**Comment by tjingboem** [comment]
and remove Winsound from that page.
I do not seem to have Winsound installed and is FLTK based it seems.

**Comment by csounder** [comment]
Yes, remove Winsound.
- It has been many many years since Winsound was running.
- I do think that is FLTK-based.
And...
- A google search reveals that there is a name conflict because there is a
Python App for playing sound (not for playing Csound) call Winsound

*- dB*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division

**Comment by tjingboem** [comment]
I will remove it.

And i will add Visual Studio Code and its Csound extension.
Due to my English being far from perfect, i will make a draft text for VSC and ask you to check if the English is okay?
I will post it here soon.

**Comment by csounder** [comment]
Happy to read it over and give you feedback.

*- R*

**Comment by tjingboem** [comment]
1st attempt text VSC, partly copied:
"Visual Studio Code is a tool that combines the simplicity of a code editor with what developers need for the core edit-build-debug cycle. A csound-vscode-plugin with syntax highlighting, developed by Steven Yi, is available."

**Comment by AsterixMusic** [comment]
I think could be better to add the link to the Csound plugin in VSCode Marketplace:

https://marketplace.visualstudio.com/items?itemName=kunstmusik.csound-vscode-plugin

**Comment by tjingboem** [comment]
yes, good one. i will add this.

"Visual Studio Code is a tool that combines the simplicity of a code editor with what developers need for the core edit-build-debug cycle. Homepage: https://code.visualstudio.com/. A csound-vscode-plugin with syntax highlighting, developed by Steven Yi and Stephen Kyne, is available here: https://marketplace.visualstudio.com/items?itemName=kunstmusik.csound-vscode-plugin "

**Comment by tjingboem** [comment]
done

**Comment by csounder** [comment]
Nice and... important to know about as well!

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music
