### ISSUE TITLE
opcode now part of plugin repo

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#582]
mention on manual pages for all plugin opcodes the new repo:

This opcode is part of the plugin repository. This has to be installed separately. The plugin repository can be found here: https://github.com/csound/plugins

**Comment by csounder** [comment]
Nice

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music

**Comment by tjingboem** [comment]
- [ ] Ableton
- [ ] chua
- [ ] cuda
- [ ] faust
- [ ] hdf5
- [ ] image
- [ ] jackops
- [ ] algebra
- [ ] mp3
- [ ] opencl
- [ ] glove
- [ ] py
- [ ] stk
- [ ] web
- [ ] wii
- [ ] widgets

**Comment by tjingboem** [comment]
all is done, except for mp3out and opencl as they do not have manual pages for different reasons
