### ISSUE TITLE
Mean value for exprand wrong in manual

### ISSUE THREAD

**Issue by ReinerZorn** [csound/manual#607]
The documentation of exprand at [https://csound.com/docs/manual/exprand.html](url) reads

> The probablity density function of an exponential distribution is an exponential curve, whose mean is 0.69515/lambda.

This seemed strange to me because the average of x for an exponential distribution lambda * exp( -lambda * x ) is 1/lambda and I don't see where the factor 0.69515 should come from. Indeed a test with the attached csound file indicates that the average is 1/lambda.

[exprand_test.zip](https://github.com/csound/manual/files/7776871/exprand_test.zip)

**Comment by jpffitch** [comment]
Those quoations are direc from Dodge and Jerse, p347 in seconfd edition. 
I do see an error in the equation in 11.1B(4)

Anyone know were the 0.69314 coes from?

**Comment by jpffitch** [comment]
Reading the code csound does not have the same algorithm as Dodge & Jerse.

Whatever it should say the code does not correspond to the manual.

Hum.....

**Comment by vlazzarini** [comment]
the eq in the book is wrong, missing e, and the text mentions 0.69315/lambda as the mean (not .69515). That's also wrong, because as the op rightly says the mean is 1/lambda. The median is log(2)/lambda, and 0.69315 is an approximation of log(2). So we should correct the manual with that.

I suspect the code is ok, but we'll check.

**Comment by jpffitch** [comment]
I think the code is wrond as it multiplies by lambda not divides.  Average 
is lamgada not 1/lambda

**Comment by vlazzarini** [comment]
In the book it's log(u)/lambda, isn't that the right thing?

**Comment by vlazzarini** [comment]
I see. The code is wrong.

**Comment by jpffitch** [comment]
The correct fornmula is log(u)/lambda but csound calculates 
log(u)*lambdaa, so average is lambda and median log2 * lambda

I noticed it was wrong in v3.30 where it calculates log(u)lambda/10 
for unknown reasons.

We can leave it (for backwards compatability) and document the paraeter as 
1/lambda in common usage

**Comment by vlazzarini** [comment]
that seems to me the correct way to go.

**Comment by jpffitch** [comment]
Manual changed
