### ISSUE TITLE
ATSaddnz - errors in example.csd - "no noise"

### ISSUE THREAD

**Issue by boulangerlabs** [csound/manual#61]
SECTION 1:
new alloc for instr 1:
file beats.ats (243680 bytes) loaded into memory
INIT ERROR in instr 1: ATSADDNZ: This file type contains no noise
asig	ATSaddnz	ktime	"beats.ats"	1	24	1	
	  B  0.000 - note deleted.  i1 had 1 init errors
Score finished in csoundPerformKsmps().
inactive allocs returned to freespace
end of score.		   overall amps:  0.00000  0.00000
	   overall samples out of range:        0        0
1 errors in performance
Elapsed time at end of performance: real: 0.016s, CPU: 0.009s
closing device
0 2048 sample blks of 64-bit floats written to dac

**Comment by jpffitch** [comment]
Example replaced
