### ISSUE TITLE
opcode intypes

### ISSUE THREAD

**Issue by lsalgueiro** [csound/manual#610]
Opcode accepts a fsig as an intype. This is not made clear by the manual, and maybe it could be; I was a bit tripped up before deciding to try it. Perhaps there are other possible types missing as well.

**Comment by joachimheintz** [comment]
obviously referring to the list (zable) in
https://csound.com/docs/manual/opcode.html

**Comment by tjingboem** [comment]
it would be nice to have an example using fsig as an intype as well...

**Comment by tjingboem** [comment]
Joachims pull request has been apllied.
I'll leave this issue open; at some point i think it would be good to have an example for this particular use.

**Comment by lsalgueiro** [comment]
How about something like

```<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac    ;;;realtime audio out
;-iadc    ;;;uncomment -iadc if realtime audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o opcode_example.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
0dbfs = 1
nchnls = 2

opcode Transpose, a, afk
 // Transpose a monophonic input signal through FFT.
 // p4 = transposition in semitones
 
 ain, fsig, kInterval xin
 
 fScaled pvscale fsig, semitone(kInterval)
 aTransposed pvsynth fScaled
 
 xout aTransposed 
endop

instr 1
 a1 diskin2 "fox.wav"
 fsig pvsanal a1, 1024, 256, 1024, 1
 aTransposed Transpose a1, fsig, p4

 out aTransposed
endin

</CsInstruments>
<CsScore>
i1 0 3 0
i1 . . 7
i1 . . 12
</CsScore>
</CsoundSynthesizer>```

**Comment by tjingboem** [comment]
exactly something like that!
Changed to outs in instr. 1 & moved the comments a bit. Also made text a bit more compact so it will take a bit less space on the manual page.

Can i add your name as creator of this example?
It would be like this:

```
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac    ;;;realtime audio out
;-iadc    ;;;uncomment -iadc if realtime audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o opcode_example.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
0dbfs = 1
nchnls = 2

; example by Luis Salgueiro

opcode Transpose, a, afk    ; transpose a monophonic input signal through FFT.
 ain, fsig, kInterval xin
 fScaled pvscale fsig, semitone(kInterval)
 aTransposed pvsynth fScaled
 xout aTransposed 
endop

instr 1
 a1 diskin2 "fox.wav"
 fsig pvsanal a1, 1024, 256, 1024, 1
 aTransposed Transpose a1, fsig, p4   ; p4 = transposition in semitones
 outs aTransposed, aTransposed
endin

</CsInstruments>
<CsScore>
i1 0 3 0
i1 . . 7
i1 . . 12
</CsScore>
</CsoundSynthesizer>
```

**Comment by lsalgueiro** [comment]
Yes, of course, by all means, great!

**Comment by joachimheintz** [comment]
thanks menno!

but please note that i asked last night victor on the csound list about 
the OUTtype, because i think f-sigs are only possible for INtype.  we 
should not release the manual if my commit was half-wrong.

**Comment by tjingboem** [comment]
okay- i was not aware of that.
You are talking about the f Type here:
![Screenshot from 2022-01-30 17-26-56](https://user-images.githubusercontent.com/6670911/151708100-cda56cb3-3a9b-447e-b490-bab7a646b0d4.png)

I hope this gets clear before release, or else it is better to take this f outtype out of the manual before publishing.

**Comment by joachimheintz** [comment]
yes exactly that's the outtype table which i mean.
the example from luis covers the f-sig as intype, and that seems allright.

**Comment by tjingboem** [comment]
The new example from Luis can be found here: https://csound.com/manual/opcode.html

I just saw your message in Csnd-dev. The f outtype is, at the moment, part of this manual page, and awaits a conclusion...

**Comment by joachimheintz** [comment]
hi menno -

if you like, here is a simple example for the f-sig output which victor 
just fixed.  perhaps add to luis' example?

best -
	joachim


<CsoundSynthesizer>
<CsOptions>
-odac
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs = 1

//example by joachim heintz

opcode Stretch,f,ik
  iTab, kSpeed xin
  fStretch pvstanal kSpeed, 1, 1, iTab
  xout fStretch
endop

giFox ftgen 0, 0, 0, 1, "fox.wav", 0, 0, 0

instr 1
  fStretch Stretch giFox, linseg:k(1,p3,0)
  aStretch pvsynth fStretch
  outall aStretch
endin

</CsInstruments>
<CsScore>
i 1 0 5
</CsScore>
</CsoundSynthesizer>

**Comment by tjingboem** [comment]
yes it would be nice to have this example integrated into the example of Luis. But i do not have the time to make it so, perhaps later in the evening...too late for 6.17??
If you can do it, and rename your instr to instr 2, and copypaste this into Luis example?

**Comment by joachimheintz** [comment]
sure =)

<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac    ;;;realtime audio out
;-iadc    ;;;uncomment -iadc if realtime audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o opcode_example.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
0dbfs = 1
nchnls = 2

; example by Luis Salgueiro and joachim heintz

opcode Transpose, a, fk    ; transpose a monophonic input signal through 
FFT.
  fsig, kInterval xin
  fScaled pvscale fsig, semitone(kInterval)
  aTransposed pvsynth fScaled
  xout aTransposed
endop

opcode Stretch,f,ik
  iTab, kSpeed xin
  fStretch pvstanal kSpeed, 1, 1, iTab
  xout fStretch
endop

giFox ftgen 0, 0, 0, 1, "fox.wav", 0, 0, 0

instr 1
  aSnd diskin2 "fox.wav"
  fSnd pvsanal aSnd, 1024, 256, 1024, 1
  aTransposed Transpose fSnd, p4   ; p4 = transposition in semitones
  outall aTransposed/2
endin

instr 2
  fStretch Stretch giFox, transeg:k(1,p3,-3,0)
  aStretch pvsynth fStretch
  outall aStretch
endin

</CsInstruments>
<CsScore>
i1 0 3 0
i1 . . 7
i1 . . 12
i2 3 8
</CsScore>
</CsoundSynthesizer>

**Comment by tjingboem** [comment]
i rebuild Csound, checked the example and committed it. Nice to have an f in and out type example on that page.
I hope it is part of 6.17 or perhaps it is too late?? We'll see
Thanks Joachim, Luis for this!
