### ISSUE TITLE
WARNING: ATSCROSS: time pointer out of range, truncating to last frame  WARNING: ATSBUFREAD: time pointer out of range, truncating to last frame

### ISSUE THREAD

**Issue by boulangerlabs** [csound/manual#62]
Should fix these settings.  There should not be warnings in the example files from the manual.  Dr.B. 

  0: dac0 (Built-in Output)
PortAudio: selected output device 'Built-in Output'
writing 2048 sample blks of 64-bit floats to dac 
SECTION 1:
ftable 1:
new alloc for instr 1:
file fox.ats (985312 bytes) loaded into memory
file beats.ats (243680 bytes) loaded into memory
WARNING: ATSCROSS: time pointer out of range, truncating to last frame

WARNING: ATSBUFREAD: time pointer out of range, truncating to last frame

B  0.000 ..  4.000 T  4.000 TT  4.000 M:  1.01330  1.01330
	 number of samples out of range:        8        8
Score finished in csoundPerformKsmps().
inactive allocs returned to freespace
end of score.		   overall amps:  1.01330  1.01330
	   overall samples out of range:        8        8
0 errors in performance
Elapsed time at end of performance: real: 4.219s, CPU: 0.309s
closing device
173 2048 sample blks of 64-bit floats written to dac

**Comment by jpffitch** [comment]
transferred to csound as generic
