### ISSUE TITLE
replace bad and add good samples part 1: beats

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#628]
**replace _beats.wav_ with _drumsMlp.wav_**: this modern sounding drum sample has the advantage of having the same 120 BPM and duration 2 seconds, and is hopefully an easy "drop in" replacement for _beats.wav._

- [x] add drumsMlp.ogg to: ftsr.csd, gen01.csd (change images), mp3in.csd, mp3scal.csd
- [x] add drumsMlp.mp3 to: ftsr.csd, gen01.csd (change images)
- [x] examples/ATSaddnz.csd
- [x] examples/ATSbufread.csd 
- [x] examples/ATScross.csd
- [x] examples/ATSpartialtap.csd
- [x] examples/ATSreadnz.csd
- [x] examples/ATSsinnoi.csd
- [x] examples/FLbutton.csd
- [x] examples/FLexecButton.csd
- [x] examples/babo.csd
- [x] examples/babo_expert.csd
- [x] examples/bbcutm.csd
- [x] examples/binit.csd
- [x] examples/compress.csd
- [x] examples/compress2.csd
- [x] examples/cvanal.csd
- [x] examples/dam.csd
- [x] examples/dam_expanded.csd
- [x] examples/dcblock.csd
- [x] examples/dcblock2.csd
- [x] examples/delay1.csd
- [x] examples/diskin.csd
- [x] examples/diskin2.csd
- [x] examples/downsamp.csd
- [x] examples/dssiactivate.csd  --> csound command: Segmentation fault
- [x] examples/dssiaudio.csd  --> csound command: Segmentation fault
- [x] examples/dssictls.csd  --> Plugin 'C* Compress - Compressor and saturating limiter' has 1 audio input ports.
- [x] examples/dssiinit.csd
- [x] examples/dssiplay_mono.csd --> csound command: Segmentation fault
- [x] examples/dssiplay_stereo.csd
- [x] examples/filesr.csd
- [x] examples/follow.csd
- [x] examples/follow2.csd
- [x] examples/fout_ftable.csd
- [x] examples/fout_poly.csd
- [x] examples/ftaudio.csd
- [x] examples/ftgen-2.csd
- [x] examples/ftlen.csd
- [x] examples/gen01.csd
- [x] examples/gen01computed.csd
- [x] examples/gen28.csd
- [x] examples/grain.csd
- [x] examples/hilbert.csd
- [x] examples/hrtfer.csd
- [x] examples/liveconv.csd
- [x] examples/locsend_quad.csd
- [x] examples/locsend_stereo.csd
- [x] examples/locsig_quad.csd
- [x] examples/locsig_stereo.csd
- [x] examples/lpcfilter-2.csd
- [x] examples/lpcfilter.csd
- [x] examples/lphasor.csd
- [x] examples/lposcil.csd
- [x] examples/lposcil3.csd
- [x] examples/lposcila.csd
- [x] examples/moogvcf2.csd
- [x] examples/multitap.csd
- [x] examples/nestedap.csd
- [x] examples/nreverb_ftable.csd
- [x] examples/peak.csd
- [x] examples/pitch.csd
- [x] examples/pitchamdf.csd
- [x] examples/plate.csd
- [x] examples/pvbufread.csd
- [x] examples/pvsbufread.csd
- [x] examples/pvsbufread2.csd
- [x] examples/pvsdemix.csd
- [x] examples/pvsgain.csd
- [x] examples/pvsifd.csd
- [x] examples/pvsinit.csd
- [x] examples/pvsmix.csd
- [x] examples/pvstrace.csd
- [x] examples/scoreline.csd
- [x] examples/scoreline_i.csd
- [x] examples/sndinfo.csd
- [x] examples/sndloop.csd
- [x] examples/space_quad.csd
- [x] examples/space_stereo.csd
- [x] examples/spsend_quad.csd
- [x] examples/spsend_stereo.csd
- [x] examples/src_conv.csd
- [x] examples/strcpyk.csd
- [x] examples/strget.csd
- [x] examples/strindexk.csd
- [x] examples/syncloop.csd
- [x] examples/tableikt.csd
- [x] examples/tablexkt.csd
- [x] examples/tempest.csd
- [x] examples/tone.csd
- [x] examples/tonex.csd
- [x] examples/tradsyn.csd
- [x] examples/trcross.csd
- [x] examples/trfilter.csd
- [x] examples/trlowest.csd
- [x] examples/trsplit.csd
- [x] examples/tvconv.csd
- [x] examples/valpass-2.csd
- [x] examples/vbap.csd
- [x] examples/vbap4.csd
- [x] examples/vbap4move.csd
- [x] examples/vbapg.csd
- [x] examples/vbapgmove.csd
- [x] examples/vbaplsinit.csd
- [x] examples/vbapmove.csd
- [x] examples/vcopy.csd
- [x] examples/vdelayxq.csd
- [x] examples/vdelayxwq.csd
- [x] examples/vmult.csd
- [x] examples/vtablewa.csd
- [x] examples/vtablewk.csd
- [x] examples/wguide2.csd
- [x] opcodes/babo.xml
- [x] opcodes/bbcutm.xml
- [x] opcodes/dam.xml
- [x] opcodes/dcblock.xml
- [x] opcodes/dcblock2.xml
- [x] opcodes/diskin.xml
- [x] opcodes/diskin2.xml
- [x] opcodes/filesr.xml
- [x] opcodes/flbutton.xml
- [x] opcodes/follow.xml
- [x] opcodes/follow2.xml
- [x] opcodes/fout.xml
- [x] opcodes/ftlen.xml
- [x] opcodes/grain.xml
- [x] opcodes/hilbert.xml
- [x] opcodes/hrtfer.xml
- [x] opcodes/nestedap.xml
- [x] opcodes/nreverb.xml
- [x] opcodes/peak.xml
- [x] opcodes/tempest.xml
- [x] scoregens/gen01.xml

**Comment by tjingboem** [comment]
the work is done.
I _think_  i replaced all beats.wav, also beats.ogg and mp3. Also the manual pages are adjusted.
Please reports any issues.

Thanks goes to @tgrey Kevin for making a program that helps in searching and replacing!

**Comment by csounder** [comment]
Wonderful Dr. Richard BoulangerProfessorElectronic Production and DesignBerklee College of MusicOn Feb 2, 2023, at 1:59 PM, Menno Knevel ***@***.***> wrote:﻿
the work is done.
I think  i replaced all beats.wav, also beats.ogg and mp3. Also the manual pages are adjusted.
Please reports any issues.
Thanks goes to @tgrey Kevin for making a program that helps in searching and replacing!
