### ISSUE TITLE
replace bad and add good samples: the fox stays but

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#629]
there are a lot of foxes in the manual. Sometimes it might be nice/better to use another mono sample for an example

**Comment by AsterixMusic** [comment]
I think "quick brown fox" it's important because contains all the letters of the alphabet.
Maybe for vocoder examples, for spectral processing we can continue to use this sentence.

**Comment by tjingboem** [comment]
yes it is important to decide what example uses the fox, the marimba or the singing Female.
Every proposal will be posted here to discuss.
(see https://github.com/csound/manual/issues/627 for the new samples).

But first i'll be checking to replace _kickroll, mary_ and _beats_.

**Comment by csounder** [comment]
I do like Quick Brown Fox.  It is decent and research-oriented, but imagine
if you had a quote by Max Mathews, Bob Moog, John Cage, Brian Eno, Wendy
Carlos, or Laurie Anderson, ???

- it might inspire more 'creative' ideas.

*- Dr.B*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division

**Comment by tjingboem** [comment]
can you elaborate on "- it might inspire more 'creative' ideas."?

**Comment by csounder** [comment]
Students might be inspired by the suggestions in the quotes themselves
Students might be inspired by the quote to compose pieces using these words
and voices

*- Dr.B*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division

**Comment by csounder** [comment]
When John Cage says, "invade areas where nothing is definite," - that is
pretty inspiring.
When Max Mathews says something about how, with a computer one could make
any sound that they imagine

stuff like that

*- Dr.B*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division

**Comment by tjingboem** [comment]
i like that as alternatives for the fox. That is:
the fox stays but sometimes replace by the quote from John Cage or Max Matthews.
Do you have those quotes in good quality?

**Comment by csounder** [comment]
I do.  I will find them for you tonight or tomorrow - teaching now.  Have a
great day.

*- Dr.B*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division

**Comment by tjingboem** [comment]
This is the quote from Max Mathews to be used as an alternative and (sometimes) replacement for _fox_ or _beats_, depending on the example.
The quote has a duration of about 16 seeconds, 16 bits/44.1kHz.

[Mathews.wav.zip](https://github.com/csound/manual/files/9336085/Mathews.wav.zip)

**Comment by csounder** [comment]
nice.

*- Dr.B*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division

**Comment by tjingboem** [comment]
Now that _kickroll_ and _mary_ are replaced by _drumsSlp_ and _marimba/singFemale_ respectively, this issue on replacing sometimes!! the _fox_ will be combined with the issue on replacing _beats_: https://github.com/csound/manual/issues/628     

So this issue can be closed.

**Comment by csounder** [comment]
Excellent 

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music
