### ISSUE TITLE
dnoise not mentioned in manual

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#633]
on the opening page.
It does have a manual page: https://csound.com/manual/dnoise.html . This can be found before the Het_export utility.
but it should have an entry in the Utility section.

Also on https://csound.com/manual/UtilityConversion.html an entry is missing.

**Comment by csounder** [comment]
Yes.  This is where I found it, but it does seem to be in the wrong place.
And, for sure, it does need it's own page.
It is a great utility.

*- Dr.B*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division

**Comment by tjingboem** [comment]
The link to **dnoise** is back up again: https://csound.com/manual/dnoise.html

**Comment by csounder** [comment]
Excellent 

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music
