### ISSUE TITLE
envext needs new example

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#640]
due to _mary.wav_

**Comment by tjingboem** [comment]
```
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac   -m0  ;;;realtime audio out, with limiter protection
; For Non-realtime ouput leave only the line below:
; -o envext.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1

; by Menno Knevel 2022

instr 1
; analyzes sound file and outputs result to a file called "newenv"
ires1 system_i 1,{{ envext -w .05 Mathews.wav }}                  ; default settings (1024 bandoass filters)
endin

</CsInstruments>
<CsScore>

i1 0 1                   ; untreated signal

e
</CsScore>
</CsoundSynthesizer>
```

This utility does work but i do not know what to do with these values. What is the idea behind **envext**?
Is this utility outdated?

**Comment by csounder** [comment]
Not sure what this is supposed to do.
- it does not seem to be able to open the Mathews.wav file.

And, there is a spelling error on the word 'bandpass' in the comment.

*- Dr.B*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division

**Comment by tjingboem** [comment]
ah yes i forgot, here is the quote
[Mathews.wav.zip](https://github.com/csound/manual/files/9401697/Mathews.wav.zip)

This sample is now uploaded to manual/examples

**Comment by tjingboem** [comment]
This could probably go into the Historical section

**Comment by tjingboem** [comment]
example added

**Comment by csounder** [comment]
excellent.

*- Dr.B*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division
