### ISSUE TITLE
Error in wterrain2 curve equations?

### ISSUE THREAD

**Issue by ST-Music** [csound/manual#651]
These two equations appear identical to me. I'm not great at math but I assume there should be a difference between the two. Am I simply overlooking something? 
kcurve=2: limacon
        fx(t) = kx + krx * sin(t) * (cos(t) + kcurveparam)
        fy(t) = ky + kry * cos(t) * (cos(t) + kcurveparam)
kcurve=3: cornoid
        fx(t) = kx + krx * sin(t) * (cos(t) + kcurveparam)
        fy(t) = ky + kry * cos(t) * (cos(t) + kcurveparam)

**Comment by tjingboem** [comment]
imo this is a copy&paste error
but i am faaarrrr from being an expert here.

The author is Christian Bacher, but i do not know how to contact him.
Anyone knows?

**Comment by tjingboem** [comment]
Christian responded. so now the formula for cornoid is corrected
Thanks for reporting!
