### ISSUE TITLE
c2r.csd - manual example bug

### ISSUE THREAD

**Issue by boulangerlabs** [csound/manual#67]
STARTING FILE
Creating options
Creating orchestra
Creating score
rtaudio: PortAudio module enabled ... 
using blocking interface
error: syntax error, unexpected T_IDENT  (token "ifft") from file /Library/Frameworks/CsoundLib64.framework/Resources/Manual/examples/c2r.csd (1)
 line 19:
>>> kCmplx ifft <<<
Unexpected untyped word kCmplx when expecting a variable
Parsing failed due to invalid input!
Stopping on parser failure
cannot compile orchestra

**Comment by vlazzarini** [comment]
fixed example
