### ISSUE TITLE
re-organize In and Output sections of Audio and Midi

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#678]
re-organize the In and Output sections of Audio and Midi:

///Linux specific Audio & Midi ///        Mac specific Audio & Midi ///       Windows specific Audio & Midi///

PortAudio & PortMidi is the standard driver for all these platforms so info on it should be copied in all sections of the different platforms
Link to page about Jack, that is (in principle) available for all platforms https://jackaudio.org/downloads/

**Comment by tjingboem** [comment]
- [ ] separate Audio and Midi sections

- [ ] Add to all: _With PortMIDI, DEVICE is either a number for single port input, 'a' for listening to all input ports, or 'm' for mapping ports to MIDI channels above 16. In this case, device 0 uses 1-16, device 1 uses 17-32, ... device N uses (N+1)*channel. The options 'a' and 'm' are also convenient when you don't have devices as they will not generate an error._
- [ ] add list of jack midi ports

**Comment by tjingboem** [comment]
DONE

**Comment by csounder** [comment]
NiceDr. Richard BoulangerProfessorElectronic Production and DesignBerklee College of MusicOn May 31, 2024, at 2:25 AM, Menno Knevel ***@***.***> wrote:﻿
 
 
  
  done
