### ISSUE TITLE
cent - 3 p-fileds not 4

### ISSUE THREAD

**Issue by boulangerlabs** [csound/manual#68]
new alloc for instr 1:
WARNING: instr 1 uses 3 p-fields but is given 4
instr 1:  iroot = 440.000
B  0.000 ..  2.500 T  2.500 TT  2.500 M:  0.60000  0.60000
new alloc for instr 2:
instr 2:  iroot = 440.000
instr 2:  ifactor = 1.189
instr 2:  inew = 523.251
B  2.500 ..  5.000 T  5.000 TT  5.000 M:  0.60000  0.60000
instr 2:  iroot = 440.000
instr 2:  ifactor = 2.000
instr 2:  inew = 880.000
B  5.000 ..  7.000 T  7.000 TT  7.000 M:  0.60000  0.60000
Score finished in csoundPerformKsmps().
inactive allocs returned to freespace
end of score.		   overall amps:  0.60000  0.60000
	   overall samples out of range:        0        0

**Comment by jpffitch** [comment]
Fixef
