### ISSUE TITLE
chuap.csd - uses 9 but given 25

### ISSUE THREAD

**Issue by boulangerlabs** [csound/manual#70]
new alloc for instr 1:
WARNING: instr 1 uses 19 p-fields but is given 25
ChuasOscillatorPiecewise::init: L: -0.007079  R0: 0.000016  C2: 100.000000  G: 1.000000  Ga: -0.999553  Gb: -1.000284  E: 1.000000  C1: -0.002222  M(1): 3.870756  M(2): 0.003089  M(3): -2.362016 step: 0.000000

**Comment by jpffitch** [comment]
Referred to author

**Comment by gogins** [comment]
Removed warning!
