### ISSUE TITLE
compilecsd.csd - uses 5 p-fields, given 3

### ISSUE THREAD

**Issue by boulangerlabs** [csound/manual#71]
STARTING FILE
Creating orchestra
Creating score
instr 1:  ires = 0.000
new alloc for instr 2:
new alloc for instr 2:
WARNING: instr 2 uses 5 p-fields but is given 3
B  0.000 ..  1.000 T  1.000 TT  1.000 M:  0.20000
B  1.000 ..  3.000 T  3.000 TT  3.000 M:  0.20000
Score finished in csoundPerformKsmps().
inactive allocs returned to freespace
end of score.		   overall amps:  0.20000
	   overall samples out of range:        0

**Comment by vlazzarini** [comment]
The warning is spurious, example works perfectly.
