### ISSUE TITLE
compilestr.csd - syntax error - unexpected T_IDENT

### ISSUE THREAD

**Issue by boulangerlabs** [csound/manual#72]
audio buffered in 1024 sample-frame blocks
PortAudio V19-devel (built Sep  4 2014 22:30:30)
   0: adc0 (Built-in Microph)
PortAudio: selected input device 'Built-in Microph'
reading 2048-byte blks of shorts from adc (RAW)
   0: dac0 (Built-in Output)
PortAudio: selected output device 'Built-in Output'
writing 1024 sample blks of 64-bit floats to dac 
SECTION 1:
new alloc for instr 1:
error: syntax error, unexpected T_IDENT  (token "oscilb") line 2:
>>>a1 oscilb <<<
Unexpected untyped word a1 when expecting a variable
Parsing failed due to invalid input!
Stopping on parser failure
instr 1:  ires = -1.000
instr 1:  ires = 0.000
new alloc for instr 2:
B  0.000 ..  1.000 T  1.000 TT  1.000 M:  0.20000
B  1.000 ..  3.000 T  3.000 TT  3.000 M:  0.20000
Score finished in csoundPerformKsmps().
inactive allocs returned to freespace
end of score.		   overall amps:  0.20000
	   overall samples out of range:        0
0 errors in performance
Elapsed time at end of performance: real: 3.080s, CPU: 0.115s

**Comment by vlazzarini** [comment]
did you read the example? It is supposed to fail.
