### ISSUE TITLE
lonely opcodes

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#721]
- make a list of _'lonely'_ opcodes: opcodes without See Also category. User will not find these opcodes that easily or not at all as they are not part of such a category and are not mentioned anywhere except in the WhatsNew section
- contact and communicate with devs about this
- try and give them some love

**Comment by tjingboem** [comment]
ToDoList of _lonely_ opcodes 


- [ ] oversample, undersample, opcode, xin, xout, endop --> UDO opcodes
- [ ] elapsedcycles, elapsedtime, eventcycles, and eventtime, lastcycle
- [ ] +=  --> which category?
- [ ] !
- [ ] <<
- [ ] resonbnk --> new manual page Streaming LPC opcodes
- [ ] Model and Emulations --> link naar STK
- [ ] cell
- [ ] centroid
- [ ] cell
- [ ] centroid
- [ ] ceps
- [ ] chani sofwarebus opcodes
- [ ] compilecsd
- [ ] count
- [ ] cpumeter
- [ ] ctrlpreset opcodes 
- [ ] directory
- [ ] evalstr
- [ ] exitnow
- [ ] faust opcodes --> new manual page Faust opcodes
- [ ] farey  --> which category?
- [ ] filescal  --> which category?
- [ ] flashtxt
- [ ] fmanal
- [ ] fmax/fmin/fmod
- [ ] framebuffer
- [ ] ftsamplebank
- [ ] gtadsr
- [ ] getftargs
- [ ] getseed
- [ ] hypot
- [ ] lag
- [ ] lagud
- [ ] lufs
- [ ] median k
- [ ] metro : Instrument Control:Sensing and Control but what kind? Tempo and Sequencing?
- [ ] midifilestatus : Instrument Control:Sensing and Control but what kind?
- [ ] mp3
- [ ] msstereo : Panning and Spatialization but what kind?
- [ ] nchnls_hw
- [ ] nstance
- [ ] nstrnum
- [ ] olabuffer
- [ ] p5
- [ ] p
- [ ] part2txt
- [ ] paulstretch
- [ ] pcount
- [ ] pindex
- [ ] pitch
- [ ] pitchamdf
- [ ] plltrack
- [ ] product
- [ ] ptrack
- [ ] pvsbandwidth
- [ ] pvsceps
- [ ] pvsfromarray
- [ ] pvspitch
- [ ] pvstrace
- [ ] pvs2tab
- [ ] pwd
- [ ] qinf qnan
- [ ] readf i
- [ ] readscore
- [ ] remove
- [ ] return
- [ ] rnd
- [ ] s
- [ ] schedulek
- [ ] sequ
- [ ] select
- [ ] serial opcodes  --> new manual page
- [ ] seqtime typo
- [ ] setksmps
- [ ] signum
- [ ] splitrig
- [ ] strfromurl
- [ ] strstrip
- [ ] tabifd
- [ ] tablefilter
- [ ] tableicopy
- [ ] tableigpw
- [ ] trigexpseg
- [ ] trighold
- [ ] triglinseg
- [ ] tvconv
- [ ] vcella
- [ ] wii   --> new manual page WII opcodes
- [ ] writescratch, readscratch : Instrument Control:Sensing and Control but what kind?

**Comment by csounder** [comment]
All the lonely opcodes
Where do they all come from?
<https://genius.com/4459117/The-beatles-eleanor-rigby/All-the-lonely-people-where-do-they-all-come-from>
All the lonely opcodes
Where do they all belong?
<https://genius.com/2116202/The-beatles-eleanor-rigby/All-the-lonely-people-where-do-they-all-belong>

I could not HELP (I need somebody) myself.

*- Dr.B*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division
