### ISSUE TITLE
cpumeter.csd - syntax error, unexpected T_IDENT  (token "cpumeter")

### ISSUE THREAD

**Issue by boulangerlabs** [csound/manual#73]
Creating orchestra
Creating score
rtaudio: PortAudio module enabled ... 
using blocking interface
rtmidi: PortMIDI module enabled
error: syntax error, unexpected T_IDENT  (token "cpumeter") from file /Library/Frameworks/CsoundLib64.framework/Resources/Manual/examples/cpumeter.csd (1)
 line 18:
>>>k0   cpumeter <<<
Unexpected untyped word k0 when expecting a variable
Parsing failed due to invalid input!
Stopping on parser failure
cannot compile orchestra

**Comment by vlazzarini** [comment]
this opcode is linux only
