### ISSUE TITLE
cross2.csd - WARNING: ahh.aiff sr = 22050, orch sr = 44100.0

### ISSUE THREAD

**Issue by boulangerlabs** [csound/manual#74]
you should use other files or convert these to 44100

====
writing 2048 sample blks of 64-bit floats to dac 
SECTION 1:
ftable 1:
WARNING: ahh.aiff sr = 22050, orch sr = 44100.0
audio sr = 22050, monaural
opening AIFF infile ahh.aiff
ftable 2:
WARNING: eee.aiff sr = 22050, orch sr = 44100.0
audio sr = 22050, monaural
opening AIFF infile eee.aiff
ftable 3:
new alloc for instr 1:

**Comment by jpffitch** [comment]
Changed sample rate, but I think this is no big deal either way
