### ISSUE TITLE
ctrl21 - no example .csd in the manual

### ISSUE THREAD

**Issue by boulangerlabs** [csound/manual#76]

**Comment by tjingboem** [comment]
the reason why at the time i did not provide an example for this opcode was that there are to my knowledge no 21-bit MIDI signals. It just didn' t make it into the real live.

**Comment by vlazzarini** [comment]
Maybe you could adapt ctrl7 example by adding another two controller numbers alongside it. Similarly for ctrl7

**Comment by vlazzarini** [comment]
done.
