### ISSUE TITLE
dssiactivate - example doesn't run from the manual - where is the required dssi4cs plugin

### ISSUE THREAD

**Issue by boulangerlabs** [csound/manual#77]
STARTING FILE
Creating options
Creating orchestra
Creating score
rtaudio: PortAudio module enabled ... 
using blocking interface
rtmidi: CoreMIDI module enabled
error: syntax error, unexpected T_IDENT  (token "dssiinit") from file /Library/Frameworks/CsoundLib64.framework/Resources/Manual/examples/dssiactivate.csd (1)
 line 15:
>>>gihandle dssiinit <<<
Unexpected untyped word gihandle when expecting a variable
Parsing failed due to invalid input!
Stopping on parser failure
cannot compile orchestra

**Comment by vlazzarini** [comment]
linux onlu
