### ISSUE TITLE
dumpk examples and others that write to disk

### ISSUE THREAD

**Issue by boulangerlabs** [csound/manual#79]
as you know, you can't write to the "examples" folder on a mac without changing the permissions on the folder.  and so, manual examples such as the dumpk examples will not work from the manual without first copying them.  might be better to write to another directory? or to do something on install that sets the examples dir as a source dir (so that you can read all the included files) - and have some sort of output dir (where one could modify manual examples and, by default, safe user modified .csd files.)

**Comment by vlazzarini** [comment]
Impossible to know where to write, which arbitrary directory will allow it in a user's disk.

**Comment by jpffitch** [comment]
could it write to /tmp which seems t exist on mist (all?) systems?  Otherwise we should close this issue.
