### ISSUE TITLE
ficlose  manual example -  test1.txt file missing

### ISSUE THREAD

**Issue by boulangerlabs** [csound/manual#81]
nel 13 using instr 1
midi channel 14 using instr 1
midi channel 15 using instr 1
midi channel 16 using instr 1
0dBFS level = 1.0
INIT ERROR in instr 0: error opening file 'test1.txt'
gihand	fiopen	"test1.txt"	0	
header init errors

**Comment by jpffitch** [comment]
Works for me.  It creates the file test1.txt so you need permission to write to the directory
