### ISSUE TITLE
Gensone.csd - lots of samples out of range - is it supposed to blow the speakers?

### ISSUE THREAD

**Issue by boulangerlabs** [csound/manual#83]
-Csound version 6.06 (double samples) Sep 29 2015
midi channel 1 using instr 1
midi channel 2 using instr 2
midi channel 3 using instr 1
midi channel 4 using instr 1
midi channel 5 using instr 1
midi channel 6 using instr 1
midi channel 7 using instr 1
midi channel 8 using instr 1
midi channel 9 using instr 1
midi channel 10 using instr 1
midi channel 11 using instr 1
midi channel 12 using instr 1
midi channel 13 using instr 1
midi channel 14 using instr 1
midi channel 15 using instr 1
midi channel 16 using instr 1
0dBFS level = 1.0
0 MIDI sources in system 
MIDI device number 0 is out-of-range, not connected 
orch now loaded
audio buffered in 1024 sample-frame blocks
PortAudio V19-devel (built Sep  4 2014 22:30:30)
   0: adc0 (Built-in Microph)
PortAudio: selected input device 'Built-in Microph'
reading 4096-byte blks of shorts from adc (RAW)
   0: dac0 (Built-in Output)
PortAudio: selected output device 'Built-in Output'
writing 2048 sample blks of 64-bit floats to dac 
SECTION 1:
ftable 1:
ftable 2:
end of section 1	 sect peak amps:  0.00000  0.00000
SECTION 2:
B  0.000 ..  1.000 T  1.000 TT  1.000 M:  0.00000  0.00000
end of section 2	 sect peak amps:  0.00000  0.00000
SECTION 3:
new alloc for instr 1:
B  0.000 ..  2.000 T  2.000 TT  3.000 M:31933.8116831933.81168
	 number of samples out of range:    88044    88044
B  2.000 ..  4.000 T  4.000 TT  5.000 M:31933.8116831933.81168
	 number of samples out of range:    88040    88040
B  4.000 ..  6.000 T  6.000 TT  7.000 M:31952.7297531952.72975
	 number of samples out of range:    88039    88039
B  6.000 ..  8.000 T  8.000 TT  9.000 M:31991.1009131991.10091
	 number of samples out of range:    88049    88049
end of section 3	 sect peak amps:31991.1009131991.10091
	 number of samples out of range:   352172   352172
inactive allocs returned to freespace
SECTION 4:
new alloc for instr 2:
B  0.000 ..  2.000 T  2.000 TT 11.000 M:  0.99855  0.99855
B  2.000 ..  4.000 T  4.000 TT 13.000 M:  0.99855  0.99855
B  4.000 ..  6.000 T  6.000 TT 15.000 M:  0.99893  0.99893
B  6.000 ..  8.000 T  8.000 TT 17.000 M:  0.99981  0.99981
end of section 4	 sect peak amps:  0.99981  0.99981
Score finished in csoundPerformKsmps().
inactive allocs returned to freespace
end of score.		   overall amps:31991.1009131991.10091
	   overall samples out of range:   352172   352172
0 errors in performance
Elapsed time at end of performance: real: 17.223s, CPU: 0.520s
closing device
733 2048 sample blks of 64-bit floats written to dac

**Comment by jpffitch** [comment]
I tried to ask earlier -- what is your program?  The example in the manual looks OK running on Linux

--Csound version 6.07 (double samples) Mar 15 2016
displays suppressed
0dBFS level = 1.0
orch now loaded
audio buffered in 256 sample-frame blocks
writing 1024-byte blks of shorts to test.wav (WAV)
SECTION 1:
ftable 1:
ftable 2:
end of section 1         sect peak amps:  0.00000  0.00000
SECTION 2:
B  0.000 ..  1.000 T  1.000 TT  1.000 M:  0.00000  0.00000
end of section 2         sect peak amps:  0.00000  0.00000
SECTION 3:
new alloc for instr 1:
B  0.000 ..  2.000 T  2.000 TT  3.000 M:  0.99793  0.99793
B  2.000 ..  4.000 T  4.000 TT  5.000 M:  0.99793  0.99793
B  4.000 ..  6.000 T  6.000 TT  7.000 M:  0.99852  0.99852
B  6.000 ..  8.000 T  8.000 TT  9.000 M:  0.99972  0.99972
end of section 3         sect peak amps:  0.99972  0.99972
inactive allocs returned to freespace
SECTION 4:
new alloc for instr 2:
B  0.000 ..  2.000 T  2.000 TT 11.000 M:  0.99855  0.99855
B  2.000 ..  4.000 T  4.000 TT 13.000 M:  0.99855  0.99855
B  4.000 ..  6.000 T  6.000 TT 15.000 M:  0.99893  0.99893
B  6.000 ..  8.000 T  8.000 TT 17.000 M:  0.99981  0.99981
end of section 4         sect peak amps:  0.99981  0.99981
Score finished in csoundPerform().
inactive allocs returned to freespace
end of score.              overall amps:  0.99981  0.99981
           overall samples out of range:        0        0
0 errors in performance
Elapsed time at end of performance: real: 0.030s, CPU: 0.029s
512 1024 sample blks of shorts written to test.wav (WAV)

**Comment by jpffitch** [comment]
This is not a manual issue -- should be transferred to csound/csound

**Comment by vlazzarini** [comment]
fixed in git.
