### ISSUE TITLE
filepeak manual example - uses a soundfile that is not in the examples folder

### ISSUE THREAD

**Issue by boulangerlabs** [csound/manual#85]
rch now loaded
audio buffered in 1024 sample-frame blocks
PortAudio V19-devel (built Sep  4 2014 22:30:30)
   0: adc0 (Built-in Microph)
PortAudio: selected input device 'Built-in Microph'
reading 4096-byte blks of shorts from adc (RAW)
   0: dac0 (Built-in Output)
PortAudio: selected output device 'Built-in Output'
writing 2048 sample blks of 64-bit floats to dac 
SECTION 1:
new alloc for instr 1:
WARNING: Church.wav: no PEAK chunk was found, scanning file for maximum amplitude

Peak value in file 'Church.wav' is 0.909363 (-0.825 dB).

soundin: opened 'Church.wav':
         44100 Hz, 1 channel(s), 4920 sample frames
INIT ERROR in instr 1: error opening sound file 'Church_norm.wav'
	fout	"Church_norm.wav"	14	asig	
	  B  0.000 - note deleted.  i1 had 1 init errors
B  0.000 ..  2.000 T  2.000 TT  2.000 M:  0.00000  0.00000
new alloc for instr 2:
INIT ERROR in instr 2: soundin: Church_norm.wav: failed to open file
aout	soundin	"Church_norm.wav"	0	0	0	0	
INIT ERROR in instr 2: diskinfo cannot open Church_norm.wav
ipknew	filepeak	"Church_norm.wav"	0	

Peak value in file 'Church_norm.wav' is 0.000000 (-inf dB).

	  B  2.000 - note deleted.  i2 had 2 init errors
Score finished in csoundPerformKsmps().
inactive allocs returned to freespace
end of score.		   overall amps:  0.00000  0.00000
	   overall samples out of range:        0        0
2 errors in performance
Elapsed time at end of performance: real: 2.162s, CPU: 0.082s
closing device
87 2048 sample blks of 64-bit floats written to dac

**Comment by jpffitch** [comment]
I assume tis is just file permissions in creating output?

**Comment by jpffitch** [comment]
Checking the .csd file this requires write access to the directory.  ser error -- no action needed
