### ISSUE TITLE
fiopen - calling a non-existent .txt file (need to replace in examples folder)

### ISSUE THREAD

**Issue by boulangerlabs** [csound/manual#87]
midi channel 9 using instr 1
midi channel 10 using instr 1
midi channel 11 using instr 1
midi channel 12 using instr 1
midi channel 13 using instr 1
midi channel 14 using instr 1
midi channel 15 using instr 1
midi channel 16 using instr 1
0dBFS level = 1.0
INIT ERROR in instr 0: error opening file 'test1.txt'
gihand	fiopen	"test1.txt"	0	
header init errors

**Comment by jpffitch** [comment]
You need writeaccess to the directory to crearte the file.  User error
