### ISSUE TITLE
flashtxt - bug in example

### ISSUE THREAD

**Issue by boulangerlabs** [csound/manual#88]
audio buffered in 1024 sample-frame blocks
PortAudio V19-devel (built Sep  4 2014 22:30:30)
   0: adc0 (Built-in Microph)
PortAudio: selected input device 'Built-in Microph'
reading 2048-byte blks of shorts from adc (RAW)
   0: dac0 (Built-in Output)
PortAudio: selected output device 'Built-in Output'
writing 1024 sample blks of 64-bit floats to dac 
SECTION 1:
ftable 1:
new alloc for instr 1:
TCL/Tk
Wish couldn't read file "nsliders.tk": no such file or directory

WARNING: Buffer overrun in real-time audio input
WARNING: Buffer underrun in real-time audio output
WARNING: Buffer overrun in real-time audio input
B  0.000 ..  3.000 T  3.000 TT  3.000 M:   4000.0
Score finished in csoundPerformKsmps().
inactive allocs returned to freespace
end of score.		   overall amps:   4000.0
	   overall samples out of range:        0
0 errors in performance
Elapsed time at end of performance: real: 4.384s, CPU: 5.002s
closing device
130 1024 sample blks of 64-bit floats written to dac

**Comment by jpffitch** [comment]
nsliders.tk should be in the distribution.
