### ISSUE TITLE
add jspline & rspline to random generators page

### ISSUE THREAD

**Issue by bloodymortimer** [csound/manual#89]
Hi

I am wondering if this page ...

http://www.csounds.com/manual/html/SiggenNoise.html

should have jspline & rspline added to the list of available generators?

**Comment by bloodymortimer** [comment]
My feeling is that if the interpolating noise generators are ... noise generators, then these are, primarily, noise generators too ... they just differ in the mode of interpolation...

chears...

**Comment by jpffitch** [comment]
I have changed it in my copy -- to git when I can
