### ISSUE TITLE
section in the Csound Reference Manual for third-party opcodes

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#9]
Since the 3 Loris opcodes are no longer part of the Csound tree (since 5.15), i think they can be moved to the Deprecated Orchestra Opcodes and GEN Routines section.

Also, the Loris Opcodes text in Spectral Processing should mention that they are no longer supported.
Perhaps the word Deprecated can be placed in manual/index.html behind Spectral Processing, Loris Opcodes ?

**Comment by vlazzarini** [comment]
I think we should definitely do something about this, but these are not exactly deprecated, are they? They are third-party opcodes, so maybe we could have a section for these.

Maybe we should check the status of these opcodes with the Loris developers before deciding, though.

**Comment by tjingboem** [comment]
i was able to build Loris1.8 with Csound support:

menno@muziek:~/Documents/loris_stk_xtra_opcodes/loris-1.8$ ./configure CPPFLAGS="-I/usr/local/include/csound -DUSE_DOUBLE"
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
----- Package Name And Version -----
this is Loris 1.8
----- Program Checks -----
checking for g++... g++
checking for C++ compiler default output file name... a.out
checking whether the C++ compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for /usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking how to run the C++ preprocessor... g++ -E
checking for g77... no
checking for xlf... no
checking for f77... no
checking for frt... no
checking for pgf77... no
checking for cf77... no
checking for fort77... no
checking for fl32... no
checking for af77... no
checking for xlf90... no
checking for f90... no
checking for pgf90... no
checking for pghpf... no
checking for epcf90... no
checking for gfortran... no
checking for g95... no
checking for xlf95... no
checking for f95... no
checking for fort... no
checking for ifort... no
checking for ifc... no
checking for efc... no
checking for pgf95... no
checking for lf95... no
checking for ftn... no
checking whether we are using the GNU Fortran 77 compiler... no
checking whether  accepts -g... no
checking the maximum length of command line arguments... 1572864
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC
checking if gcc PIC flag -fPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
configure: creating libtool
appending configuration tag "CXX" to libtool
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC
checking if g++ PIC flag -fPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
(cached) (cached) checking how to hardcode library paths into programs... immediate
appending configuration tag "F77" to libtool
checking for doxygen... /usr/bin/doxygen
checking for swig... no
configure: WARNING: Cannot find SWIG. Python module cannot be built.
----- Compiler Feature Checks -----
checking size of bool... 1
checking size of char... 1
checking whether char is unsigned... no
checking size of short... 2
checking size of int... 4
checking size of long... 8
checking size of int *... 8
checking size of size_t... 8
checking size of float... 4
checking size of double... 8
checking for isfinite defined in cmath... yep
checking whether byte ordering is bigendian... no
checking for M_PI defined in cmath... yep
checking whether C++ compiler supports template member functions... yes
----- Library Checks -----
checking for library containing sin... -lm
checking for fftw_execute in -lfftw3... no
checking for fftw_create_plan_specific in -lfftw... no
configure: WARNING: Not using the FFTW library.  Infrequent non-power-of-two DFTs will be slow.
----- Language Checks -----
checking csdl.h usability... yes
checking csdl.h presence... yes
checking for csdl.h... yes
checking for csound... /usr/local/bin/csound
----- Creating Output Files -----
configure: creating ./config.status
config.status: creating src/loris.h
config.status: creating doc/Doxyfile
config.status: creating Makefile
config.status: creating doc/Makefile
config.status: creating src/Makefile
config.status: creating scripting/Makefile
config.status: creating csound/Makefile
config.status: creating test/Makefile
config.status: creating utils/Makefile
config.status: creating config.h
config.status: executing depfiles commands
----- Configuration Summary -----
FFTW support: Disabled.
Add something to CPPFLAGS and LDFLAGS to enable.
See ./configure --help.
Python support: Disabled.
Define PYTHON or add something to CPPFLAGS to enable.
See ./configure --help.
Csound support: Enabled.
To use Loris opcodes in your instruments, invoke csound with the argument:
--opcode-lib=/usr/local/lib/libloris.so
or libloris.dylib on Mac OS X
----- End Of Configuration -----

But "make" produces:

make  all-recursive
make[1]: Entering directory `/home/menno/Documents/loris_stk_xtra_opcodes/loris-1.8'
Making all in csound
make[2]: Entering directory `/home/menno/Documents/loris_stk_xtra_opcodes/loris-1.8/csound'
/bin/bash ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..   -I/usr/local/include/csound   -I../src -g -O2 -MT liblorisops_la-lorisgens5.lo -MD -MP -MF .deps/liblorisops_la-lorisgens5.Tpo -c -o liblorisops_la-lorisgens5.lo `test -f 'lorisgens5.C' || echo './'`lorisgens5.C
 g++ -DHAVE_CONFIG_H -I. -I.. -I/usr/local/include/csound -I../src -g -O2 -MT liblorisops_la-lorisgens5.lo -MD -MP -MF .deps/liblorisops_la-lorisgens5.Tpo -c lorisgens5.C  -fPIC -DPIC -o .libs/liblorisops_la-lorisgens5.o
make[2]: Leaving directory `/home/menno/Documents/loris_stk_xtra_opcodes/loris-1.8/csound'
make[1]: Leaving directory `/home/menno/Documents/loris_stk_xtra_opcodes/loris-1.8'

(I have never used Loris in a music piece, i have made quite some effort to get it to run in Csound on behalf of producing and testing the examples (that were already there) for the 3 loris opcodes.

Perhaps i am saying something less clever than avarage, but in case of  we can make use of the SDIF2AD utility, maybe improve it and use HETRO?

**Comment by gogins** [comment]
I have often wondered what to do about third party and plugin opcodes.

I agree there should be a section in the Csound Reference Manual for
third-party opcodes. I found the Loris opcodes quite useful some years ago,
and I can certainly imagine using them again.

I also think all opcodes that are plugins, whether third-party or part of
Csound's repository, should be marked as such in the Csound Reference
Manual. These are not always available on all platforms.

What I would really have liked is a system where the man page for each
opcode is actually built into the opcode as an HTML resources, and there is
a tool that pulls out the pages and organizes them into a manual. That
would enable Csound front ends to interrogate Csound for current
documentation on each opcode, including plugins and third party opcodes.

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by tjingboem** [comment]
perhaps we can assign this issue (and perhaps others) with a Milestone label, so it can be discussed and dealt with in the next IRC meeting?

**Comment by tjingboem** [comment]
the list of third party opcodes so far:
- STKopcodes
- cudasynth and friends 
- faust opcodes

**Comment by mantaraya36** [comment]
Maybe VST should be in the list too?

**Comment by gogins** [comment]
The vst4cs opcodes, yes.
The FluidSynth opcodes, would they be considered "third party?"

Indeed, what defines "third party opcodes?"

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by tjingboem** [comment]
mmm...good question.
STK and Faust are to be downloaded separately from Csound, and as i just read you have to have Faust installed to get the faust opcodes running? Same with Loris a few years ago?
For cuda a lot of extra stuff has to be installed too (100M)

I just see these kinds of questions coming back from time to time and i thought it would be nice to have all this kind of information ready in the manual.

**Comment by gogins** [comment]
I'm still a bit puzzled. When I produce the Windows installer, everything
is self-contained. The STK source code is built into the STK opcodes, the
FluidSynth library is included, etc. For Faust though I see the point. I
don't include the Faust opcodes on Windows but if I did, the user would
have to install Faust, CLang, etc., to be able to use them.

Best,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by vlazzarini** [comment]
For the faust opcodes, you only need faust to build them.  They are distributed on OSX with no extra dependencies.

Victor Lazzarini
Dean of Arts, Celtic Studies, and Philosophy
Maynooth University
Ireland

**Comment by gogins** [comment]
That's what I'm talking about, unless I misunderstand you. I write some
Faust code, and the Faust opcodes produce plugin opcodes for Csound from my
code. For that I need Faust, and CLang, correct?

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by vlazzarini** [comment]
No, that's different.  These are the faust opcodes that have a JIT compiler in them, for which you need faustlib, but only to build them.

Victor Lazzarini
Dean of Arts, Celtic Studies, and Philosophy
Maynooth University
Ireland

**Comment by tjingboem** [comment]
it seems to me that this knowledge is very specialized information, depending on platform and certain present packages already available on that platform.
Perhaps this kind of information varies too quickly to want it to be included in the manual. An alternative to make the information available (but adaptable to rapid changes) is to put it in the Csound Wiki: 
https://github.com/csound/manual/wiki

Personally i still think, because the Loris/Faust/cuda etc. opcodes are a part of the manual, there should be an established place where the interested user can turn to in order to get information on what to do to get these opcodes in Csound working for his/her platform.
But that's me :)

Or we can just give the information when someone asks for it in the mailinglist. That works too.

**Comment by tjingboem** [comment]
Kelly Fitz has closed the issue regarding Csound support for the Loris opcodes:

- **status**: open --> wont-fix
- **Comment**:

closed for want of a developer qualified to manage the update.

**Comment by tjingboem** [comment]
i think we could transport the manual pages on the Loris opcodes to the  Deprecated Section, as there is nobody that will will try to make them working for Csound in the near future - so it seems.

This might stop some confusion on the Loris opcodes and will be clear for the users.

after that, we can close this subject

**Comment by tjingboem** [comment]
i think this issue is now resolved by the creation of the csound plugins repo
For every opcode that is part of this repo, a message on the manual page is added saying that it is now part of the plugins repo
