### ISSUE TITLE
GENpadsynth docs are wrong (missing arguments)

### ISSUE THREAD

**Issue by anton-k** [csound/manual#90]
The padsynth doc page for the reference manual is wrong.
[doc page](http://csound.github.io/docs/manual/GENpadsynth.html)

There are two missing parameters according to the source code.

~~~
   p8  harmonicStretchScale -- ratio of stretch of thre overtoes.

   **** missing args *****

    p9      Number specifying the shape of the bandwidth profile:

             1  Gaussian
             2  Square
             3  Exponential

    p10     Profile function parameter.

  ********************************

   p11-pN  The amplitudes of the partials (may be 0).
~~~

Also there is a broken link to the original paper at the end of the docs.
It should lead to the other site but it redirects to the csound's site.

**Comment by tjingboem** [comment]
it has been corrected by Michael in git a few months ago. Will be in the next release.

new excerpt: 
f # score_time table_size "padsynth" fundamental_frequency
    partial_bandwidth partial_scale harmonic_stretch profile_shape profile_shape_parameter
    partial1_amplitude [partial2_amplitude ...]

Initialization

table_size -- Function table size. Should be large, e.g. 2^18 == 262144. Must be a power of 2 or power-of-2 plus 1 (see f statement).

fundamental_frequency -- Fundamental frequency for the generated table.

partial_bandwidth -- Bandwidth of each partial in cents.

partial_scale -- Scaling factor for bandwidth of each partial (log of increase/decrease with partial frequency, 0 is no stretch or shrink).

harmonic_stretch -- Harmonic stretch/shrink for all partials (1 is harmonic).

profile_shape -- Number specifying the shape of the bandwidth profile: 1 = Gaussian, 2 = square, and 3 = exponential

profile_shape_parameter -- Parameter passed to the function generating the profile shape, e.g. exponent.

partial1_amplitude, partial2_amplitude, ... -- Amplitudes for each partial (may be zero).
