### ISSUE TITLE
fluidallout - missing sf_GMbank.sf2 soundfont in the example

### ISSUE THREAD

**Issue by boulangerlabs** [csound/manual#91]
midi channel 16 using instr 1
0dBFS level = 1.0
Created fluidEngine 0x0x7fcceeea7e70 with sampling rate = 44100.000000, chorus on, reverb on, channels 256, voices 4096.
INIT ERROR in instr 0: fluid: unable to load sf_GMbank.sf2
isfnum1	fluidLoad	"sf_GMbank.sf2"	giengine1	1	
Created fluidEngine 0x0x7fcce9efa450 with sampling rate = 44100.000000, chorus on, reverb on, channels 256, voices 4096.
Loading SoundFont : 22Bassoon.sf2.
fluidSynth: 0x0x7fcce9efa450  soundFontId: 1.
SoundFont:   1  Bank:   0  Preset:  70  Ethan Bassoon mono
header init errors

**Comment by tjingboem** [comment]
i remember that you, Richard has put sf_GMbank.sf2 in the csound/samples folder. The example however speaks of the folder manual/examples. 
I think this soundfont should be available in the manual/examples, along with the example wavs beats.wav, fox.wav etc.

If agreed, can someone please upload the soundfont to m,anual/examples?

**Comment by jpffitch** [comment]
Uploaded
