### ISSUE TITLE
fluidcontrol - man example doesn't run

### ISSUE THREAD

**Issue by boulangerlabs** [csound/manual#92]
STARTING FILE
Creating options
argc=3 Additional string "and"
Usage:	csound [-flags] orchfile scorefile
Legal flags are:
--help	print long usage options
-U unam	run utility program unam
-C	use Cscore processing of scorefile
-j N	use N threads in performance
-I	I-time only orch run
-n	no sound onto disk
-i fnam	sound input filename
-o fnam	sound output filename
-b N	sample frames (or -kprds) per software sound I/O buffer
-B N	samples per hardware sound I/O buffer
-A	create an AIFF format output soundfile
-W	create a WAV format output soundfile
-J	create an IRCAM format output soundfile
-h	no header on output soundfile
-c	8-bit signed_char sound samples
-8	8-bit unsigned_char sound samples
-u	ulaw sound samples
-s	short_int sound samples
-l	long_int sound samples
-f	float sound samples
-3	24bit sound samples
-r N	orchestra srate override
-k N	orchestra krate override
-K	Do not generate PEAK chunks
-v	verbose orch translation
-m N	tty message level. Sum of:
		1=note amps, 2=out-of-range msg, 4=warnings
		0/32/64/96=note amp format (raw,dB,colors)
		128=print benchmark information
-d	suppress all displays
-g	suppress graphics, use ascii displays
-G	suppress graphics, use Postscript displays
-x fnam	extract from score.srt using extract file 'fnam'
-t N	use uninterpreted beats of the score, initially at tempo N
-t 0	use score.srt for sorted score rather than a temporary
-L dnam	read Line-oriented realtime score events from device 'dnam'
-M dnam	read MIDI realtime events from device 'dnam'
-F fnam	read MIDIfile event stream from file 'fnam'
-R	continually rewrite header while writing soundfile (WAV/AIFF)
-H#	print heartbeat style 1, 2 or 3 at each soundfile write
-N	notify (ring the bell) when score or miditrack is done
-T	terminate the performance when miditrack is done
-D	defer GEN01 soundfile loads until performance time
-Q dnam	select MIDI output device
-z	List opcodes in this version
-Z	Dither output
flag defaults: csound -s -otest -b1024 -B4096 -m135
Csound Command ERROR:	too many arguments

**Comment by jpffitch** [comment]
I do not understand the error message but there is also a missing midi file (Anna.mid)

**Comment by jpffitch** [comment]
comments are clearly not allowed in option statement.  I will investigate

**Comment by jpffitch** [comment]
Fixed in git -- it needs a space before comment

**Comment by tjingboem** [comment]
Anna.mid is a midi file that can be found on the internet. It is a song from The Beatles. At the time when i was working on examples for the manual, I did not copy Anna.mid into the example folder of the manual, in order to prevent any conflict regarding licences.

**Comment by tjingboem** [comment]
added a comment on where to find Anna.mid
