### ISSUE TITLE
fprints manual example - missing file  - 

### ISSUE THREAD

**Issue by boulangerlabs** [csound/manual#94]
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
; Audio out   Audio in
-odac           -iadc    ;;;RT audio I/O
; For Non-realtime ouput leave only the line below:
; -o fprints.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

/* Written by Matt Ingalls, edited by Kevin Conder. */
; Initialize the global variables.
sr = 44100
also, you might want this and all manual examples that try to write files (temp or otherwise)  to print to the current working directory or to the user's home directory

kr = 4410
ksmps = 10
nchnls = 1

; Instrument #1 - a score generator example.
instr 1
  ; Print to the file "my.sco".
  fprints "my.sco", "%!Generated score by ma++\\n \\n"
endin

</CsInstruments>
<CsScore>

/* Written by Matt Ingalls, edited by Kevin Conder. */
; Play Instrument #1.
i 1 0 0.001

</CsScore>
</CsoundSynthesizer>

**Comment by jpffitch** [comment]
It runs if you can write to te directory in which you are running.  User error
