### ISSUE TITLE
No rule to make target 'examples/opcode1.xml'

### ISSUE THREAD

**Issue by merlinusambrosius** [csound/manual#96]
I am building using msys64.  I am building this using the instructions found [here](https://github.com/csound/csound/tree/develop/mingw64).  During the build process, I am getting an error:
`mingw32-make[1]: *** No rule to make target 'examples/opcode1.xml', needed by 'html'.  Stop.
`

**Comment by jpffitch** [comment]
Inadvertantly moved fro examples to opcodes.  Restired noow

OTOH wmy is itt required by make?
