### ISSUE TITLE
Input argument of chnparams is undocumented

### ISSUE THREAD

**Issue by nwhetsell** [csound/manual#98]
Running

```
csound --list-opcodes1
```

shows that `chnparams` takes a string as input:

```
chnparams   iiiiii      S
```

This input argument seems to be missing from https://csound.github.io/docs/manual/chnparams.html.

The source file for `chnparams` is https://github.com/csound/manual/blob/master/opcodes/chnparams.xml.

**Comment by jpffitch** [comment]
Thanks; just modified source and checking; will commit soon.
