### ISSUE TITLE
fluidcomplex.csd contains merge conflict marks

### ISSUE THREAD

**Issue by nwhetsell** [csound/manual#99]
[fluidcomplex.csd](https://github.com/csound/manual/blob/270b30f7106c7ff4099b94a34999b88b75f90070/examples/fluidcomplex.csd) contains merge conflict marks at lines [4](https://github.com/csound/manual/blob/270b30f7106c7ff4099b94a34999b88b75f90070/examples/fluidcomplex.csd#L4), [7](https://github.com/csound/manual/blob/270b30f7106c7ff4099b94a34999b88b75f90070/examples/fluidcomplex.csd#L7), and [10](https://github.com/csound/manual/blob/270b30f7106c7ff4099b94a34999b88b75f90070/examples/fluidcomplex.csd#L10).

**Comment by jpffitch** [comment]
Fixed in git
